# Generated by Django 4.1.6 on 2023-04-08 02:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0041_remove_area_aggregate_to_remove_area_delegation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hex_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('clave', models.CharField(blank=True, max_length=30, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('medical_speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_license', models.CharField(blank=True, max_length=20, null=True)),
                ('is_aggregate', models.BooleanField(default=False)),
                ('aggregate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.doctor')),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.institution')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hex_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('cie10', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('motive', models.TextField(blank=True, null=True)),
                ('is_aggregate', models.BooleanField(default=False)),
                ('aggregate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.diagnosis')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hex_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave del área')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Nombre del área')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del área')),
                ('is_aggregate', models.BooleanField(default=False)),
                ('aggregate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.area')),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.institution')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'catalog_area',
            },
        ),
    ]
