# Generated by Django 4.1.6 on 2023-04-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('hex_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('key2', models.CharField(blank=True, help_text='key2', max_length=20, null=True)),
                ('own_key2', models.CharField(blank=True, help_text='own', max_length=255, null=True)),
                ('medicine_type', models.CharField(blank=True, help_text='mt', max_length=90, null=True)),
                ('component_name', models.TextField(blank=True, help_text='comp', null=True)),
                ('presentation_type', models.CharField(blank=True, help_text='pt', max_length=255, null=True)),
                ('presentation_description', models.TextField(blank=True, help_text='pres', null=True)),
                ('container_name', models.TextField(blank=True, help_text='cont', null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.component')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.container')),
                ('entity', models.ForeignKey(blank=True, help_text='ent', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.entity')),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.presentation')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='MedicalUnit',
            fields=[
                ('hex_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('delegation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction_key', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('attention_level', models.CharField(blank=True, max_length=80, null=True)),
                ('clues_key', models.CharField(blank=True, max_length=12, null=True)),
                ('own_key', models.CharField(blank=True, max_length=255, null=True)),
                ('key_issste', models.CharField(blank=True, max_length=12, null=True)),
                ('typology_key', models.CharField(blank=True, max_length=18, null=True)),
                ('typology_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.clues', verbose_name='CLUES')),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation', verbose_name='Delegación')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.entity', verbose_name='Entity')),
            ],
            options={
                'verbose_name': 'Unidad Médica',
                'verbose_name_plural': 'Unidades Médicas',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('hex_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_aggregate', models.BooleanField(blank=True, default=False, null=True)),
                ('clave', models.CharField(blank=True, max_length=30, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_license', models.CharField(blank=True, max_length=20, null=True)),
                ('aggregate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.doctor')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.entity')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('hex_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_aggregate', models.BooleanField(blank=True, default=False, null=True)),
                ('cie10', models.CharField(blank=True, max_length=40, null=True)),
                ('own_key', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('motive', models.TextField(blank=True, null=True)),
                ('aggregate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.diagnosis')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('hex_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_aggregate', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('aggregate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
            ],
            options={
                'verbose_name': 'Clasificación de entrega',
                'verbose_name_plural': 'Clasificaciones de Entrega',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('hex_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_aggregate', models.BooleanField(blank=True, default=False, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave del área')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Nombre del área')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del área')),
                ('aggregate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.area')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.entity')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
    ]
