# Generated by Django 4.1.6 on 2024-09-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='professional_license',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
