# Generated by Django 4.1.6 on 2023-09-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
