# Generated by Django 4.1.6 on 2023-04-10 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0043_remove_clues_jurisdiction_obj_clues_delegation_and_more'),
        ('medicine', '0003_alter_component_options_alter_container_options_and_more'),
        ('med_cat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='delegation',
        ),
        migrations.RemoveField(
            model_name='area',
            name='hex_hash',
        ),
        migrations.RemoveField(
            model_name='area',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='area',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='hex_hash',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='delegation',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hex_hash',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='uuid',
        ),
        migrations.AddField(
            model_name='area',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='hash',
            field=models.CharField(default=1, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='hash',
            field=models.CharField(default=1, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='own_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='hash',
            field=models.CharField(default=1, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cie10',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('key2', models.CharField(help_text='key2', max_length=20)),
                ('own_key', models.CharField(blank=True, help_text='own', max_length=255, null=True)),
                ('medicine_type', models.CharField(blank=True, help_text='mt', max_length=90, null=True)),
                ('component_name', models.TextField(blank=True, help_text='comp', null=True)),
                ('presentation_description', models.TextField(blank=True, help_text='pres', null=True)),
                ('container_name', models.TextField(blank=True, help_text='cont', null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.component')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.container')),
                ('entity', models.ForeignKey(blank=True, help_text='ent', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.entity')),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.presentation')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='MedicalUnity',
            fields=[
                ('hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('delegation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('attention_level', models.CharField(blank=True, max_length=255, null=True)),
                ('clues_key', models.CharField(blank=True, max_length=12, null=True)),
                ('own_key', models.CharField(blank=True, max_length=255, null=True)),
                ('key_issste', models.CharField(blank=True, max_length=30, null=True)),
                ('typology_key', models.CharField(blank=True, max_length=18, null=True)),
                ('typology_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.clues', verbose_name='CLUES')),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation', verbose_name='Delegación')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.entity', verbose_name='Entity')),
            ],
            options={
                'verbose_name': 'Unidad Médica',
                'verbose_name_plural': 'Unidades Médicas',
            },
        ),
    ]
