# Generated by Django 4.1.6 on 2023-10-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0002_delivered_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered',
            name='alternative_names',
            field=models.TextField(blank=True, help_text='Separados por coma', null=True, verbose_name='Nombres alternativos'),
        ),
    ]
