# Generated by Django 4.1.6 on 2023-04-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0002_remove_area_delegation_remove_area_hex_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='hash',
            new_name='hex_hash',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='hash',
            new_name='hex_hash',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='hash',
            new_name='hex_hash',
        ),
        migrations.RenameField(
            model_name='medicalunity',
            old_name='hash',
            new_name='hex_hash',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='hash',
            new_name='hex_hash',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='own_key',
            new_name='own_key2',
        ),
    ]
