# Generated by Django 4.1.6 on 2024-09-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0002_alter_doctor_professional_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='professional_license',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
