# Generated by Django 4.1.6 on 2023-04-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0046_agency_entity'),
        ('formula', '0027_rename_medical_unity_prescription_medical_unit'),
        ('med_cat', '0003_rename_hash_area_hex_hash_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalUnity',
            new_name='MedicalUnit',
        ),
    ]
