# Generated by Django 4.1.6 on 2024-12-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_group_unidecode_name_alter_container_status_review'),
        ('med_cat', '0003_alter_doctor_professional_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.component'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.container'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.presentation'),
        ),
    ]
