# Generated by Django 4.1.6 on 2023-04-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0004_rename_medicalunity_medicalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalunit',
            name='jurisdiction_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='presentation_type',
            field=models.CharField(blank=True, help_text='pt', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalunit',
            name='attention_level',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='medicalunit',
            name='key_issste',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
