# Generated by Django 4.1.6 on 2024-03-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_rename_entity_provider_alter_provider_table'),
        ('med_cat', '0004_alter_medicalunit_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalunit',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.provider', verbose_name='Provider'),
        ),
    ]
