# Generated by Django 4.1.6 on 2023-04-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0005_medicalunit_jurisdiction_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='is_aggregate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='is_aggregate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_aggregate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
