# Generated by Django 4.1.6 on 2024-03-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0005_alter_medicalunit_entity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='medicalunit',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='entity',
            new_name='provider',
        ),
    ]
