# Generated by Django 4.1.6 on 2023-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0006_alter_area_is_aggregate_alter_diagnosis_is_aggregate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='key2',
            field=models.CharField(blank=True, help_text='key2', max_length=20, null=True),
        ),
    ]
