# Generated by Django 4.1.6 on 2023-04-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0007_alter_medicament_key2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('hex_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_aggregate', models.BooleanField(blank=True, default=False, null=True)),
                ('aggregate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
            ],
            options={
                'verbose_name': 'Clasificación de entrega',
                'verbose_name_plural': 'Clasificaciones de Entrega',
            },
        ),
    ]
