# Generated by Django 4.1.6 on 2023-04-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0009_alter_doctor_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='aggregate_to',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='aggregate_to',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='aggregate_to',
        ),
    ]
