# Generated by Django 4.1.6 on 2023-04-16 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0010_remove_area_aggregate_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='aggregate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.area'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='aggregate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.diagnosis'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='aggregate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.doctor'),
        ),
    ]
