# Generated by Django 2.2.25 on 2022-03-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'DocumentType',
                'verbose_name_plural': 'DocumentTypes',
                'db_table': 'desabasto_documenttype',
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('clave_medico', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_medico', models.CharField(max_length=255)),
                ('especialidad_medico', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Medic',
                'verbose_name_plural': 'Medics',
                'db_table': 'desabasto_medic',
            },
        ),
        migrations.CreateModel(
            name='MedicalSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MedicalSpeciality',
                'verbose_name_plural': 'MedicalSpecialitys',
                'db_table': 'desabasto_medicalspeciality',
            },
        ),
        migrations.CreateModel(
            name='RecipeMedicine2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=48)),
                ('clave_medicamento', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_prescrita', models.IntegerField(blank=True, null=True)),
                ('cantidad_entregada', models.IntegerField(blank=True, null=True)),
                ('precio_medicamento', models.FloatField(blank=True, null=True)),
                ('rn', models.IntegerField(blank=True, null=True)),
                ('delivered', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'RecipeItem',
                'verbose_name_plural': 'RecipeItems',
                'db_table': 'desabasto_recipemedicine2',
            },
        ),
        migrations.CreateModel(
            name='RecipeReport2',
            fields=[
                ('folio_ocamis', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('tipo_documento', models.IntegerField()),
                ('folio_documento', models.CharField(max_length=40)),
                ('iso_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('iso_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('iso_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('delegacion', models.IntegerField(blank=True, null=True)),
                ('clues', models.IntegerField(blank=True, null=True)),
                ('medico', models.CharField(blank=True, max_length=48, null=True)),
                ('year_month', models.IntegerField(blank=True, null=True)),
                ('clave_presupuestal', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_atencion', models.IntegerField(blank=True, null=True)),
                ('delivered', models.CharField(blank=True, max_length=3, null=True)),
                ('anomaly', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RecipeReport2',
                'verbose_name_plural': 'RecipeReports2',
                'db_table': 'desabasto_recipereport2',
            },
        ),
        migrations.CreateModel(
            name='RecipeReportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('processing_date', models.DateTimeField(auto_now=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('successful', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RecipeReportLog',
                'verbose_name_plural': 'RecipeReportLogs',
                'db_table': 'desabasto_recipereportlog',
            },
        ),
    ]
