# Generated by Django 2.2.25 on 2022-03-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='especialidad_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.MedicalSpeciality'),
        ),
        migrations.AlterField(
            model_name='recipemedicine2',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.RecipeReport2'),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='clues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.CLUES'),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='delegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.State'),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Medic'),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.DocumentType'),
        ),
    ]
