# Generated by Django 2.2.25 on 2022-07-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20220308_1847'),
        ('catalog', '0006_auto_20220323_1545'),
        ('recipe', '0002_auto_20220308_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipemedicine2',
            options={'verbose_name': 'Insumos', 'verbose_name_plural': 'Insumos (medicamentos)'},
        ),
        migrations.AlterModelOptions(
            name='recipereport2',
            options={'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.RemoveField(
            model_name='recipemedicine2',
            name='clave_medicamento',
        ),
        migrations.AddField(
            model_name='medic',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Institution'),
        ),
        migrations.AddField(
            model_name='recipemedicine2',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Container'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='especialidad_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.MedicalSpeciality'),
        ),
        migrations.AlterModelTable(
            name='medic',
            table='medic',
        ),
    ]
