# Generated by Django 2.2.25 on 2022-07-22 17:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0004_auto_20220722_1215'),
        ('recipe', '0003_auto_20220706_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('short_name', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Clasificación de entrega',
                'verbose_name_plural': 'Clasificaciones de Entrega',
            },
        ),
        migrations.CreateModel(
            name='MissingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_value', models.TextField(blank=True, null=True)),
                ('final_value', models.TextField(blank=True, null=True)),
                ('other_values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_rows.Column')),
            ],
            options={
                'verbose_name': 'Documento Faltante',
                'verbose_name_plural': 'Documentos Faltantes',
            },
        ),
        migrations.CreateModel(
            name='MissingRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('row_seq', models.IntegerField(default=1)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_rows.File')),
            ],
            options={
                'verbose_name': 'Renglón faltante',
                'verbose_name_plural': 'Renglones faltantes',
            },
        ),
        migrations.DeleteModel(
            name='RecipeReportLog',
        ),
        migrations.RenameField(
            model_name='recipereport2',
            old_name='tipo_documento',
            new_name='type_document',
        ),
        migrations.RemoveField(
            model_name='recipemedicine2',
            name='rn',
        ),
        migrations.RemoveField(
            model_name='recipereport2',
            name='anomaly',
        ),
        migrations.RemoveField(
            model_name='recipereport2',
            name='nivel_atencion',
        ),
        migrations.RemoveField(
            model_name='recipereport2',
            name='year_month',
        ),
        migrations.AddField(
            model_name='recipemedicine2',
            name='row_seq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipereport2',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_rows.File'),
        ),
        migrations.AlterField(
            model_name='recipemedicine2',
            name='cantidad_entregada',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipemedicine2',
            name='cantidad_prescrita',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipemedicine2',
            name='delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Delivered'),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='delegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Delegation'),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Delivered'),
        ),
        migrations.AddField(
            model_name='missingfield',
            name='missing_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.MissingRow'),
        ),
    ]
