# Generated by Django 2.2.25 on 2022-07-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220719_1927'),
        ('files_rows', '0004_auto_20220722_1215'),
        ('recipe', '0004_auto_20220722_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeReport2',
            new_name='Recipe',
        ),
    ]
