# Generated by Django 2.2.25 on 2022-07-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20220308_1847'),
        ('recipe', '0005_auto_20220722_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeMedicine2',
            new_name='Medicine',
        ),
    ]
