# Generated by Django 2.2.25 on 2022-07-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20220722_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingrow',
            name='recipe_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Medicine'),
        ),
        migrations.AddField(
            model_name='missingrow',
            name='recipe_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
