# Generated by Django 2.2.25 on 2022-07-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20220308_1847'),
        ('catalog', '0008_auto_20220719_1927'),
        ('files_rows', '0012_auto_20220726_1321'),
        ('recipe', '0008_auto_20220722_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prescrita', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cantidad_entregada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('precio_medicamento', models.FloatField(blank=True, null=True)),
                ('row_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Container')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_rows.DataFile')),
                ('delivered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Delivered')),
            ],
            options={
                'verbose_name': 'Insumos',
                'verbose_name_plural': 'Insumos (medicamentos)',
                'db_table': 'desabasto_recipemedicine2',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('folio_ocamis', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('iso_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('iso_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('folio_documento', models.CharField(max_length=40)),
                ('iso_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('clave_presupuestal', models.CharField(blank=True, max_length=20, null=True)),
                ('clues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.CLUES')),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Delegation')),
                ('delivered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Delivered')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'desabasto_recipereport2',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='clues',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='delegacion',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='type_document',
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='clave_medico',
            new_name='clave_doctor',
        ),
        migrations.RenameField(
            model_name='missingfield',
            old_name='column',
            new_name='name_column',
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='recipe_medicine',
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='recipe_report',
        ),
        migrations.RenameModel(
            old_name='Medic',
            new_name='Doctor',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='type_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.DocumentType'),
        ),
        migrations.AddField(
            model_name='droug',
            name='recipe_prescr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Prescription'),
        ),
        migrations.AddField(
            model_name='missingrow',
            name='droug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Droug'),
        ),
        migrations.AddField(
            model_name='missingrow',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.Prescription'),
        ),
    ]
