# Generated by Django 4.1.6 on 2024-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefile',
            name='self_repeated_count',
            field=models.IntegerField(default=0),
        ),
    ]
