# Generated by Django 4.1.13 on 2024-07-16 08:19

from django.db import migrations


# def assign_petition_file_control(apps, schema_editor):
#     PetitionFileControl = apps.get_model('inai', 'PetitionFileControl')
#     for pfc in PetitionFileControl.objects.all():
#         pfc.data_files.update(file_control=pfc.file_control, petition=pfc.petition)


def create_is_duplicated(apps, schema_editor):
    DataFile = apps.get_model('respond', 'DataFile')
    DataFile.objects.filter(status_process__name="duplicated")\
        .update(is_duplicated=True)
    DataFile.objects.filter(status_process__name="not_duplicated")\
        .update(is_duplicated=False)
    DataFile.objects.filter(status_process__isnull=False)\
        .update(status_process=None)

def delete_status_process(apps, schema_editor):
    StatusControl = apps.get_model('category', 'StatusControl')
    StatusControl.objects.filter(group="process").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(assign_petition_file_control),
        # migrations.RunPython(create_is_duplicated),
        migrations.RunPython(delete_status_process),
    ]
