# Generated by Django 4.1.6 on 2024-03-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='tablefile',
            old_name='entity',
            new_name='provider',
        ),
    ]
