# Generated by Django 4.1.6 on 2024-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0002_tablefile_self_repeated_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetfile',
            name='self_repeated_count',
            field=models.IntegerField(default=0, verbose_name='Repetidos'),
        ),
    ]
