# Generated by Django 4.1.6 on 2024-03-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0002_rename_entity_datafile_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossingsheet',
            old_name='entity_month',
            new_name='month_record',
        ),
        migrations.RenameField(
            model_name='crossingsheet',
            old_name='entity_week',
            new_name='week_record',
        ),
        migrations.RenameField(
            model_name='sheetfile',
            old_name='entity_months',
            new_name='month_records',
        ),
        migrations.RenameField(
            model_name='tablefile',
            old_name='entity_week',
            new_name='week_record',
        ),
    ]
