# Generated by Django 4.1.6 on 2024-09-23 22:41

from django.db import migrations, models
import django.db.models.deletion
import respond.models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0005_weekrecord_self_repeated_count'),
        ('data_param', '0002_delete_dictionaryfile'),
        ('geo', '0002_remove_delegation_clues_alter_clues_provider'),
        ('respond', '0003_sheetfile_self_repeated_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetfile',
            name='rx_count',
            field=models.IntegerField(default=0, verbose_name='Prescripciones (rx)'),
        ),
        migrations.AlterUniqueTogether(
            name='tablefile',
            unique_together={('lap_sheet', 'collection', 'year', 'iso_week', 'iso_delegation')},
        ),
        migrations.CreateModel(
            name='MonthTableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=120)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=respond.models.set_upload_month_path)),
                ('inserted', models.BooleanField(default=False)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_param.collection')),
                ('month_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_table_files', to='inai.monthrecord')),
            ],
            options={
                'verbose_name': 'Archivo de mes',
                'verbose_name_plural': '7. Archivos de mes',
            },
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='is_for_edition',
        ),
    ]
