# Generated by Django 4.1.6 on 2024-10-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0004_alter_sheetfile_rx_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyfile',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replyfile',
            name='instant_access',
            field=models.BooleanField(default=True, verbose_name='Acceso instantáneo'),
        ),
    ]
