# Generated by Django 4.1.6 on 2024-05-02 20:28

from django.db import migrations, models


def delete_status_process(apps, schema_editor):
    StatusControl = apps.get_model('category', 'StatusControl')
    StatusControl.objects.filter(group="process").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0005_datafile_is_duplicated_datafile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='is_duplicated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Duplicado'),
        ),
        migrations.RunPython(delete_status_process),
    ]
