# Generated by Django 4.1.6 on 2024-12-16 17:21

from django.db import migrations, models
import respond.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0005_replyfile_available_until_replyfile_instant_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(max_length=255, storage=storages.backends.s3boto3.S3Boto3Storage(gzip=True, object_parameters={'StorageClass': 'GLACIER_IR'}), upload_to=respond.models.set_upload_data_file_path),
        ),
        migrations.AlterField(
            model_name='monthtablefile',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(object_parameters={'StorageClass': 'DEEP_ARCHIVE'}), upload_to=respond.models.set_upload_month_path),
        ),
        migrations.AlterField(
            model_name='sheetfile',
            name='file',
            field=models.FileField(max_length=255, storage=storages.backends.s3boto3.S3Boto3Storage(gzip=True, object_parameters={'StorageClass': 'GLACIER_IR'}), upload_to=respond.models.set_upload_sheet_file_path),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='file',
            field=models.FileField(max_length=255, storage=storages.backends.s3boto3.S3Boto3Storage(gzip=True, object_parameters={'StorageClass': 'STANDARD_IA'}), upload_to=respond.models.set_upload_table_file_path),
        ),
    ]
