# Generated by Django 4.1.6 on 2024-05-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0005_datafile_is_duplicated_datafile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='is_duplicated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Duplicado'),
        ),
    ]
