# Generated by Django 4.1.6 on 2024-05-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0006_alter_datafile_is_duplicated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='status_process',
        ),
    ]
