# Generated by Django 4.1.6 on 2024-05-04 20:32

from django.db import migrations


def delete_status_process(apps, schema_editor):
    StatusControl = apps.get_model('category', 'StatusControl')
    StatusControl.objects.filter(group="process").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0006_alter_datafile_is_duplicated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='status_process',
        ),
        migrations.RunPython(delete_status_process),
    ]
