# Generated by Django 4.1.6 on 2024-07-01 19:59

from django.db import migrations, models
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0009_alter_datafile_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(max_length=255, upload_to=inai.models.set_upload_path),
        ),
    ]
