# Generated by Django 4.1.6 on 2024-07-01 20:02

from django.db import migrations, models
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0010_alter_datafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyfile',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=inai.models.set_upload_path, verbose_name='archivo'),
        ),
    ]
