# Generated by Django 4.1.6 on 2024-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0093_requesttemplate_data_groups_petitiondatagroup'),
        ('respond', '0011_alter_replyfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyfile',
            name='month_records',
            field=models.ManyToManyField(blank=True, related_name='reply_files', to='inai.monthrecord'),
        ),
    ]
