# Generated by Django 4.1.6 on 2024-07-08 18:41

from django.db import migrations, models
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0012_replyfile_month_records'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetfile',
            options={'ordering': ['id'], 'verbose_name': 'Archivo de hojas (csv)', 'verbose_name_plural': '4. Archivos de hojas (Sheets .csv)'},
        ),
        migrations.AddField(
            model_name='datafile',
            name='sample_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=inai.models.set_upload_path, verbose_name='Archivo con muestra'),
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='sample_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=inai.models.set_upload_path, verbose_name='Archivo con muestra'),
        ),
    ]
