# Generated by Django 4.1.6 on 2024-07-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0014_remove_replyfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
