# Generated by Django 4.1.6 on 2023-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanfunction',
            name='ready_code',
            field=models.CharField(choices=[('ready_alone', 'Listo, solito'), ('complement', 'Listo'), ('not_ready', 'Not ready')], default='not_ready', max_length=12, verbose_name='Ready'),
        ),
        migrations.AlterField(
            model_name='cleanfunction',
            name='for_all_data',
            field=models.BooleanField(default=False, help_text='Es una transformación para todo el archivo', verbose_name='All'),
        ),
        migrations.AlterField(
            model_name='cleanfunction',
            name='priority',
            field=models.SmallIntegerField(default=5, help_text='Nivel de prioridad (ordenación)', verbose_name='orden'),
        ),
    ]
