# Generated by Django 2.2.25 on 2022-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0002_auto_20220801_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalfield',
            options={'ordering': ['collection', 'name'], 'verbose_name': 'Campo final', 'verbose_name_plural': 'Campos finales (en DB)'},
        ),
    ]
