# Generated by Django 4.1.6 on 2023-05-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0002_cleanfunction_ready_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanfunction',
            name='ready_code',
            field=models.CharField(choices=[('ready_alone', '✳️Listo, solo'), ('ready', 'Listo PREVIO'), ('ready 1', '1️⃣Listo 1'), ('ready 2', '2️⃣Listo 2'), ('ready CAT', '✅Listo CAT'), ('ready EXT', '✅Listo Ext'), ('not_ready', '❌Not ready')], default='not_ready', max_length=12, verbose_name='Ready'),
        ),
    ]
