# Generated by Django 4.1.6 on 2024-12-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0002_delete_dictionaryfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalfield',
            name='variations',
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_fields', to='data_param.collection'),
        ),
    ]
