# Generated by Django 4.1.6 on 2023-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0003_alter_cleanfunction_ready_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='snake_name',
            field=models.CharField(default='unknown', max_length=225, verbose_name='Nombre para distinguirlo en el código'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='model_name',
            field=models.CharField(max_length=225, verbose_name='Nombre del Modelo Django'),
        ),
    ]
