# Generated by Django 2.2.25 on 2022-08-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0003_auto_20220808_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='public_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
