# Generated by Django 4.1.6 on 2023-05-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0004_collection_snake_name_alter_collection_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='model_name',
            field=models.CharField(help_text='Nombre del modelo en Django (Meta.model_name)', max_length=225, verbose_name='Nombre en Django'),
        ),
    ]
