# Generated by Django 2.2.25 on 2022-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0004_auto_20220809_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanfunction',
            options={'verbose_name': 'Función de limpieza y transformación', 'verbose_name_plural': 'Funciones de limpieza y transformación'},
        ),
        migrations.AlterField(
            model_name='cleanfunction',
            name='for_all_data',
            field=models.BooleanField(default=False, verbose_name='Es una transformación para toda la info'),
        ),
    ]
