# Generated by Django 4.1.6 on 2023-06-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_alter_entity_options_alter_entity_state'),
        ('data_param', '0005_alter_collection_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontrol',
            name='real_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.entity', verbose_name='Proveedor real'),
        ),
    ]
