# Generated by Django 2.2.25 on 2022-08-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0005_auto_20220811_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_param.DataGroup')),
            ],
            options={
                'verbose_name': '1.2 Grupo de Parametros',
                'verbose_name_plural': 'Grupos de Parametros',
            },
        ),
        migrations.AddField(
            model_name='finalfield',
            name='parameter_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.ParameterGroup'),
        ),
    ]
