# Generated by Django 2.2.25 on 2022-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0006_auto_20220816_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalfield',
            options={'ordering': ['parameter_group', 'collection', '-is_common', 'verbose_name'], 'verbose_name': 'Campo final', 'verbose_name_plural': 'Campos finales (en DB)'},
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='in_data_base',
            field=models.BooleanField(default=False, help_text='Ya está en la base de datos comprobado', verbose_name='En DB'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Es común'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='verified',
            field=models.BooleanField(default=False, help_text='Ricardo ya verificó que todos los parámetros están bien', verbose_name='Verificado'),
        ),
    ]
