# Generated by Django 4.1.6 on 2023-08-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0007_alter_collection_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filecontrol',
            table=None,
        ),
        migrations.AlterModelTable(
            name='namecolumn',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transformation',
            table=None,
        ),
    ]
