# Generated by Django 2.2.25 on 2022-08-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0008_auto_20220817_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanfunction',
            options={'ordering': ['public_name'], 'verbose_name': 'Función de limpieza y transformación', 'verbose_name_plural': 'Funciones de limpieza y transformación'},
        ),
        migrations.AlterField(
            model_name='cleanfunction',
            name='for_all_data',
            field=models.BooleanField(default=False, help_text='Es una transformación para toda la info', verbose_name='Es general'),
        ),
        migrations.AlterField(
            model_name='cleanfunction',
            name='priority',
            field=models.SmallIntegerField(default=5, help_text='Nivel de prioridad (5 niveles)', verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='cleanfunction',
            name='restricted_field',
            field=models.ForeignKey(blank=True, help_text='Campo o variable al cual solo puede aplicarse', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.FinalField', verbose_name='Campo exclusivo'),
        ),
    ]
