# Generated by Django 4.1.6 on 2023-11-30 17:37

from django.db import migrations, models


def standardize_name(apps, schema_editor):
    from scripts.common import text_normalizer
    # from data_param.models import NameColumn
    NameColumn = apps.get_model('data_param', 'NameColumn')
    names_to_update = []
    for name_col in NameColumn.objects.filter(name_in_data__isnull=False):
        std_name_in_data = text_normalizer(name_col.name_in_data, True)
        names_to_update.append(
            NameColumn(id=name_col.id, std_name_in_data=std_name_in_data))
    NameColumn.objects.bulk_update(names_to_update, ['std_name_in_data'])


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0008_alter_filecontrol_table_alter_namecolumn_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecolumn',
            name='std_name_in_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la columna normalizado'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='name_in_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la columna real'),
        ),
        migrations.RunPython(standardize_name),
    ]
