# Generated by Django 4.1.6 on 2024-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0009_namecolumn_std_name_in_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecolumn',
            name='destination',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Pestaña Destino'),
        ),
    ]
