# Generated by Django 2.2.25 on 2022-08-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20220822_1708'),
        ('data_param', '0009_auto_20220818_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanfunction',
            name='column_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='col_type_functions', to='category.ColumnType', verbose_name='Tipo de columna'),
        ),
    ]
