# Generated by Django 2.2.25 on 2022-08-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0010_cleanfunction_column_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanfunction',
            options={'ordering': ['priority', 'public_name'], 'verbose_name': 'Función de limpieza y transformación', 'verbose_name_plural': 'Funciones de limpieza y transformación'},
        ),
    ]
