# Generated by Django 2.2.25 on 2022-08-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0011_auto_20220823_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanfunction',
            name='priority',
            field=models.SmallIntegerField(default=5, help_text='Nivel de prioridad (ordenación)', verbose_name='Prioridad'),
        ),
    ]
