# Generated by Django 2.2.25 on 2022-08-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0012_auto_20220825_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datagroup',
            old_name='name',
            new_name='public_name',
        ),
    ]
