# Generated by Django 4.1.6 on 2024-03-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0012_rename_real_entity_filecontrol_real_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionaryfile',
            old_name='entity',
            new_name='provider',
        ),
    ]
