# Generated by Django 2.2.25 on 2022-08-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0013_auto_20220827_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre (devs)'),
        ),
        migrations.AlterField(
            model_name='datagroup',
            name='public_name',
            field=models.CharField(max_length=80, verbose_name='Nombre público'),
        ),
    ]
