# Generated by Django 4.1.6 on 2024-04-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0013_rename_entity_dictionaryfile_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametergroup',
            options={'ordering': ['order'], 'verbose_name': 'Agrupación de campos finales', 'verbose_name_plural': '1.2 Agrupaciones de campos finales'},
        ),
        migrations.AddField(
            model_name='parametergroup',
            name='icon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='parametergroup',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
