# Generated by Django 2.2.25 on 2022-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0014_auto_20220827_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfield',
            name='need_for_viz',
            field=models.BooleanField(default=False, help_text='Se utiliza en indicadores de transparencia', verbose_name='para data viz'),
        ),
    ]
