# Generated by Django 4.1.6 on 2024-04-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0014_alter_parametergroup_options_parametergroup_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecolumn',
            name='manual_validation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Validación manual'),
        ),
        migrations.AddField(
            model_name='namecolumn',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
