# Generated by Django 4.1.6 on 2024-04-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0015_namecolumn_manual_validation_namecolumn_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanfunction',
            name='ready_code',
            field=models.CharField(choices=[('ready_alone', '✳️Listo, solo'), ('ready', 'Listo PREVIO'), ('ready_shared', '✳️Listo, compartido'), ('ready 1', '1️⃣Listo 1'), ('ready 2', '2️⃣Listo 2'), ('ready CAT', '✅Listo CAT'), ('ready EXT', '✅Listo Ext'), ('need_value', '⚠️Necesita valor'), ('not_ready', '❌Not ready')], default='not_ready', max_length=12, verbose_name='Ready'),
        ),
    ]
