# Generated by Django 2.2.25 on 2022-08-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0015_finalfield_need_for_viz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datagroup',
            options={'verbose_name': 'Grupo de datos solicitados', 'verbose_name_plural': 'Grupos de datos solicitados'},
        ),
        migrations.AlterModelOptions(
            name='parametergroup',
            options={'verbose_name': 'Agrupación de campos finales', 'verbose_name_plural': 'Agrupaciones de campos finales'},
        ),
    ]
