# Generated by Django 4.1.6 on 2024-05-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0016_alter_cleanfunction_ready_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filecontrol',
            old_name='status_register',
            new_name='old_status_register',
        ),
    ]
