# Generated by Django 2.2.25 on 2022-09-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0016_auto_20220831_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalfield',
            options={'ordering': ['parameter_group', '-is_common', 'verbose_name'], 'verbose_name': 'Campo final', 'verbose_name_plural': 'Campos finales (en DB)'},
        ),
    ]
