# Generated by Django 4.1.5 on 2023-01-22 07:41

import data_param.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0017_auto_20220911_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanfunction',
            name='addl_params',
            field=models.JSONField(blank=True, null=True, verbose_name='Otras configuraciones'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='addl_params',
            field=models.JSONField(verbose_name='Otras configuraciones'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='addl_params',
            field=models.JSONField(blank=True, help_text='Por ejemplo, max_length, null, blank, help_text, así como otras configuraciones que se nos vayan ocurriendo', null=True, verbose_name='Otras configuraciones'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='variations',
            field=models.JSONField(blank=True, help_text='Nombres como pueden venir en las tablas de INAI', null=True, verbose_name='Otros posibles nombres (variaciones)'),
        ),
    ]
