# Generated by Django 4.1.6 on 2023-02-17 20:25

import data_param.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0018_alter_cleanfunction_addl_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='addl_params',
            field=models.JSONField(default=data_param.models.default_params_data_type, verbose_name='Otras configuraciones'),
        ),
    ]
