# Generated by Django 4.1.6 on 2024-05-17 23:00

from django.db import migrations, models
import django.db.models.deletion


def create_datagroup(apps, schema_editor):
    OldDataGroup = apps.get_model('data_param', 'OldDataGroup')
    DataGroup = apps.get_model('data_param', 'DataGroup')
    for old_datagroup in OldDataGroup.objects.all():
        DataGroup.objects.create(
            name=old_datagroup.name,
            public_name=old_datagroup.public_name,
            is_default=old_datagroup.is_default,
            color=old_datagroup.color,
            order=old_datagroup.order
        )


def assign_datagroup(apps, schema_editor):
    Collection = apps.get_model('data_param', 'Collection')
    FileControl = apps.get_model('data_param', 'FileControl')
    ParameterGroup = apps.get_model('data_param', 'ParameterGroup')
    DataGroup = apps.get_model('data_param', 'DataGroup')
    for data_group in DataGroup.objects.all():
        Collection.objects.filter(data_group__name=data_group.name)\
            .update(new_data_group=data_group)
        FileControl.objects.filter(data_group__name=data_group.name)\
            .update(new_data_group=data_group)
        ParameterGroup.objects.filter(data_group__name=data_group.name)\
            .update(new_data_group=data_group)


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0019_remove_filecontrol_old_status_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataGroup',
            new_name='OldDataGroup',
        ),
        migrations.CreateModel(
            name='DataGroup',
            fields=[
                ('name',
                 models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombre (devs)')),
                ('public_name', models.CharField(max_length=80, verbose_name='Nombre público')),
                ('is_default', models.BooleanField(default=False)),
                ('color', models.CharField(default='lime', max_length=20)),
                ('order', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Grupo de datos solicitados',
                'verbose_name_plural': '1.1 Grupos de datos solicitados',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='new_data_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='data_param.datagroup', verbose_name='Conjunto de datos nuevo'),
        ),
        migrations.AddField(
            model_name='filecontrol',
            name='new_data_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='data_param.datagroup'),
        ),
        migrations.AddField(
            model_name='parametergroup',
            name='new_data_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='data_param.datagroup'),
        ),
        migrations.RunPython(create_datagroup, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(assign_datagroup, reverse_code=migrations.RunPython.noop),
    ]
