# Generated by Django 4.1.6 on 2023-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0019_remove_cleanfunction_id_alter_cleanfunction_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalfield',
            name='addl_params',
            field=models.JSONField(blank=True, help_text='Por ejemplo, max_length, null, blank, help_text, django_field, así como otras que aparezcan', null=True, verbose_name='Otras configuraciones'),
        ),
    ]
