# Generated by Django 4.1.6 on 2024-05-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0020_rename_datagroup_olddatagroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='data_group',
        ),
        migrations.RemoveField(
            model_name='filecontrol',
            name='data_group',
        ),
        migrations.RemoveField(
            model_name='parametergroup',
            name='data_group',
        ),
    ]
