# Generated by Django 4.1.6 on 2023-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0020_alter_finalfield_addl_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalfield',
            old_name='requiered',
            new_name='is_required',
        ),
        migrations.AddField(
            model_name='finalfield',
            name='is_unique',
            field=models.BooleanField(default=False, verbose_name='Puede ser una llave única'),
        ),
    ]
