# Generated by Django 4.1.6 on 2024-05-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0021_remove_collection_data_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='new_data_group',
            new_name='data_group',
        ),
        migrations.RenameField(
            model_name='filecontrol',
            old_name='new_data_group',
            new_name='data_group',
        ),
        migrations.RenameField(
            model_name='parametergroup',
            old_name='new_data_group',
            new_name='data_group',
        ),
    ]
