# Generated by Django 4.1.6 on 2024-07-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0022_rename_new_data_group_collection_data_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldDataGroup',
        ),
    ]
