# Generated by Django 4.1.6 on 2023-03-02 06:35

import data_param.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0001_initial'),
        ('data_param', '0022_alter_finalfield_is_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_function', models.IntegerField(blank=True, null=True)),
                ('file_control', models.IntegerField(blank=True, null=True)),
                ('name_column', models.IntegerField(blank=True, null=True)),
                ('addl_params', models.JSONField(blank=True, default=data_param.models.default_params, null=True)),
            ],
            options={
                'verbose_name': 'Transformación a aplicar',
                'verbose_name_plural': 'Transformaciones a aplicar',
                'db_table': 'inai_transformation',
            },
        ),
        migrations.CreateModel(
            name='FileControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_group', models.IntegerField()),
                ('format_file', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('word', 'Word'), ('xls', 'Excel'), ('txt', 'Texto'), ('csv', 'CSV'), ('email', 'Correo electrónico'), ('other', 'Otro')], max_length=5, null=True)),
                ('file_format', models.IntegerField(blank=True, null=True)),
                ('other_format', models.CharField(blank=True, max_length=80, null=True)),
                ('final_data', models.BooleanField(blank=True, null=True, verbose_name='Es información final')),
                ('notes', models.TextField(blank=True, null=True)),
                ('row_start_data', models.IntegerField(blank=True, default=1, null=True, verbose_name='# de fila donde inician los datos')),
                ('row_headers', models.IntegerField(blank=True, null=True, verbose_name='# de fila donde se encuentran los encabezados')),
                ('in_percent', models.BooleanField(default=False)),
                ('addl_params', models.JSONField(default=data_param.models.default_addl_params)),
                ('delimiter', models.CharField(blank=True, max_length=3, null=True, verbose_name='Delimitador de columnas')),
                ('decode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Codificación')),
                ('status_register', models.IntegerField(blank=True, null=True)),
                ('all_results', models.JSONField(blank=True, null=True)),
                ('anomalies', models.ManyToManyField(blank=True, to='transparency.anomaly', verbose_name='Anomalías de los datos')),
            ],
            options={
                'verbose_name': 'Grupo de control de archivos',
                'verbose_name_plural': 'Grupos de control de archivos',
                'db_table': 'inai_file_control',
            },
        ),
    ]
