# Generated by Django 4.1.6 on 2024-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0023_delete_olddatagroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecolumn',
            name='destination',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Hoja Destino'),
        ),
    ]
