# Generated by Django 4.1.6 on 2023-03-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0023_transformation_filecontrol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filecontrol',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transformation',
            table=None,
        ),
        migrations.CreateModel(
            name='NameColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_data', models.TextField(blank=True, null=True, verbose_name='Nombre de la columna real')),
                ('position_in_data', models.IntegerField(blank=True, null=True, verbose_name='idx')),
                ('column_type', models.IntegerField(blank=True, null=True)),
                ('file_control', models.IntegerField(blank=True, null=True)),
                ('data_type', models.IntegerField(blank=True, null=True)),
                ('collection', models.IntegerField(blank=True, null=True)),
                ('final_field', models.IntegerField(blank=True, null=True)),
                ('clean_params', models.JSONField(blank=True, null=True, verbose_name='Parámetros de limpieza')),
                ('requiered_row', models.BooleanField(default=False)),
                ('seq', models.IntegerField(blank=True, help_text='Número consecutivo para ordenación en dashboard', null=True, verbose_name='order')),
                ('children_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='data_param.namecolumn', verbose_name='Hijo resultado (junto a otras columnas)')),
                ('parent_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='data_param.namecolumn', verbose_name='Columna padre de la que derivó')),
            ],
            options={
                'verbose_name': 'Nombre de Columna',
                'verbose_name_plural': 'Nombres de Columnas',
                'ordering': ['seq'],
                'db_table': 'inai_name_column',
            },
        ),
    ]
