# Generated by Django 4.1.6 on 2023-03-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0030_alter_fileformat_addl_params_and_more'),
        ('data_param', '0024_alter_filecontrol_table_alter_transformation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontrol',
            name='data_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_param.datagroup'),
        ),
        migrations.AlterField(
            model_name='filecontrol',
            name='file_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.fileformat', verbose_name='formato del archivo'),
        ),
        migrations.AlterField(
            model_name='filecontrol',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol', verbose_name='Status de los registro de variables'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.collection'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='column_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.columntype'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.datatype'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='data_param.filecontrol'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='final_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_columns', to='data_param.finalfield'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='clean_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_param.cleanfunction', verbose_name='Función de limpieza o transformación'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_transformations', to='data_param.filecontrol', verbose_name='Grupo de control'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='name_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_transformations', to='data_param.namecolumn', verbose_name='Columna'),
        ),
    ]
