# Generated by Django 4.1.6 on 2023-03-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0025_alter_filecontrol_data_group_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filecontrol',
            table='data_param_filecontrol',
        ),
        migrations.AlterModelTable(
            name='namecolumn',
            table='data_param_namecolumn',
        ),
        migrations.AlterModelTable(
            name='transformation',
            table='data_param_transformation',
        ),
    ]
