# Generated by Django 4.1.6 on 2023-03-02 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_delegation_clues'),
        ('data_param', '0026_alter_filecontrol_table_alter_namecolumn_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontrol',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.entity', verbose_name='Entidad'),
        ),
    ]
