# Generated by Django 4.1.6 on 2023-03-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0027_filecontrol_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='order',
            field=models.IntegerField(default=5),
        ),
    ]
