# Generated by Django 4.1.6 on 2023-03-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0028_datagroup_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datagroup',
            options={'ordering': ['order'], 'verbose_name': 'Grupo de datos solicitados', 'verbose_name_plural': 'Grupos de datos solicitados'},
        ),
    ]
