# Generated by Django 4.1.6 on 2023-03-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0029_alter_datagroup_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namecolumn',
            old_name='requiered_row',
            new_name='required_row',
        ),
        migrations.RemoveField(
            model_name='namecolumn',
            name='clean_params',
        ),
        migrations.RemoveField(
            model_name='namecolumn',
            name='collection',
        ),
        migrations.AddField(
            model_name='namecolumn',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
