# Generated by Django 4.1.6 on 2023-03-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_remove_area_id_area_delegation_area_uuid'),
        ('data_param', '0030_rename_requiered_row_namecolumn_required_row_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dictionary_files')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_param.collection')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.entity')),
                ('final_fields', models.ManyToManyField(blank=True, related_name='m2m_dictionary_files', to='data_param.finalfield', verbose_name='Campos finales')),
                ('unique_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_files', to='data_param.finalfield')),
            ],
            options={
                'verbose_name': 'Catálogo para match',
                'verbose_name_plural': 'Catálogos para match',
            },
        ),
    ]
