# Generated by Django 4.1.6 on 2023-03-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0031_dictionaryfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfield',
            name='regex_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
