# Generated by Django 4.1.6 on 2023-03-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0032_finalfield_regex_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryfile',
            name='file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.filecontrol'),
        ),
        migrations.AddField(
            model_name='dictionaryfile',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
