# Generated by Django 4.1.6 on 2023-03-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0033_dictionaryfile_file_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfield',
            name='included',
            field=models.BooleanField(blank=True, null=True, verbose_name='valid'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Común'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='need_for_viz',
            field=models.BooleanField(default=False, help_text='Se utiliza en indicadores de transparencia', verbose_name='Data viz'),
        ),
    ]
