# Generated by Django 4.1.6 on 2023-04-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0037_remove_area_state_area_delegation'),
        ('data_param', '0034_finalfield_included_alter_finalfield_is_common_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namecolumn',
            old_name='children_column',
            new_name='child_column',
        ),
        migrations.RemoveField(
            model_name='dictionaryfile',
            name='entity',
        ),
        migrations.AddField(
            model_name='dictionaryfile',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation'),
        ),
        migrations.AddField(
            model_name='dictionaryfile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.institution'),
        ),
    ]
