# Generated by Django 4.1.6 on 2023-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0035_rename_children_column_namecolumn_child_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalfield',
            name='for_matching',
            field=models.BooleanField(default=False, verbose_name='match'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='included',
            field=models.BooleanField(blank=True, help_text='¿La inserción lo incluye?', null=True, verbose_name='valid'),
        ),
    ]
