# Generated by Django 4.1.6 on 2023-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0036_finalfield_for_matching_alter_finalfield_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalfield',
            name='for_matching',
        ),
        migrations.AddField(
            model_name='collection',
            name='cat_params',
            field=models.JSONField(default=dict, verbose_name='Parámetros para catálogo'),
        ),
        migrations.AddField(
            model_name='collection',
            name='open_insertion',
            field=models.BooleanField(default=False, verbose_name='Permitir inserción de datos'),
        ),
        migrations.AddField(
            model_name='finalfield',
            name='match_use',
            field=models.CharField(blank=True, choices=[('as_unique', 'Como único'), ('in_list', 'En la lista'), ('alternatives', 'Nombres alternativos')], help_text='Uso en el match con catálogos', max_length=16, null=True),
        ),
    ]
