# Generated by Django 4.1.6 on 2023-04-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0037_remove_finalfield_for_matching_collection_cat_params_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filecontrol',
            old_name='entity',
            new_name='agency',
        ),
    ]
