# Generated by Django 4.1.6 on 2023-04-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0032_remove_filetype_id_alter_filetype_name'),
        ('data_param', '0038_rename_entity_filecontrol_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['data_group', 'name'], 'verbose_name': 'Modelo (Tabla)', 'verbose_name_plural': 'Modelos o Tablas'},
        ),
        migrations.AddField(
            model_name='namecolumn',
            name='alternative_names',
            field=models.JSONField(blank=True, null=True, verbose_name='Nombres alternativos'),
        ),
        migrations.AlterField(
            model_name='cleanfunction',
            name='column_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clean_functions', to='category.columntype', verbose_name='Tipo de columna'),
        ),
    ]
