# Generated by Django 4.1.6 on 2023-04-10 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0043_remove_clues_jurisdiction_obj_clues_delegation_and_more'),
        ('data_param', '0039_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanfunction',
            options={'ordering': ['priority', 'public_name'], 'verbose_name': 'Función de limpieza y transformación', 'verbose_name_plural': '2.CAT. Funciones de limpieza y transformación'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['data_group', 'name'], 'verbose_name': 'Modelo (Tabla)', 'verbose_name_plural': '1.3 Modelos o Tablas'},
        ),
        migrations.AlterModelOptions(
            name='datagroup',
            options={'ordering': ['order'], 'verbose_name': 'Grupo de datos solicitados', 'verbose_name_plural': '1.1 Grupos de datos solicitados'},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'Tipo de dato', 'verbose_name_plural': '2.CAT. Tipos de datos'},
        ),
        migrations.AlterModelOptions(
            name='dictionaryfile',
            options={'verbose_name': 'Catálogo para match', 'verbose_name_plural': '4.2 Diccionarios para match'},
        ),
        migrations.AlterModelOptions(
            name='filecontrol',
            options={'verbose_name': 'Grupo de control de archivos', 'verbose_name_plural': '3.1 Grupos de control de archivos'},
        ),
        migrations.AlterModelOptions(
            name='finalfield',
            options={'ordering': ['parameter_group', '-is_common', 'verbose_name'], 'verbose_name': 'Campo final', 'verbose_name_plural': '1.4 Campos finales (en DB)'},
        ),
        migrations.AlterModelOptions(
            name='namecolumn',
            options={'ordering': ['seq'], 'verbose_name': 'Nombre de Columna', 'verbose_name_plural': '3.2 Nombres de Columnas'},
        ),
        migrations.AlterModelOptions(
            name='parametergroup',
            options={'verbose_name': 'Agrupación de campos finales', 'verbose_name_plural': '1.2 Agrupaciones de campos finales'},
        ),
        migrations.AlterModelOptions(
            name='transformation',
            options={'verbose_name': 'Transformación a aplicar', 'verbose_name_plural': '4.1 Transformaciones a aplicar'},
        ),
        migrations.AddField(
            model_name='dictionaryfile',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.entity'),
        ),
    ]
