# Generated by Django 4.1.6 on 2023-04-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0040_alter_cleanfunction_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryfile',
            name='delegation',
        ),
        migrations.RemoveField(
            model_name='dictionaryfile',
            name='institution',
        ),
    ]
