# Generated by Django 4.1.6 on 2023-04-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0041_remove_dictionaryfile_delegation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['data_group', 'name'], 'verbose_name': 'Modelo (Colección)', 'verbose_name_plural': '1.3 Modelos (Colecciones)'},
        ),
        migrations.AddField(
            model_name='collection',
            name='app_label',
            field=models.CharField(default='null', max_length=225, verbose_name='App'),
        ),
    ]
