# Generated by Django 4.1.6 on 2023-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0042_alter_collection_options_collection_app_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='app_label',
            field=models.CharField(default='null', max_length=40, verbose_name='App label'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='open_insertion',
            field=models.BooleanField(default=False, verbose_name='Permitir inserción'),
        ),
    ]
