# Generated by Django 4.1.6 on 2023-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0043_alter_collection_app_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalfield',
            name='included',
        ),
        migrations.AddField(
            model_name='finalfield',
            name='included_code',
            field=models.CharField(choices=[('complete', 'Completo'), ('complement', 'Complementario'), ('wait', 'En espera de inclusión; pausar'), ('invalid', 'No válido, debe revisarse')], default='complement', max_length=12, verbose_name='included'),
        ),
    ]
