# Generated by Django 4.1.6 on 2023-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0044_remove_finalfield_included_finalfield_included_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalfield',
            options={'ordering': ['parameter_group', '-is_common', 'verbose_name'], 'verbose_name': 'Campo final', 'verbose_name_plural': '1.4 Campos finales (DB)'},
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='included_code',
            field=models.CharField(choices=[('complete', 'Completo'), ('complement', 'Complementario'), ('wait', 'En espera de inclusión; pausar'), ('invalid', 'No válido, debe revisarse')], default='complement', max_length=12, verbose_name='valid'),
        ),
    ]
