# Generated by Django 4.1.6 on 2023-09-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0011_alter_entity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDrug',
            fields=[
                ('key', models.CharField(db_column='key', max_length=255, primary_key=True, serialize=False)),
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total')),
            ],
            options={
                'verbose_name': 'Tabla Madre. Drugs',
                'verbose_name_plural': 'Tabla Madre. Drugs',
                'db_table': 'mother_drug',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotherDrugExtended',
            fields=[
                ('iso_year', models.PositiveSmallIntegerField(db_column='iso_year')),
                ('iso_week', models.PositiveSmallIntegerField(db_column='iso_week')),
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Dato Extendido',
                'verbose_name_plural': 'Datos Extendidos',
                'db_table': 'mother_drug_extended',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotherDrugLosartan',
            fields=[
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='geo.entity')),
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total')),
            ],
            options={
                'verbose_name': 'Dato Losartan',
                'verbose_name_plural': 'Datos Losartan',
                'db_table': 'mother_drug_losartan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotherDrugPriority',
            fields=[
                ('key', models.CharField(db_column='key', max_length=255, primary_key=True, serialize=False)),
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total')),
            ],
            options={
                'verbose_name': 'Dato Prioridad',
                'verbose_name_plural': 'Datos Prioridad',
                'db_table': 'mother_drug_priority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotherDrugTotals',
            fields=[
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Dato Total',
                'verbose_name_plural': 'Datos Totales',
                'db_table': 'mother_drug_totals',
                'managed': False,
            },
        ),
    ]
