# Generated by Django 4.1.6 on 2023-10-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motherdruglosartan',
            options={'verbose_name': 'Dato Losartan', 'verbose_name_plural': 'Datos Losartan'},
        ),
    ]
