# Generated by Django 4.1.6 on 2023-10-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0002_alter_motherdruglosartan_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotherDrugLosartan',
        ),
    ]
