# Generated by Django 4.1.6 on 2024-03-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0003_delete_motherdruglosartan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotherDrugExtended',
        ),
    ]
