# Generated by Django 4.1.6 on 2024-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0004_delete_motherdrugextended'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDrugEntity',
            fields=[
                ('iso_year', models.PositiveSmallIntegerField(db_column='iso_year', primary_key=True, serialize=False)),
                ('iso_week', models.PositiveSmallIntegerField(db_column='iso_week')),
                ('year', models.PositiveSmallIntegerField(db_column='year')),
                ('month', models.PositiveSmallIntegerField(db_column='month')),
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total')),
            ],
            options={
                'verbose_name': 'Entidad de Medicamentos',
                'verbose_name_plural': 'Entidades de Medicamentos',
                'db_table': 'mat_drug_entity',
                'managed': False,
            },
        ),
    ]
