# Generated by Django 2.2.25 on 2022-03-09 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de medicina')),
                ('medication_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de medicamento / Insumo faltante')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='Entidad')),
                ('institution', models.IntegerField(blank=True, null=True, verbose_name='Institución')),
                ('institution_raw', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución escrita')),
                ('clues', models.IntegerField(blank=True, null=True)),
                ('is_other', models.BooleanField(default=False, verbose_name='Es otra institución')),
                ('hospital_name_raw', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de hospital o clínica')),
                ('has_corruption', models.BooleanField(verbose_name='¿Incluyó corrupción?')),
                ('narration', models.TextField(blank=True, null=True, verbose_name='Relato de la corrupción')),
                ('informer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('email', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo de contacto')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de contacto')),
                ('informer_type', models.CharField(choices=[('paciente', 'Paciente'), ('profesional', 'Profesional')], max_length=20, verbose_name='Tipo de Informante')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('origin_app', models.CharField(default='CD2', max_length=100, verbose_name='Aplicacion')),
                ('disease_raw', models.TextField(blank=True, null=True, verbose_name='Padecimiento')),
                ('validated', models.BooleanField(default=None)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('want_litigation', models.BooleanField(verbose_name='¿Permite contacto para litigio?')),
                ('validator', models.IntegerField(blank=True, null=True)),
                ('validated_date', models.DateTimeField(blank=True, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('public_testimony', models.BooleanField()),
                ('sent_email', models.BooleanField()),
                ('sent_responsible', models.BooleanField()),
                ('session_ga', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'desabasto_report',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('emails', models.CharField(max_length=255, verbose_name='Correos electronicos')),
                ('responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='responsible')),
                ('position', models.CharField(max_length=255, verbose_name='Cargo o posición')),
                ('institution', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('clues', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'db_table': 'desabasto_responsable',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField()),
                ('component', models.IntegerField(blank=True, null=True)),
                ('presentation', models.IntegerField(blank=True, null=True)),
                ('medicine_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Medicamento')),
                ('medicine_name_raw', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre reportado del medicamento')),
                ('presentation_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_real_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre real del medicamento')),
                ('disease', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suministro Medico',
                'verbose_name_plural': 'Suministros Medicos',
                'db_table': 'desabasto_supply',
            },
        ),
        migrations.CreateModel(
            name='TestimonyMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='cero_desabasto')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Archivo de testimonio',
                'verbose_name_plural': 'Archivos de testimonio',
                'db_table': 'desabasto_testimonymedia',
            },
        ),
    ]
