# Generated by Django 4.1.6 on 2023-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Medicamento o insumo', 'verbose_name_plural': '2. Medicamentos/Supplys de reportes'},
        ),
        migrations.AlterField(
            model_name='report',
            name='medication_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de medicamento / Supply faltante'),
        ),
    ]
