# Generated by Django 2.2.25 on 2022-03-10 04:40

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20220309_2240'),
        ('report', '0002_auto_20220308_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('email', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo de contacto')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de contacto')),
                ('informer_type', models.CharField(choices=[('paciente', 'Paciente'), ('profesional', 'Profesional'), ('vacuna', 'Vacuna')], max_length=20, verbose_name='Tipo de Informante')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('gender', models.CharField(blank=True, max_length=40, null=True, verbose_name='Género')),
                ('special_group', models.CharField(blank=True, max_length=80, null=True, verbose_name='Grupo especial')),
                ('comorbilities', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Comorbilidades')),
            ],
            options={
                'verbose_name': 'Persona Reportante',
                'verbose_name_plural': 'Personas Reportantes',
            },
        ),
        migrations.CreateModel(
            name='ReportCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_corruption', models.BooleanField(verbose_name='¿Incluyó corrupción?')),
                ('narration', models.TextField(blank=True, null=True, verbose_name='Relato de la corrupción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('origin_app', models.CharField(default='CD2', max_length=100, verbose_name='Aplicación')),
                ('validated', models.BooleanField(default=None)),
                ('validator', models.IntegerField(blank=True, null=True)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('validated_date', models.DateTimeField(blank=True, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('sent_email', models.BooleanField()),
                ('session_ga', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Municipality', verbose_name='Municipio residencia')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Persona', verbose_name='Persona reportante')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.State', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Reporte COVID',
                'verbose_name_plural': 'Reportes COVID',
            },
        ),
        migrations.CreateModel(
            name='DosisCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField(default=False, verbose_name='Es dosis aplicada')),
                ('other_location', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('round_dosis', models.CharField(blank=True, max_length=60, null=True, verbose_name='Número de dosis')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('reason_negative', models.TextField(blank=True, null=True, verbose_name='Razón de negativa')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Municipality', verbose_name='Municipio')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.State', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Dosis',
                'verbose_name_plural': 'Dosis aplicadas y negadas',
            },
        ),
    ]
