# Generated by Django 2.2.25 on 2022-03-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20220309_2240'),
        ('report', '0003_dosiscovid_persona_reportcovid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportCovid',
            new_name='CovidReport',
        ),
        migrations.AddField(
            model_name='dosiscovid',
            name='covid_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.CovidReport', verbose_name='Reporte Covid'),
        ),
    ]
