# Generated by Django 2.2.25 on 2022-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20220310_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidreport',
            name='other_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
