# Generated by Django 2.2.25 on 2022-03-14 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_covidreport_other_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosiscovid',
            name='covid_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosis', to='report.CovidReport', verbose_name='Reporte Covid'),
        ),
        migrations.AlterField(
            model_name='dosiscovid',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='informer_type',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('profesional', 'Profesional'), ('vacuna_covid', 'Vacuna')], max_length=20, verbose_name='Tipo de Informante'),
        ),
    ]
