# Generated by Django 2.2.25 on 2022-03-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20220319_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementreport',
            name='covid_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complement', to='report.CovidReport'),
        ),
        migrations.AlterField(
            model_name='complementreport',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complement', to='report.Report'),
        ),
    ]
