# Generated by Django 2.2.25 on 2022-03-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20220319_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidreport',
            name='has_corruption',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='origin_app',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='sent_email',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='session_ga',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='testimony',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='validated_date',
        ),
        migrations.RemoveField(
            model_name='covidreport',
            name='validator',
        ),
    ]
