# Generated by Django 2.2.25 on 2022-03-19 21:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20220319_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='age',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='comorbilities',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='informer_type',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='special_group',
        ),
        migrations.AddField(
            model_name='covidreport',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='covidreport',
            name='comorbilities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Comorbilidades'),
        ),
        migrations.AddField(
            model_name='covidreport',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='covidreport',
            name='special_group',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Grupo especial'),
        ),
    ]
