# Generated by Django 2.2.25 on 2022-03-19 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20220319_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Persona', verbose_name='Persona reportante'),
        ),
    ]
