# Generated by Django 2.2.25 on 2022-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_report_persona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complementreport',
            options={'verbose_name': 'Complemento de un reporte', 'verbose_name_plural': 'Complementos de reportes'},
        ),
        migrations.AddField(
            model_name='responsable',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='complementreport',
            name='key',
            field=models.CharField(default='', max_length=30),
        ),
    ]
