# Generated by Django 2.2.25 on 2022-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20220323_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='responsible',
        ),
        migrations.AlterField(
            model_name='responsable',
            name='emails',
            field=models.CharField(help_text='Pueden agregarse varios, separar por comas', max_length=255, verbose_name='Correos electronicos'),
        ),
    ]
