# Generated by Django 2.2.25 on 2022-03-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20220323_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='want_litigation',
            field=models.NullBooleanField(verbose_name='¿Permite contacto para asesoría legal?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='want_management',
            field=models.NullBooleanField(verbose_name='¿Permite contacto para acompañar proceso?'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='clues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='catalog.CLUES', verbose_name='Clínica u Hospital'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='catalog.Institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='catalog.State', verbose_name='Entidad'),
        ),
    ]
