# Generated by Django 2.2.25 on 2022-03-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20220323_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='disease',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
