# Generated by Django 2.2.25 on 2022-03-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20220323_1508'),
    ]

    operations = [
    ]
