# Generated by Django 2.2.25 on 2022-04-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20220323_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='is_covid',
            field=models.BooleanField(default=False, verbose_name='Responsable COVID'),
        ),
    ]
