# Generated by Django 2.2.25 on 2022-06-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_responsable_is_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementreport',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas (para corrección)'),
        ),
    ]
