# Generated by Django 2.2.25 on 2022-08-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_complementreport_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='petition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha respuesta oficio'),
        ),
    ]
