# Generated by Django 2.2.25 on 2022-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_responsable_petition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Género'),
        ),
    ]
