# Generated by Django 4.1.5 on 2023-01-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_report_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementreport',
            name='public_testimony',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complementreport',
            name='validated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='covidreport',
            name='comorbilities',
            field=models.JSONField(blank=True, null=True, verbose_name='Comorbilidades'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='want_litigation',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Permite contacto para asesoría legal?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='want_management',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Permite contacto para acompañar proceso?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='has_corruption',
            field=models.BooleanField(null=True, verbose_name='¿Incluyó corrupción?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_testimony',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sent_email',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sent_responsible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='validated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='want_litigation',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Permite contacto para litigio?'),
        ),
    ]
