# Generated by Django 4.1.5 on 2023-01-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_alter_report_has_corruption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementreport',
            name='has_corruption',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Incluyó corrupción?'),
        ),
    ]
