# Generated by Django 2.2.25 on 2022-07-26 19:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Columna',
                'verbose_name_plural': 'Tipos de columnas',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('has_data', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.CreateModel(
            name='NegativeReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Razón de negación de datos',
                'verbose_name_plural': 'Razones de negación de datos',
            },
        ),
        migrations.CreateModel(
            name='StatusControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('petition', 'Proceso de Solicitud'), ('data', 'Datos de la Solicitud'), ('process', 'Procesamiento de archivos (solo devs)'), ('register', 'Registro de variables (solo devs)')], default='petition', max_length=10, verbose_name='grupo de status')),
                ('name', models.CharField(max_length=120)),
                ('public_name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('addl_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status de control',
                'verbose_name_plural': 'Status de control (TODOS)',
            },
        ),
    ]
