# Generated by Django 2.2.25 on 2022-07-29 17:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('public_name', models.CharField(max_length=120)),
                ('order', models.IntegerField(default=5)),
                ('break_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fecha de corte',
                'verbose_name_plural': 'Fechas de corte',
            },
        ),
    ]
