# Generated by Django 4.1.6 on 2024-11-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebreak',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('provider', 'para Proveedores'), ('priority', 'Prioridad en Solicitudes'), ('medicament', 'Medicamentos')], default='petition', max_length=10, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('provider', 'para Proveedores'), ('priority', 'Prioridad en Solicitudes'), ('medicament', 'Medicamentos')], default='petition', max_length=10, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='oldstatuscontrol',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('provider', 'para Proveedores'), ('priority', 'Prioridad en Solicitudes'), ('medicament', 'Medicamentos')], default='petition', max_length=10, verbose_name='grupo de status'),
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('provider', 'para Proveedores'), ('priority', 'Prioridad en Solicitudes'), ('medicament', 'Medicamentos')], max_length=10, verbose_name='grupo de status'),
        ),
    ]
