# Generated by Django 2.2.25 on 2022-07-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_datebreak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datebreak',
            options={'ordering': ['order'], 'verbose_name': 'Fecha de corte', 'verbose_name_plural': 'Fechas de corte'},
        ),
        migrations.AlterModelOptions(
            name='filetype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documentos'},
        ),
        migrations.AlterModelOptions(
            name='statuscontrol',
            options={'ordering': ['order'], 'verbose_name': 'Status de control', 'verbose_name_plural': 'Status de control (TODOS)'},
        ),
        migrations.AddField(
            model_name='statuscontrol',
            name='order',
            field=models.IntegerField(default=4),
        ),
    ]
