# Generated by Django 4.1.6 on 2024-03-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_statuscontrol_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileformat',
            options={'ordering': ['order'], 'verbose_name': 'Formato de archivos', 'verbose_name_plural': 'Formatos de archivos'},
        ),
    ]
