# Generated by Django 4.1.6 on 2024-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_fileformat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidreason',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
