# Generated by Django 4.1.6 on 2024-04-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_invalidreason_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativereason',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
