# Generated by Django 2.2.25 on 2022-08-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_filetype_addl_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='datebreak',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('process', 'Procesamiento de archivos (solo devs)'), ('register', 'Registro de variables (solo devs)')], default='petition', max_length=10, verbose_name='grupo'),
        ),
        migrations.AddField(
            model_name='filetype',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='filetype',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('process', 'Procesamiento de archivos (solo devs)'), ('register', 'Registro de variables (solo devs)')], default='petition', max_length=10, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('process', 'Procesamiento de archivos (solo devs)'), ('register', 'Registro de variables (solo devs)')], default='petition', max_length=10, verbose_name='grupo de status'),
        ),
    ]
