# Generated by Django 4.1.6 on 2024-04-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_negativereason_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invalidreason',
            options={'ordering': ['order'], 'verbose_name': 'Razón de invalidez de datos', 'verbose_name_plural': 'Razones de invalidez de datos'},
        ),
        migrations.AlterModelOptions(
            name='negativereason',
            options={'ordering': ['order'], 'verbose_name': 'Razón de negación de datos', 'verbose_name_plural': 'Razones de negación de datos'},
        ),
    ]
