# Generated by Django 2.2.25 on 2022-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20220731_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='public_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
