# Generated by Django 2.2.25 on 2022-08-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_filetype_public_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuscontrol',
            options={'ordering': ['group', 'order'], 'verbose_name': 'Status de control', 'verbose_name_plural': 'Status de control (TODOS)'},
        ),
    ]
