# Generated by Django 2.2.25 on 2022-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20220802_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre Corto')),
                ('is_public', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(default=5)),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Anomalía en los datos',
                'verbose_name_plural': 'Anomalías en los datos',
            },
        ),
        migrations.AlterModelOptions(
            name='filetype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de archivo', 'verbose_name_plural': 'Tipos de archivos'},
        ),
    ]
