# Generated by Django 2.2.25 on 2022-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20220811_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Nombre (devs)'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='public_name',
            field=models.CharField(max_length=255, verbose_name='Nombre público'),
        ),
    ]
