# Generated by Django 4.1.6 on 2024-05-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0016_alter_cleanfunction_ready_code'),
        ('respond', '0006_alter_datafile_is_duplicated'),
        ('task', '0020_rename_entity_month_asynctask_month_record_and_more'),
        ('inai', '0080_petition_status_priority'),
        ('geo', '0019_alter_provider_options_provider_variables'),
        ('category', '0008_alter_datebreak_group_alter_filetype_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusControl',
            new_name='OldStatusControl',
        ),
    ]
