# Generated by Django 4.1.6 on 2024-05-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_rename_statuscontrol_oldstatuscontrol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oldstatuscontrol',
            table='category_oldstatuscontrol',
        ),
    ]
