# Generated by Django 2.2.25 on 2022-08-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20220811_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columntype',
            options={'ordering': ['order'], 'verbose_name': 'Tipo de Columna', 'verbose_name_plural': 'Tipos de columnas'},
        ),
        migrations.AddField(
            model_name='columntype',
            name='order',
            field=models.IntegerField(default=5),
        ),
    ]
