# Generated by Django 2.2.25 on 2022-08-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20220822_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
