# Generated by Django 2.2.25 on 2022-08-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_anomaly_is_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='color',
            field=models.CharField(blank=True, help_text='https://vuetifyjs.com/en/styles/colors/', max_length=20, null=True),
        ),
    ]
