# Generated by Django 2.2.25 on 2022-09-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20220831_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Razón de invalidez de datos',
                'verbose_name_plural': 'Razones de invalidez de datos',
            },
        ),
    ]
