# Generated by Django 4.1.6 on 2024-05-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_invalidreason_is_official_alter_statuscontrol_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebreak',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('provider', 'para Proveedores'), ('priority', 'Prioridad en Solicitudes')], default='petition', max_length=10, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('provider', 'para Proveedores'), ('priority', 'Prioridad en Solicitudes')], default='petition', max_length=10, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='oldstatuscontrol',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('provider', 'para Proveedores'), ('priority', 'Prioridad en Solicitudes')], default='petition', max_length=10, verbose_name='grupo de status'),
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('provider', 'para Proveedores'), ('priority', 'Prioridad en Solicitudes')], max_length=10, verbose_name='grupo de status'),
        ),
    ]
