# Generated by Django 2.2.25 on 2022-09-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_invalidreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscontrol',
            name='color',
            field=models.CharField(blank=True, help_text='https://vuetifyjs.com/en/styles/colors/', max_length=30, null=True),
        ),
    ]
