# Generated by Django 4.1.6 on 2024-05-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_alter_datebreak_group_alter_filetype_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuscontrol',
            options={'ordering': ['group', 'order'], 'verbose_name': '1. Status de control', 'verbose_name_plural': '1. Status de control'},
        ),
    ]
