# Generated by Django 2.2.25 on 2022-10-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_fileformat_transparencyindex_transparencylevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileformat',
            options={'verbose_name': 'Formato de archivos', 'verbose_name_plural': 'Formatos de archivos'},
        ),
        migrations.AlterModelOptions(
            name='transparencyindex',
            options={'verbose_name': 'Transparencia: Indicador', 'verbose_name_plural': 'Transparencia: Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='transparencylevel',
            options={'verbose_name': 'Transparencia: Nivel', 'verbose_name_plural': 'Transparencia: Niveles'},
        ),
        migrations.RemoveField(
            model_name='fileformat',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='fileformat',
            name='has_data',
        ),
        migrations.RemoveField(
            model_name='fileformat',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='fileformat',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='fileformat',
            name='name',
        ),
    ]
