# Generated by Django 2.2.25 on 2022-10-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_auto_20221024_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileformat',
            name='order',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
