# Generated by Django 2.2.25 on 2022-10-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_fileformat_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transparencylevel',
            name='transparency_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='category.TransparencyIndex', verbose_name='Indicador de Transparencia'),
        ),
    ]
