# Generated by Django 2.2.25 on 2022-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_auto_20221026_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencylevel',
            name='order_viz',
            field=models.IntegerField(default=-3, verbose_name='Orden en visualización'),
        ),
        migrations.AddField(
            model_name='transparencylevel',
            name='value_ctrls',
            field=models.IntegerField(default=-3, verbose_name='Priorización entre controles'),
        ),
        migrations.AddField(
            model_name='transparencylevel',
            name='value_pets',
            field=models.IntegerField(default=-3, verbose_name='Priorización entre solicitudes'),
        ),
    ]
