# Generated by Django 2.2.25 on 2022-10-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0019_auto_20221026_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencylevel',
            options={'ordering': ['order_viz'], 'verbose_name': 'Transparencia: Nivel', 'verbose_name_plural': 'Transparencia: Niveles'},
        ),
    ]
