# Generated by Django 2.2.25 on 2022-10-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_auto_20221027_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencyindex',
            name='order_viz',
            field=models.IntegerField(default=-3, verbose_name='Orden en visualización'),
        ),
    ]
