# Generated by Django 2.2.25 on 2022-11-16 01:53

import category.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

import transparency.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0021_transparencyindex_order_viz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencyindex',
            options={'ordering': ['order_viz'], 'verbose_name': 'Transparencia: Indicador', 'verbose_name_plural': 'Transparencia: Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='transparencylevel',
            options={'ordering': ['transparency_index__order_viz', '-order_viz'], 'verbose_name': 'Transparencia: Nivel', 'verbose_name_plural': 'Transparencia: Niveles'},
        ),
        migrations.AddField(
            model_name='transparencylevel',
            name='viz_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=transparency.models.default_dict),
        ),
        migrations.AlterField(
            model_name='transparencylevel',
            name='final_level',
            field=models.ForeignKey(blank=True, help_text='Si existe, se va a ese nivel de indicador principal', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.TransparencyLevel', verbose_name='Concentrado destino'),
        ),
    ]
