# Generated by Django 2.2.25 on 2022-12-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_auto_20221115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencylevel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
