# Generated by Django 4.1.5 on 2023-01-22 07:41

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0023_transparencylevel_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebreak',
            name='break_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='addl_params',
            field=models.JSONField(blank=True, default=category.models.default_dict),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='suffixes',
            field=models.JSONField(blank=True, default=category.models.default_list, null=True, verbose_name='extensiones'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='addl_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='addl_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transparencyindex',
            name='viz_params',
            field=models.JSONField(blank=True, default=category.models.default_dict),
        ),
        migrations.AlterField(
            model_name='transparencylevel',
            name='other_conditions',
            field=models.JSONField(blank=True, default=category.models.default_list),
        ),
        migrations.AlterField(
            model_name='transparencylevel',
            name='viz_params',
            field=models.JSONField(blank=True, default=category.models.default_dict),
        ),
    ]
