# Generated by Django 4.1.6 on 2023-02-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0025_statustask'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
