# Generated by Django 4.1.6 on 2023-02-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0045_delete_asynctask'),
        ('category', '0026_statustask_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusTask',
        ),
    ]
