# Generated by Django 4.1.6 on 2023-03-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0027_delete_statustask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencylevel',
            options={'verbose_name': 'Transparencia: Nivel', 'verbose_name_plural': 'Transparencia: Niveles'},
        ),
        migrations.AlterField(
            model_name='transparencylevel',
            name='transparency_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
