# Generated by Django 4.1.6 on 2023-03-02 06:35

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0051_remove_filecontrol_anomalies_delete_transformation_and_more'),
        ('category', '0028_alter_transparencylevel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransparencyIndex',
        ),
        migrations.RemoveField(
            model_name='transparencylevel',
            name='anomalies',
        ),
        migrations.RemoveField(
            model_name='transparencylevel',
            name='file_formats',
        ),
        migrations.RemoveField(
            model_name='transparencylevel',
            name='final_level',
        ),
        # migrations.AlterField(
        #     model_name='fileformat',
        #     name='addl_params',
        #     field=models.JSONField(blank=True, default=category.models.default_dict),
        # ),
        # migrations.AlterField(
        #     model_name='fileformat',
        #     name='suffixes',
        #     field=models.JSONField(blank=True, default=category.models.default_list, null=True, verbose_name='extensiones'),
        # ),
        migrations.DeleteModel(
            name='Anomaly',
        ),
        migrations.DeleteModel(
            name='TransparencyLevel',
        ),
    ]
