# Generated by Django 4.1.6 on 2023-03-02 06:55

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0029_delete_transparencyindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileformat',
            name='addl_params',
            field=models.JSONField(blank=True, default=category.models.default_dict),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='suffixes',
            field=models.JSONField(blank=True, default=category.models.default_list, null=True, verbose_name='extensiones'),
        ),
    ]
