# Generated by Django 4.1.6 on 2023-03-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0030_alter_fileformat_addl_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebreak',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('process', 'Procesamiento de archivos (solo devs)')], default='petition', max_length=10, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('process', 'Procesamiento de archivos (solo devs)')], default='petition', max_length=10, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='group',
            field=models.CharField(choices=[('petition', 'de Solicitud'), ('data', 'Datos entregados'), ('complain', 'Quejas - Revisiones'), ('register', 'Registro de variables'), ('process', 'Procesamiento de archivos (solo devs)')], default='petition', max_length=10, verbose_name='grupo de status'),
        ),
    ]
