# Generated by Django 4.1.6 on 2023-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0031_alter_datebreak_group_alter_filetype_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetype',
            name='id',
        ),
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
