# Generated by Django 4.1.6 on 2023-03-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTask',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=5)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Status de tarea',
                'verbose_name_plural': '3. Status de tareas',
                'ordering': ['order'],
                # 'db_table': 'task_statustask',
            },
        ),
        migrations.CreateModel(
            name='TaskFunction',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('reply_file', 'ReplyFile (.zip)')], max_length=100, null=True)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('addl_params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Función (tarea)',
                'verbose_name_plural': '2. Funciones (tareas)',
                # 'db_table': 'task_taskfunction',
            },
        ),
    ]
