# Generated by Django 4.1.6 on 2023-03-07 04:40

from django.db import migrations, models
import django.db.models.deletion

# stages = ['initial', 'explore', 'counting', 'transform', 'insert']


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('public_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=5)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('next_text', models.TextField(blank=True, null=True, verbose_name='Texto para continuar')),
                ('massive_next_text', models.TextField(blank=True, null=True, verbose_name='Texto - continuar masivamente')),
                ('retry_text', models.TextField(blank=True, null=True, verbose_name='Texto para reintentar')),
                ('massive_retry_text', models.TextField(blank=True, null=True, verbose_name='Texto - reintentar masivamente')),
                ('next_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_functions', to='classify_task.taskfunction')),
                ('retry_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='try_functions', to='classify_task.taskfunction')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': '4. Etapas',
                'ordering': ['order'],
            },
        ),
    ]
