# Generated by Django 4.1.6 on 2023-03-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0002_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='color',
        ),
        migrations.AlterModelTable(
            name='statustask',
            table='classify_task_statustask',
        ),
        migrations.AlterModelTable(
            name='taskfunction',
            table='classify_task_taskfunction',
        ),
    ]
