# Generated by Django 4.1.6 on 2023-05-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0003_alter_taskfunction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfunction',
            name='is_queueable',
            field=models.BooleanField(default=False, verbose_name='queue'),
        ),
        migrations.AlterField(
            model_name='taskfunction',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='taskfunction',
            name='is_from_aws',
            field=models.BooleanField(default=False, verbose_name='AWS'),
        ),
    ]
