# Generated by Django 4.1.6 on 2023-03-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0003_remove_stage_color_alter_statustask_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='massive_next_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Texto - continuar masivamente'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='massive_retry_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Texto - reintentar masivamente'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='next_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Texto para continuar'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='retry_text',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Texto para reintentar'),
        ),
    ]
