# Generated by Django 4.1.6 on 2023-03-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0004_alter_stage_massive_next_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='retry_function',
            new_name='main_function',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='next_function',
        ),
        migrations.AddField(
            model_name='stage',
            name='next_stage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_stage', to='classify_task.stage'),
        ),
    ]
