# Generated by Django 4.1.6 on 2023-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfunction',
            name='group_queue',
            field=models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('reply_file', 'ReplyFile (.zip)'), ('sheet_file', 'Pestaña'), ('entity_week', 'Semana Proveedor'), ('entity_month', 'Mes Proveedor'), ('entity', 'Proveedor')], max_length=100, null=True, verbose_name='agrupables'),
        ),
        migrations.AddField(
            model_name='taskfunction',
            name='queue_size',
            field=models.IntegerField(default=1, verbose_name='queue size'),
        ),
        migrations.AddField(
            model_name='taskfunction',
            name='simultaneous_groups',
            field=models.IntegerField(default=1, verbose_name='Grupos simultáneos'),
        ),
    ]
