# Generated by Django 4.1.6 on 2023-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0006_alter_stage_main_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustask',
            name='macro_status',
            field=models.CharField(blank=True, default='in_progress', max_length=30, null=True),
        ),
    ]
