# Generated by Django 4.1.6 on 2023-08-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0006_taskfunction_group_queue_taskfunction_queue_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='field_last_edit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo de última edición'),
        ),
        migrations.AddField(
            model_name='taskfunction',
            name='lambda_function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
