# Generated by Django 4.1.6 on 2023-08-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0007_stage_field_last_edit_taskfunction_lambda_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='finished_function',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Función al terminar'),
        ),
    ]
