# Generated by Django 4.1.6 on 2023-03-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0007_statustask_macro_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfunction',
            options={'ordering': ['model_name', 'name'], 'verbose_name': 'Función (tarea)', 'verbose_name_plural': '2. Funciones (tareas)'},
        ),
        migrations.AlterField(
            model_name='stage',
            name='main_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='classify_task.taskfunction', verbose_name='Función principal'),
        ),
    ]
