# Generated by Django 4.1.6 on 2023-03-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0008_alter_taskfunction_options_alter_stage_main_function'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfunction',
            options={'ordering': ['is_active', 'model_name', 'is_from_aws', 'name'], 'verbose_name': 'Función (tarea)', 'verbose_name_plural': '2. Funciones (tareas)'},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='massive_next_text',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='massive_retry_text',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='next_text',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='retry_text',
        ),
        migrations.RemoveField(
            model_name='taskfunction',
            name='addl_params',
        ),
        migrations.RemoveField(
            model_name='taskfunction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskfunction',
            name='icon',
        ),
        migrations.AddField(
            model_name='stage',
            name='action_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='available_next_stages',
            field=models.ManyToManyField(blank=True, related_name='previous_stages', to='classify_task.stage'),
        ),
        migrations.AddField(
            model_name='taskfunction',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskfunction',
            name='is_from_aws',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='taskfunction',
            table=None,
        ),
    ]
