# Generated by Django 4.1.6 on 2023-08-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0008_stage_finished_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfunction',
            name='ebs_percent',
            field=models.IntegerField(default=0, verbose_name='% mínimo de EBS'),
        ),
    ]
