# Generated by Django 4.1.6 on 2023-08-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0009_taskfunction_ebs_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfunction',
            name='ebs_percent',
            field=models.IntegerField(default=0, verbose_name='% EBS'),
        ),
        migrations.AlterModelTable(
            name='statustask',
            table=None,
        ),
    ]
