# Generated by Django 4.1.6 on 2023-04-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0009_alter_taskfunction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='re_process_stages',
            field=models.ManyToManyField(blank=True, related_name='re_processing', to='classify_task.stage', verbose_name='Etapas a re-procesar'),
        ),
    ]
