# Generated by Django 4.1.6 on 2023-10-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0010_alter_taskfunction_ebs_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_group',
            field=models.CharField(blank=True, choices=[('transformation', 'Transformación'), ('months', 'Meses'), ('entity', 'Proveedor')], max_length=30, null=True),
        ),
    ]
