# Generated by Django 4.1.6 on 2023-04-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0010_stage_re_process_stages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfunction',
            options={'ordering': ['-is_active', 'model_name', 'is_from_aws', 'name'], 'verbose_name': 'Función (tarea)', 'verbose_name_plural': '2. Funciones (tareas)'},
        ),
    ]
