# Generated by Django 4.1.6 on 2023-10-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0012_alter_statustask_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statustask',
            name='description',
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
