# Generated by Django 4.1.6 on 2023-10-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0015_stage_description_alter_stage_action_verb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_group',
            field=models.CharField(blank=True, choices=[('transformation', 'Transformación'), ('months', 'Meses'), ('entity', 'Proveedor'), ('entity-petition', 'Proveedor (Solicitud)'), ('entity-control', 'Proveedor (Grupos de control)'), ('entity-month', 'Proveedor (Meses)')], max_length=30, null=True),
        ),
    ]
