# Generated by Django 4.1.6 on 2024-02-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0016_alter_stage_stage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
