# Generated by Django 4.1.6 on 2024-03-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0018_alter_stage_stage_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfunction',
            name='group_queue',
            field=models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('reply_file', 'ReplyFile (.zip)'), ('sheet_file', 'Pestaña'), ('week_record', 'Semana Proveedor'), ('month_record', 'Mes Proveedor'), ('provider', 'Proveedor')], max_length=100, null=True, verbose_name='agrupables'),
        ),
        migrations.AlterField(
            model_name='taskfunction',
            name='model_name',
            field=models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('reply_file', 'ReplyFile (.zip)'), ('sheet_file', 'Pestaña'), ('week_record', 'Semana Proveedor'), ('month_record', 'Mes Proveedor'), ('provider', 'Proveedor')], max_length=100, null=True),
        ),
    ]
