# Generated by Django 4.1.6 on 2024-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0019_alter_taskfunction_group_queue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfunction',
            name='group_queue',
            field=models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('reply_file', 'ReplyFile (.zip)'), ('sheet_file', 'Pestaña'), ('week_record', 'Semana Proveedor'), ('month_record', 'Mes Proveedor'), ('provider', 'Proveedor'), ('cluster_year', 'Cluster y año'), ('mat_view', 'Materialized View')], max_length=100, null=True, verbose_name='agrupables'),
        ),
        migrations.AlterField(
            model_name='taskfunction',
            name='model_name',
            field=models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('reply_file', 'ReplyFile (.zip)'), ('sheet_file', 'Pestaña'), ('week_record', 'Semana Proveedor'), ('month_record', 'Mes Proveedor'), ('provider', 'Proveedor'), ('cluster_year', 'Cluster y año'), ('mat_view', 'Materialized View')], max_length=100, null=True),
        ),
    ]
