# Generated by Django 4.1.6 on 2024-07-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0002_delete_dictionaryfile'),
        ('inai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='complain_send_limit',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de envío de queja'),
        ),
        migrations.AlterUniqueTogether(
            name='petitionfilecontrol',
            unique_together={('petition', 'file_control')},
        ),
    ]
