# Generated by Django 2.2.25 on 2022-07-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_datebreak'),
        ('inai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='break_dates',
            field=models.ManyToManyField(blank=True, to='category.DateBreak', verbose_name='Fechas de corte'),
        ),
    ]
