# Generated by Django 4.1.6 on 2023-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapsheet',
            name='real_missing_rows',
            field=models.IntegerField(default=0),
        ),
    ]
