# Generated by Django 4.1.6 on 2024-08-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0002_cluster_icon'),
        ('inai', '0002_petition_complain_send_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthrecord',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_records', to='rds.cluster'),
        ),
    ]
