# Generated by Django 2.2.25 on 2022-07-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_datebreak'),
        ('inai', '0002_petition_break_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='break_dates',
        ),
        migrations.CreateModel(
            name='PetitionBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('date_break', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.DateBreak')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.Petition')),
            ],
            options={
                'verbose_name': 'Petición - fecha de corte (m2m)',
                'verbose_name_plural': 'Peticiones - fechas de corte (m2m)',
            },
        ),
    ]
