# Generated by Django 4.1.13 on 2024-07-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0002_run_python'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='complain_send_limit',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de envío de queja'),
        ),
    ]
