# Generated by Django 2.2.25 on 2022-07-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0003_auto_20220729_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='folio_queja',
            new_name='folio_complain',
        ),
    ]
