# Generated by Django 4.1.6 on 2023-05-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
        ('inai', '0003_alter_replyfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='geo.entity'),
        ),
    ]
