# Generated by Django 4.1.6 on 2024-08-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0003_alter_monthrecord_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthrecord',
            name='self_repeated_count',
            field=models.IntegerField(default=0),
        ),
    ]
