# Generated by Django 2.2.25 on 2022-07-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0004_auto_20220729_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='date_response',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='date_send',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='limit_complain',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='limit_pickup',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='limit_response',
        ),
    ]
