# Generated by Django 4.1.6 on 2023-05-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0004_datafile_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetfile',
            name='year_month',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Año y mes'),
        ),
    ]
