# Generated by Django 4.1.6 on 2024-08-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0004_monthrecord_self_repeated_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekrecord',
            name='self_repeated_count',
            field=models.IntegerField(default=0),
        ),
    ]
