# Generated by Django 4.1.6 on 2023-05-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
        ('inai', '0005_sheetfile_year_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthagency',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_entities', to='geo.entity'),
        ),
    ]
