# Generated by Django 2.2.25 on 2022-07-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0006_auto_20220729_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='petitionbreak',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
