# Generated by Django 4.1.6 on 2023-05-06 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
        ('inai', '0006_monthagency_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetfile',
            name='duplicates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duplicados'),
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='prescriptions_count',
            field=models.IntegerField(default=0, verbose_name='Prescripciones procesadas'),
        ),
        migrations.CreateModel(
            name='CrossingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_crossing', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossing_sheets', to='geo.entity')),
                ('sheet_file_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossing_1', to='inai.sheetfile')),
                ('sheet_file_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossing_2', to='inai.sheetfile')),
            ],
            options={
                'verbose_name': 'Mes de cruce',
                'verbose_name_plural': 'Meses de cruce',
                'get_latest_by': 'month_agency__year_month',
            },
        ),
    ]
