# Generated by Django 4.1.6 on 2023-05-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0007_sheetfile_duplicates_sheetfile_prescriptions_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('public_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('is_merge', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Comportamiento',
                'verbose_name_plural': '4. Comportamientos Merge',
            },
        ),
        migrations.AlterModelOptions(
            name='sheetfile',
            options={'ordering': ['id'], 'verbose_name': 'Archivo de pestaña (csv)', 'verbose_name_plural': '4. Archivos de pestaña (csv)'},
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='completed_rows',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='inserted_rows',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='origin_file',
        ),
        migrations.AlterField(
            model_name='sheetfile',
            name='duplicates',
            field=models.IntegerField(default=0, verbose_name='Duplicados'),
        ),
        migrations.AlterField(
            model_name='sheetfile',
            name='year_month',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Año y mes'),
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='behavior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.behavior', verbose_name='merge behavior'),
        ),
    ]
