# Generated by Django 2.2.25 on 2022-07-30 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0001_initial'),
        ('inai', '0007_auto_20220729_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontrol',
            name='data_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_param.DataGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filecontrol',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.FileType'),
        ),
        migrations.AlterField(
            model_name='petitionbreak',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_dates', to='inai.Petition'),
        ),
        migrations.AlterField(
            model_name='petitionfilecontrol',
            name='file_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='inai.FileControl'),
        ),
    ]
