# Generated by Django 2.2.25 on 2022-07-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0008_auto_20220730_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecontrol',
            options={'verbose_name': 'Grupo control de archivos', 'verbose_name_plural': 'Grupos control de archivos'},
        ),
    ]
