# Generated by Django 4.1.6 on 2023-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0008_behavior_alter_sheetfile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossingsheet',
            old_name='count',
            new_name='duplicates_count',
        ),
        migrations.AddField(
            model_name='crossingsheet',
            name='shared_count',
            field=models.IntegerField(default=0),
        ),
    ]
