# Generated by Django 2.2.25 on 2022-07-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0009_auto_20220730_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petition',
            options={'verbose_name': 'Solicitud - Petición', 'verbose_name_plural': 'Solicitudes (Petiticiones)'},
        ),
        migrations.AlterField(
            model_name='petition',
            name='folio_petition',
            field=models.IntegerField(default=123123, verbose_name='Folio de la solicitud'),
            preserve_default=False,
        ),
    ]
