# Generated by Django 4.1.6 on 2023-05-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0009_rename_count_crossingsheet_duplicates_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetfile',
            old_name='duplicates',
            new_name='duplicates_count',
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='shared_count',
            field=models.IntegerField(default=0, verbose_name='Compartidos'),
        ),
    ]
