# Generated by Django 4.1.6 on 2023-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0010_rename_duplicates_sheetfile_duplicates_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthagency',
            name='duplicate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthagency',
            name='last_crossing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthagency',
            name='prescriptions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthagency',
            name='shared_count',
            field=models.IntegerField(default=0),
        ),
    ]
