# Generated by Django 2.2.25 on 2022-07-31 05:47

from django.db import migrations, models
import django.db.models.deletion
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0010_auto_20220730_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='ori_file',
            field=models.FileField(max_length=150, upload_to=inai.models.set_upload_path),
        ),
        migrations.AlterField(
            model_name='petitionfilecontrol',
            name='file_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_file_control', to='inai.FileControl'),
        ),
        migrations.AlterField(
            model_name='processfile',
            name='ori_file',
            field=models.FileField(max_length=150, upload_to=inai.models.set_upload_path),
        ),
    ]
