# Generated by Django 2.2.25 on 2022-08-01 19:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0011_auto_20220731_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionmonth',
            options={'get_latest_by': 'month_entity__yearmonth', 'verbose_name': 'Mes de peticion', 'verbose_name_plural': 'Meses de peticion'},
        ),
        migrations.AddField(
            model_name='petition',
            name='description_petition',
            field=models.TextField(blank=True, null=True, verbose_name='descripción enviada'),
        ),
        migrations.AddField(
            model_name='petition',
            name='description_response',
            field=models.TextField(blank=True, null=True, verbose_name='descripción enviada'),
        ),
        migrations.AddField(
            model_name='petition',
            name='id_inai_open_data',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id en el sistema de INAI'),
        ),
        migrations.AddField(
            model_name='petition',
            name='info_queja_inai',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Información de la queja en INAI Seach', null=True, verbose_name='Datos de queja'),
        ),
        migrations.AddField(
            model_name='petition',
            name='send_petition',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de envío o recepción'),
        ),
        migrations.AddField(
            model_name='petition',
            name='send_response',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de última respuesta'),
        ),
        migrations.AddField(
            model_name='processfile',
            name='url_download',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Url donde se puede descargar el archivo'),
        ),
        migrations.AlterField(
            model_name='processfile',
            name='ori_file',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=inai.models.set_upload_path, verbose_name='arhivo'),
        ),
    ]
