# Generated by Django 4.1.6 on 2023-05-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0011_monthagency_duplicate_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthagency',
            old_name='duplicate_count',
            new_name='duplicates_count',
        ),
    ]
