# Generated by Django 2.2.25 on 2022-08-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0012_auto_20220801_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionmonth',
            options={'verbose_name': 'Mes de peticion', 'verbose_name_plural': 'Meses de peticion'},
        ),
        migrations.AlterField(
            model_name='petition',
            name='folio_petition',
            field=models.CharField(max_length=50, verbose_name='Folio de la solicitud'),
        ),
    ]
