# Generated by Django 4.1.6 on 2023-05-09 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0012_rename_duplicate_count_monthagency_duplicates_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthagency',
            options={'get_latest_by': 'year_month', 'ordering': ['year_month'], 'verbose_name': 'Mes de entidad', 'verbose_name_plural': 'Meses de entidad'},
        ),
        migrations.AlterField(
            model_name='sheetfile',
            name='behavior',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.CASCADE, to='inai.behavior', verbose_name='merge behavior'),
        ),
    ]
