# Generated by Django 4.1.6 on 2023-05-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0013_alter_monthagency_options_alter_sheetfile_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefile',
            name='delegation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='iso_week',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
