# Generated by Django 2.2.25 on 2022-08-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_filetype_public_name'),
        ('inai', '0013_auto_20220801_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthentity',
            options={'get_latest_by': 'year_month', 'verbose_name': 'Mes de entidad', 'verbose_name_plural': 'Meses de entidad'},
        ),
        migrations.AlterModelOptions(
            name='petitionmonth',
            options={'get_latest_by': 'month_entity__year_month', 'verbose_name': 'Mes de peticion', 'verbose_name_plural': 'Meses de peticion'},
        ),
        migrations.AddField(
            model_name='petition',
            name='status_complain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions_complain', to='category.StatusControl', verbose_name='Status de la queja'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='description_response',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta texto'),
        ),
    ]
