# Generated by Django 2.2.25 on 2022-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0014_auto_20220802_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontrol',
            name='final_data',
            field=models.BooleanField(verbose_name='Es información final'),
        ),
        migrations.AlterField(
            model_name='filecontrol',
            name='name',
            field=models.CharField(default='grupo único', max_length=255),
        ),
        migrations.AlterField(
            model_name='filecontrol',
            name='row_start_data',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='# de fila donde inician los datos'),
        ),
    ]
