# Generated by Django 4.1.6 on 2023-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0003_alter_cleanfunction_ready_code'),
        ('inai', '0014_tablefile_delegation_name_tablefile_iso_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petitionmonth',
            name='notes',
        ),
        migrations.AddField(
            model_name='petition',
            name='months_agency',
            field=models.ManyToManyField(blank=True, to='inai.monthagency', verbose_name='Meses de la solicitud'),
        ),
        migrations.AlterUniqueTogether(
            name='tablefile',
            unique_together={('lap_sheet', 'collection', 'is_for_edition', 'year', 'iso_week', 'delegation_name')},
        ),
    ]
