# Generated by Django 4.1.6 on 2023-05-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0015_remove_petitionmonth_notes_petition_months_agency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lapsheet',
            old_name='prescription_count',
            new_name='rx_count',
        ),
        migrations.RenameField(
            model_name='monthagency',
            old_name='prescriptions_count',
            new_name='rx_count',
        ),
        migrations.RenameField(
            model_name='sheetfile',
            old_name='prescriptions_count',
            new_name='rx_count',
        ),
    ]
