# Generated by Django 2.2.25 on 2022-08-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0002_auto_20220801_0807'),
        ('inai', '0015_auto_20220802_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='ori_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='processfile',
            old_name='ori_file',
            new_name='file',
        ),
        migrations.AlterUniqueTogether(
            name='filecontrol',
            unique_together={('data_group', 'name')},
        ),
    ]
