# Generated by Django 4.1.6 on 2023-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0017_remove_datafile_file_type_monthagency_drugs_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthagency',
            name='last_transformation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
