# Generated by Django 2.2.25 on 2022-08-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0017_auto_20220808_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='description_complain',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de la queja'),
        ),
    ]
