# Generated by Django 2.2.25 on 2022-08-09 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0018_petition_description_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='month_entity',
        ),
        migrations.AddField(
            model_name='datafile',
            name='petition_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.PetitionMonth'),
        ),
    ]
