# Generated by Django 4.1.6 on 2023-05-19 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
        ('inai', '0018_monthagency_last_transformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='petition_month',
        ),
        migrations.AddField(
            model_name='tablefile',
            name='iso_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='year_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='iso_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeekEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.SmallIntegerField(blank=True, null=True)),
                ('iso_week', models.SmallIntegerField(blank=True, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.SmallIntegerField(blank=True, null=True)),
                ('year_month', models.CharField(max_length=10)),
                ('drugs_count', models.IntegerField(default=0)),
                ('rx_count', models.IntegerField(default=0)),
                ('duplicates_count', models.IntegerField(default=0)),
                ('shared_count', models.IntegerField(default=0)),
                ('last_crossing', models.DateTimeField(blank=True, null=True)),
                ('last_transformation', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='geo.entity')),
            ],
            options={
                'verbose_name': 'Semana de entidad',
                'verbose_name_plural': '7. Semanas de entidad',
                'get_latest_by': ['year_month', 'iso_week'],
            },
        ),
        migrations.AddField(
            model_name='tablefile',
            name='week_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.weekentity'),
        ),
    ]
