# Generated by Django 2.2.25 on 2022-08-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0019_auto_20220808_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecolumn',
            name='name_in_data',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre de la columna real'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='position_in_data',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
