# Generated by Django 4.1.6 on 2023-05-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
        ('inai', '0019_remove_datafile_petition_month_tablefile_iso_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.SmallIntegerField(blank=True, null=True)),
                ('iso_week', models.SmallIntegerField(blank=True, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.SmallIntegerField(blank=True, null=True)),
                ('year_month', models.CharField(max_length=10)),
                ('drugs_count', models.IntegerField(default=0)),
                ('rx_count', models.IntegerField(default=0)),
                ('duplicates_count', models.IntegerField(default=0)),
                ('shared_count', models.IntegerField(default=0)),
                ('last_crossing', models.DateTimeField(blank=True, null=True)),
                ('last_transformation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Semana de entidad',
                'verbose_name_plural': '7. Semanas de entidad',
                'get_latest_by': ['year_month', 'iso_week'],
            },
        ),
        migrations.RemoveField(
            model_name='weekentity',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='week_entity',
        ),
        migrations.AlterField(
            model_name='monthagency',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='geo.agency'),
        ),
        migrations.AlterField(
            model_name='monthagency',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_months', to='geo.entity'),
        ),
    ]
