# Generated by Django 4.1.6 on 2023-05-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_asynctask_week_entity_asynctask_entity_week'),
        ('inai', '0020_entityweek_remove_weekentity_entity_and_more'),
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekEntity',
        ),
        migrations.AddField(
            model_name='entityweek',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='geo.entity'),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='entity_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='inai.monthagency'),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='entity_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.entityweek'),
        ),
    ]
