# Generated by Django 2.2.25 on 2022-08-09 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0004_auto_20220809_0157'),
        ('inai', '0020_auto_20220809_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecolumn',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.Collection'),
        ),
    ]
