# Generated by Django 4.1.6 on 2023-05-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
        ('inai', '0021_delete_weekentity_entityweek_entity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthAgency',
            new_name='EntityMonth',
        ),
        migrations.RenameField(
            model_name='petitionmonth',
            old_name='month_agency',
            new_name='entity_month',
        ),
    ]
