# Generated by Django 2.2.25 on 2022-08-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20220811_1216'),
        ('inai', '0021_namecolumn_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontrol',
            name='anomalies',
            field=models.ManyToManyField(blank=True, to='category.Anomaly', verbose_name='Anomalías de los datos'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='clean_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_param.CleanFunction', verbose_name='Función de limpieza o transformación'),
        ),
    ]
