# Generated by Django 4.1.6 on 2023-05-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0022_rename_monthagency_entitymonth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='months_agency',
            new_name='entity_months',
        ),
    ]
