# Generated by Django 2.2.25 on 2022-08-12 04:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0022_auto_20220811_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecolumn',
            name='clean_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Parámetros de limpieza'),
        ),
    ]
