# Generated by Django 2.2.25 on 2022-08-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0006_auto_20220816_1121'),
        ('inai', '0023_auto_20220811_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namecolumn',
            options={'ordering': ['collection', 'final_field', 'name_in_data'], 'verbose_name': 'Nombre de Columna', 'verbose_name_plural': 'Nombres de Columnas'},
        ),
        migrations.AddField(
            model_name='namecolumn',
            name='parameter_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.ParameterGroup'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='position_in_data',
            field=models.IntegerField(blank=True, null=True, verbose_name='idx'),
        ),
    ]
