# Generated by Django 4.1.6 on 2023-05-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0023_rename_months_agency_petition_entity_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityweek',
            name='delegation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
