# Generated by Django 2.2.25 on 2022-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0024_auto_20220816_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecolumn',
            name='seq',
            field=models.IntegerField(blank=True, help_text='Número consecutivo para ordenación en dashboard', null=True, verbose_name='order'),
        ),
    ]
