# Generated by Django 4.1.6 on 2023-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0024_entityweek_delegation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossingsheet',
            name='delegation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crossingsheet',
            name='iso_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crossingsheet',
            name='iso_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
