# Generated by Django 4.1.6 on 2023-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0025_crossingsheet_delegation_name_crossingsheet_iso_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityweek',
            name='year_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
