# Generated by Django 2.2.25 on 2022-08-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0025_namecolumn_seq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namecolumn',
            options={'ordering': ['seq'], 'verbose_name': 'Nombre de Columna', 'verbose_name_plural': 'Nombres de Columnas'},
        ),
        migrations.AlterField(
            model_name='transformation',
            name='file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_transformations', to='inai.FileControl', verbose_name='Grupo de archivos'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='name_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_transformations', to='inai.NameColumn', verbose_name='Columna'),
        ),
    ]
