# Generated by Django 2.2.25 on 2022-08-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0026_auto_20220816_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processfile',
            options={'verbose_name': 'Archivo sin datos finales', 'verbose_name_plural': 'Archivos sin datos finales'},
        ),
    ]
