# Generated by Django 4.1.6 on 2023-05-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0027_tablefile_inserted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefile',
            name='drugs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='duplicates_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='rx_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='shared_count',
            field=models.IntegerField(default=0),
        ),
    ]
