# Generated by Django 2.2.25 on 2022-08-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0027_auto_20220817_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namecolumn',
            old_name='children_row',
            new_name='children_column',
        ),
        migrations.RenameField(
            model_name='namecolumn',
            old_name='parent_row',
            new_name='parent_column',
        ),
    ]
