# Generated by Django 2.2.25 on 2022-08-18 08:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0028_auto_20220818_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='addl_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=inai.models.default_addl_params, null=True),
        ),
    ]
