# Generated by Django 4.1.6 on 2023-05-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0028_tablefile_drugs_count_tablefile_duplicates_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymonth',
            name='last_insertion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='entity_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_files', to='inai.entityweek'),
        ),
    ]
