# Generated by Django 4.1.6 on 2023-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0029_entitymonth_last_insertion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablefile',
            options={'ordering': ['-id'], 'verbose_name': 'Archivo para insertar', 'verbose_name_plural': '6. Archivos para insertar'},
        ),
        migrations.AddField(
            model_name='lapsheet',
            name='basic_inserted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='lapsheet',
            name='cat_inserted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
