# Generated by Django 2.2.25 on 2022-08-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0030_auto_20220822_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontrol',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='filecontrol',
            unique_together=set(),
        ),
    ]
