# Generated by Django 4.1.6 on 2023-05-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0030_alter_tablefile_options_lapsheet_basic_inserted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapsheet',
            name='missing_inserted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
