# Generated by Django 2.2.25 on 2022-08-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0031_auto_20220823_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transformation',
            options={'verbose_name': 'Transformación a aplicar', 'verbose_name_plural': 'Transformaciones a aplicar'},
        ),
    ]
