# Generated by Django 4.1.6 on 2023-05-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0031_lapsheet_missing_inserted'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityweek',
            name='year_week',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='year_week',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='year_month',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
