# Generated by Django 2.2.25 on 2022-09-01 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_invalidreason'),
        ('inai', '0032_auto_20220831_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='invalid_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.InvalidReason', verbose_name='Razón de invalidez'),
        ),
    ]
