# Generated by Django 4.1.6 on 2023-05-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0032_entityweek_year_week_tablefile_year_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossingsheet',
            name='year_week',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
