# Generated by Django 2.2.25 on 2022-09-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0033_petition_invalid_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionfilecontrol',
            options={'verbose_name': 'Relacional: petición -- Grupo de Control', 'verbose_name_plural': 'Relacional: Petición -- Grupos de Control'},
        ),
        migrations.RemoveField(
            model_name='namecolumn',
            name='parameter_group',
        ),
    ]
