# Generated by Django 4.1.6 on 2023-05-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0005_alter_collection_model_name'),
        ('inai', '0033_crossingsheet_year_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityweek',
            options={'get_latest_by': ['year_month', 'year_week'], 'verbose_name': 'Semana de entidad', 'verbose_name_plural': '7. Semanas de entidad'},
        ),
        migrations.AlterUniqueTogether(
            name='tablefile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='crossingsheet',
            name='delegation_name',
        ),
        migrations.RemoveField(
            model_name='entityweek',
            name='delegation_name',
        ),
        migrations.AddField(
            model_name='crossingsheet',
            name='iso_delegation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='iso_delegation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='iso_delegation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tablefile',
            unique_together={('lap_sheet', 'collection', 'is_for_edition', 'year', 'iso_week', 'iso_delegation')},
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='delegation_name',
        ),
    ]
