# Generated by Django 2.2.25 on 2022-09-12 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0034_auto_20220907_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='process_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.ProcessFile', verbose_name='archivo base'),
        ),
        migrations.AddField(
            model_name='processfile',
            name='has_data',
            field=models.BooleanField(default=False, verbose_name='Contiene los datos'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='origin_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_files', to='inai.DataFile', verbose_name='archivo origen'),
        ),
    ]
