# Generated by Django 4.1.6 on 2023-05-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_entity_split_by_delegation_alter_agency_entity'),
        ('inai', '0034_alter_entityweek_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefile',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.entity'),
        ),
    ]
