# Generated by Django 2.2.25 on 2022-09-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0035_auto_20220911_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='directory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta en archivo comprimido'),
        ),
    ]
