# Generated by Django 4.1.6 on 2023-05-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_entity_split_by_delegation_alter_agency_entity'),
        ('inai', '0035_tablefile_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymonth',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='geo.agency', verbose_name='Sujeto Obligado'),
        ),
        migrations.AlterField(
            model_name='entitymonth',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_months', to='geo.entity', verbose_name='Proveedor de servicios de salud'),
        ),
    ]
