# Generated by Django 2.2.25 on 2022-09-15 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0036_datafile_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='process_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file_childs', to='inai.ProcessFile', verbose_name='archivo base'),
        ),
    ]
