# Generated by Django 4.1.6 on 2023-06-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0036_alter_entitymonth_agency_alter_entitymonth_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapsheet',
            name='basic_inserted',
        ),
    ]
