# Generated by Django 4.1.6 on 2023-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0037_remove_lapsheet_basic_inserted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetfile',
            name='entity_months',
            field=models.ManyToManyField(blank=True, related_name='sheet_files', to='inai.entitymonth', verbose_name='Años y meses'),
        ),
    ]
