# Generated by Django 2.2.25 on 2022-09-21 20:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0037_auto_20220914_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecontrol',
            options={'verbose_name': 'Grupo de control de archivos', 'verbose_name_plural': 'Grupos de control de archivos'},
        ),
        migrations.AddField(
            model_name='datafile',
            name='explore_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=inai.models.default_explore_data, null=True, verbose_name='Primeros datos, de exploración'),
        ),
    ]
