# Generated by Django 2.2.25 on 2022-10-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_fileformat_transparencyindex_transparencylevel'),
        ('inai', '0038_auto_20220921_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontrol',
            name='file_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.FileFormat', verbose_name='formato del archivo'),
        ),
    ]
