# Generated by Django 4.1.6 on 2023-06-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0038_sheetfile_entity_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossingsheet',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='crossingsheet',
            name='iso_delegation',
        ),
        migrations.RemoveField(
            model_name='crossingsheet',
            name='iso_week',
        ),
        migrations.RemoveField(
            model_name='crossingsheet',
            name='iso_year',
        ),
        migrations.RemoveField(
            model_name='crossingsheet',
            name='year_week',
        ),
        migrations.AddField(
            model_name='crossingsheet',
            name='entity_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crossing_sheets', to='inai.entityweek'),
        ),
    ]
