# Generated by Django 2.2.25 on 2022-12-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0039_filecontrol_file_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petition',
            options={'verbose_name': 'Solicitud - Petición', 'verbose_name_plural': 'Solicitudes (Peticiones)'},
        ),
    ]
