# Generated by Django 4.1.6 on 2023-06-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_delegation_entity'),
        ('inai', '0039_remove_crossingsheet_entity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entityweek',
            unique_together={('entity', 'year_week', 'iso_delegation', 'year_month')},
        ),
    ]
