# Generated by Django 4.1.6 on 2023-06-23 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_alter_entity_options_alter_entity_state'),
        ('inai', '0040_alter_entityweek_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='real_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_petitions', to='geo.entity'),
        ),
    ]
