# Generated by Django 4.1.6 on 2023-06-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0041_petition_real_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetfile',
            options={'ordering': ['id'], 'verbose_name': 'Archivo de pestaña (csv)', 'verbose_name_plural': '4. Archivos de pestaña (Sheets .csv)'},
        ),
        migrations.AddField(
            model_name='entityweek',
            name='last_insertion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheetfile',
            name='entity_months',
            field=models.ManyToManyField(blank=True, related_name='sheet_files', to='inai.entitymonth'),
        ),
    ]
