# Generated by Django 4.1.6 on 2023-06-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0042_alter_sheetfile_options_entityweek_last_insertion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymonth',
            name='last_merge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='last_merge',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
