# Generated by Django 4.1.6 on 2023-02-15 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0026_statustask_is_completed'),
        ('inai', '0043_datafile_suffix_alter_asynctask_function_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecontrol',
            name='file_type',
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype', verbose_name='Tipo de archivo'),
        ),
    ]
