# Generated by Django 4.1.6 on 2023-06-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0043_entitymonth_last_merge_entityweek_last_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossingsheet',
            name='entity_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crossing_sheets', to='inai.entitymonth'),
        ),
    ]
