# Generated by Django 4.1.6 on 2023-06-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0044_crossingsheet_entity_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityweek',
            name='cancelled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='complete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='denied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='over_delivered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='partial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='unavailable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='unknown',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityweek',
            name='zero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
