# Generated by Django 4.1.6 on 2023-02-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0044_remove_filecontrol_file_type_datafile_file_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsyncTask',
        ),
    ]
