# Generated by Django 4.1.6 on 2023-06-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0045_entityweek_cancelled_entityweek_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lapsheet',
            old_name='drug_count',
            new_name='drugs_count',
        ),
    ]
