# Generated by Django 4.1.6 on 2023-02-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0045_delete_asynctask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='explore_data',
            new_name='sample_data',
        ),
    ]
