# Generated by Django 4.1.6 on 2023-07-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0046_rename_drug_count_lapsheet_drugs_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossingsheet',
            options={'get_latest_by': 'month_agency__year_month', 'verbose_name': 'Cruce de archivos', 'verbose_name_plural': '5.1 Cruces de archivos'},
        ),
        migrations.AlterModelOptions(
            name='entitymonth',
            options={'get_latest_by': 'year_month', 'ordering': ['year_month'], 'verbose_name': '8. Mes de proveedor (entity)', 'verbose_name_plural': '8. Meses de proveedores (entity)'},
        ),
        migrations.AlterModelOptions(
            name='entityweek',
            options={'get_latest_by': ['year_month', 'year_week'], 'verbose_name': 'Semana de proveedor (entity)', 'verbose_name_plural': '9. Semanas de proveedores (entities)'},
        ),
        migrations.AddField(
            model_name='entitymonth',
            name='month',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitymonth',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
