# Generated by Django 4.1.6 on 2023-02-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0047_filecontrol_all_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_transformations', to='inai.filecontrol', verbose_name='Grupo de control'),
        ),
    ]
