# Generated by Django 4.1.6 on 2023-02-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0021_rename_requiered_finalfield_required_and_more'),
        ('inai', '0048_alter_transformation_file_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontrol',
            name='decode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codificación'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='final_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_columns', to='data_param.finalfield'),
        ),
    ]
