# Generated by Django 4.1.6 on 2023-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0049_filecontrol_decode_alter_namecolumn_final_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontrol',
            name='data_group',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filecontrol',
            name='file_format',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filecontrol',
            name='status_register',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='collection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='column_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='data_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='file_control',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='final_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petitionfilecontrol',
            name='file_control',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='clean_function',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='file_control',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='name_column',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
