# Generated by Django 4.1.6 on 2023-07-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0049_alter_datafile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymonth',
            name='last_insertion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
