# Generated by Django 4.1.6 on 2023-03-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0050_alter_filecontrol_data_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecontrol',
            name='anomalies',
        ),
        migrations.DeleteModel(
            name='Transformation',
        ),
        migrations.DeleteModel(
            name='FileControl',
        ),
    ]
