# Generated by Django 4.1.6 on 2023-07-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_alter_entity_options'),
        ('inai', '0050_entitymonth_last_insertion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityweek',
            name='iso_delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation'),
        ),
    ]
