# Generated by Django 4.1.6 on 2023-03-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0051_remove_filecontrol_anomalies_delete_transformation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameColumn',
        ),
    ]
