# Generated by Django 4.1.6 on 2023-07-29 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_alter_entity_options'),
        ('inai', '0051_alter_entityweek_iso_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_files', to='geo.entity'),
        ),
    ]
