# Generated by Django 4.1.6 on 2023-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0052_behavior_is_discarded_alter_tablefile_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymonth',
            name='error_process',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
