# Generated by Django 4.1.6 on 2023-03-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0025_alter_filecontrol_data_group_and_more'),
        ('inai', '0052_delete_namecolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionfilecontrol',
            name='file_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_file_control', to='data_param.filecontrol'),
        ),
    ]
