# Generated by Django 4.1.6 on 2023-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0053_entitymonth_error_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymonth',
            name='drugs_in_pre_insertion',
            field=models.IntegerField(default=0),
        ),
    ]
