# Generated by Django 4.1.6 on 2023-03-05 18:39

from django.db import migrations, models
import inai.models
import inai.reply_file_mixins.process_mix


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0053_alter_petitionfilecontrol_file_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=150, null=True, upload_to=inai.models.set_upload_path, verbose_name='arhivo')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto (en caso de no haber archivo)')),
                ('url_download', models.URLField(blank=True, max_length=400, null=True, verbose_name='Url donde se puede descargar el archivo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('addl_params', models.JSONField(blank=True, null=True, verbose_name='Otras configuraciones')),
                ('has_data', models.BooleanField(default=False, verbose_name='Contiene los datos')),
            ],
            options={
                'verbose_name': 'Archivo sin datos finales',
                'verbose_name_plural': 'Archivos sin datos finales',
            },
            bases=(models.Model, inai.reply_file_mixins.process_mix.ReplyFileMix),
        ),
        migrations.RemoveField(
            model_name='processfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='processfile',
            name='petition',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='process_file',
        ),
    ]
