# Generated by Django 4.1.6 on 2023-03-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0054_replyfile_remove_processfile_file_type_and_more'),
        ('task', '0010_alter_asynctask_options_and_more'),
        ('category', '0030_alter_fileformat_addl_params_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessFile',
        ),
        migrations.AddField(
            model_name='replyfile',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype'),
        ),
        migrations.AddField(
            model_name='replyfile',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_files', to='inai.petition'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='reply_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file_childs', to='inai.replyfile', verbose_name='archivo base'),
        ),
    ]
