# Generated by Django 4.1.6 on 2023-08-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_alter_entity_options'),
        ('inai', '0054_entitymonth_drugs_in_pre_insertion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablefile',
            name='iso_delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation'),
        ),
    ]
