# Generated by Django 4.1.6 on 2023-03-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0003_remove_stage_color_alter_statustask_table_and_more'),
        ('inai', '0055_delete_processfile_replyfile_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='sheets_to_insert',
            field=models.JSONField(blank=True, null=True, verbose_name='Nombres de las hojas a insertar'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa actual'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask', verbose_name='Status actual'),
        ),
    ]
