# Generated by Django 4.1.6 on 2023-08-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0055_alter_tablefile_iso_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymonth',
            name='last_validate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
