# Generated by Django 4.1.6 on 2023-03-14 17:31

from django.db import migrations, models
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0056_datafile_sheets_to_insert_datafile_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='sheets_to_insert',
        ),
        migrations.AddField(
            model_name='datafile',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=inai.models.set_upload_path),
        ),
        migrations.AddField(
            model_name='datafile',
            name='sheets_info',
            field=models.JSONField(blank=True, default=inai.models.default_explore_data, null=True, verbose_name='Información de las hojas'),
        ),
    ]
