# Generated by Django 4.1.6 on 2023-08-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0007_stage_field_last_edit_taskfunction_lambda_function'),
        ('inai', '0056_entitymonth_last_validate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_process', models.JSONField(blank=True, null=True)),
                ('entity_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='inai.entitymonth', verbose_name='Mes-proveedor')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask', verbose_name='Status')),
            ],
            options={
                'verbose_name': '9. Paso',
                'verbose_name_plural': '9. Pasos',
            },
        ),
    ]
