# Generated by Django 4.1.6 on 2023-08-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0057_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitymonth',
            old_name='last_validate',
            new_name='last_indexing',
        ),
    ]
