# Generated by Django 4.1.6 on 2023-03-16 18:07

from django.db import migrations, models
import django.db.models.deletion
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0032_remove_filetype_id_alter_filetype_name'),
        ('inai', '0057_remove_datafile_sheets_to_insert_datafile_csv_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='sheets_info',
        ),
        migrations.AddField(
            model_name='datafile',
            name='filtered_sheets',
            field=models.JSONField(blank=True, null=True, verbose_name='Nombres de las hojas filtradas'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='completed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_type',
            field=models.ForeignKey(blank=True, default='original_data', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype', verbose_name='Tipo de archivo'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='inserted_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=inai.models.set_upload_path)),
                ('matched', models.BooleanField(blank=True, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_data', models.JSONField(blank=True, default=inai.models.default_explore_data, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('completed_rows', models.IntegerField(default=0)),
                ('inserted_rows', models.IntegerField(default=0)),
                ('all_results', models.JSONField(blank=True, null=True)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_files', to='inai.datafile')),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype')),
            ],
            options={
                'verbose_name': 'Archivo con datos',
                'verbose_name_plural': 'Archivos con datos',
                'unique_together': {('data_file', 'sheet_name', 'file_type')},
            },
        ),
    ]
