# Generated by Django 4.1.6 on 2023-08-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0058_rename_last_validate_entitymonth_last_validates'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymonth',
            name='last_validate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
