# Generated by Django 4.1.6 on 2023-03-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0059_alter_datafile_status_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablefile',
            options={'verbose_name': 'Archivo csv', 'verbose_name_plural': 'Archivos csv'},
        ),
    ]
