# Generated by Django 4.1.6 on 2023-10-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0059_entitymonth_last_validate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
