# Generated by Django 4.1.6 on 2023-11-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0060_delete_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['-id'], 'verbose_name': 'Archivo con datos', 'verbose_name_plural': '3. Archivos con datos (DataFile)'},
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='zip_path',
        ),
    ]
