# Generated by Django 4.1.6 on 2023-03-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0060_alter_tablefile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='replyfile',
            name='file_type',
        ),
    ]
