# Generated by Django 4.1.6 on 2023-03-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0032_remove_filetype_id_alter_filetype_name'),
        ('inai', '0061_remove_datafile_file_type_remove_replyfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='file_type',
            field=models.ForeignKey(blank=True, default='original_data', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype', verbose_name='Tipo de archivo'),
        ),
        migrations.AddField(
            model_name='replyfile',
            name='file_type',
            field=models.ForeignKey(blank=True, default='no_final_info', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype'),
        ),
    ]
