# Generated by Django 4.1.6 on 2024-03-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0061_alter_datafile_options_remove_datafile_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='folio_petition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio de la solicitud'),
        ),
    ]
