# Generated by Django 4.1.6 on 2024-03-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0062_alter_petition_folio_petition'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='behavior',
            table='inai_behavior',
        ),
        migrations.AlterModelTable(
            name='crossingsheet',
            table='inai_crossingsheet',
        ),
        migrations.AlterModelTable(
            name='datafile',
            table='inai_datafile',
        ),
        migrations.AlterModelTable(
            name='entityweek',
            table='inai_entityweek',
        ),
        migrations.AlterModelTable(
            name='lapsheet',
            table='inai_lapsheet',
        ),
        migrations.AlterModelTable(
            name='replyfile',
            table='inai_replyfile',
        ),
        migrations.AlterModelTable(
            name='sheetfile',
            table='inai_sheetfile',
        ),
        migrations.AlterModelTable(
            name='tablefile',
            table='inai_tablefile',
        ),
    ]
