# Generated by Django 4.1.6 on 2023-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0062_datafile_file_type_replyfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefile',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
