# Generated by Django 4.1.6 on 2023-03-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0008_alter_taskfunction_options_alter_stage_main_function'),
        ('inai', '0063_tablefile_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='status',
            field=models.ForeignKey(blank=True, default='initial', null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask', verbose_name='Status actual'),
        ),
    ]
