# Generated by Django 4.1.6 on 2023-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0064_alter_datafile_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablefile',
            options={'ordering': ['id'], 'verbose_name': 'Archivo csv', 'verbose_name_plural': 'Archivos csv'},
        ),
        migrations.AddField(
            model_name='datafile',
            name='warnings',
            field=models.JSONField(blank=True, null=True, verbose_name='Advertencias'),
        ),
    ]
