# Generated by Django 4.1.6 on 2024-03-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_alter_asynctask_data_file_alter_asynctask_reply_file_and_more'),
        ('inai', '0064_remove_crossingsheet_entity_month_and_more'),
        ('formula', '0018_alter_missingrow_sheet_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFile',
        ),
        migrations.DeleteModel(
            name='LapSheet',
        ),
        migrations.DeleteModel(
            name='ReplyFile',
        ),
        migrations.DeleteModel(
            name='SheetFile',
        ),
        migrations.DeleteModel(
            name='TableFile',
        ),
    ]
