# Generated by Django 4.1.6 on 2023-03-31 01:50

from django.db import migrations, models
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0065_alter_tablefile_options_datafile_warnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=inai.models.set_upload_path)),
                ('matched', models.BooleanField(blank=True, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_data', models.JSONField(blank=True, default=inai.models.default_explore_data, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('completed_rows', models.IntegerField(default=0)),
                ('inserted_rows', models.IntegerField(default=0)),
                ('all_results', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Archivo csv',
                'verbose_name_plural': 'Archivos csv',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tablefile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='file_type',
        ),
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['-id'], 'verbose_name': 'Archivo con datos', 'verbose_name_plural': 'Archivos con datos'},
        ),
    ]
