# Generated by Django 4.1.6 on 2024-03-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_entity_has_indirect_entity_is_indirect'),
        ('inai', '0065_delete_datafile_delete_lapsheet_delete_replyfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('variable_type', models.CharField(choices=[('string', 'String'), ('date', 'Date')], default='string', max_length=10)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Variable de plantilla',
                'verbose_name_plural': 'Variables de plantilla',
            },
        ),
        migrations.CreateModel(
            name='RequestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('text', models.TextField()),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_templates', to='geo.entity')),
            ],
            options={
                'verbose_name': 'Plantilla de solicitud',
                'verbose_name_plural': 'Plantillas de solicitud',
            },
        ),
    ]
