# Generated by Django 4.1.6 on 2023-03-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0066_sheetfile_alter_tablefile_unique_together_and_more'),
        ('formula', '0020_missingrow_sheet_file'),
        ('task', '0018_remove_asynctask_table_file_asynctask_sheet_file'),
        ('category', '0032_remove_filetype_id_alter_filetype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableFile',
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_files', to='inai.datafile'),
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype'),
        ),
        migrations.AlterUniqueTogether(
            name='sheetfile',
            unique_together={('data_file', 'sheet_name', 'file_type')},
        ),
    ]
