# Generated by Django 4.1.6 on 2024-03-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0067_variable_request_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttemplate',
            options={'ordering': ['-version'], 'verbose_name': 'Plantilla de solicitud', 'verbose_name_plural': 'Plantillas de solicitud'},
        ),
    ]
