# Generated by Django 4.1.6 on 2023-03-31 15:37

from django.db import migrations, models
import django.db.models.deletion
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0032_remove_filetype_id_alter_filetype_name'),
        ('inai', '0067_delete_tablefile_sheetfile_data_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='last_lap_inserted',
            field=models.SmallIntegerField(default=-1, verbose_name='Última vuelta insertada'),
        ),
        migrations.CreateModel(
            name='TableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=inai.models.set_upload_path)),
                ('lap', models.IntegerField(default=0)),
                ('rows_count', models.IntegerField(default=0)),
                ('inserted', models.BooleanField(blank=True, null=True)),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype')),
                ('sheet_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_files', to='inai.sheetfile')),
            ],
            options={
                'verbose_name': 'Archivo para insertar',
                'verbose_name_plural': 'Archivos para insertar',
                'ordering': ['id'],
                'unique_together': {('sheet_file', 'file_type', 'lap')},
            },
        ),
    ]
