# Generated by Django 4.1.6 on 2024-03-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0068_alter_requesttemplate_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='real_entity',
            new_name='real_provider',
        ),
    ]
