# Generated by Django 4.1.6 on 2023-04-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0037_remove_finalfield_for_matching_collection_cat_params_and_more'),
        ('inai', '0068_datafile_last_lap_inserted_tablefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetfile',
            old_name='is_valid',
            new_name='valid_insert',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='last_lap_inserted',
        ),
        migrations.RemoveField(
            model_name='sheetfile',
            name='all_results',
        ),
        migrations.RemoveField(
            model_name='sheetfile',
            name='completed_rows',
        ),
        migrations.RemoveField(
            model_name='sheetfile',
            name='inserted_rows',
        ),
        migrations.AddField(
            model_name='tablefile',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.collection'),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='is_for_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LapSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField(default=0)),
                ('inserted', models.BooleanField(default=False)),
                ('general_error', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription_count', models.IntegerField(default=0)),
                ('drug_count', models.IntegerField(default=0)),
                ('missing_rows', models.IntegerField(default=0)),
                ('missing_fields', models.IntegerField(default=0)),
                ('row_errors', models.JSONField(blank=True, null=True)),
                ('field_errors', models.JSONField(blank=True, null=True)),
                ('sheet_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_sheet_files', to='inai.sheetfile')),
            ],
            options={
                'verbose_name': 'Lap de archivo csv',
                'verbose_name_plural': 'Laps de archivo csv',
                'ordering': ['id'],
                'unique_together': {('sheet_file', 'lap')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tablefile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tablefile',
            name='lap_sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='table_files', to='inai.lapsheet'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tablefile',
            unique_together={('lap_sheet', 'collection', 'is_for_edition')},
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='inserted',
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='lap',
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='rows_count',
        ),
        migrations.RemoveField(
            model_name='tablefile',
            name='sheet_file',
        ),
    ]
