# Generated by Django 4.1.6 on 2024-03-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_rename_entity_agency_provider_and_more'),
        ('inai', '0069_rename_real_entity_petition_real_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitymonth',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='entityweek',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='requesttemplate',
            old_name='entity',
            new_name='provider',
        ),
        migrations.AlterUniqueTogether(
            name='entityweek',
            unique_together={('provider', 'year_week', 'iso_delegation', 'year_month')},
        ),
    ]
