# Generated by Django 4.1.6 on 2023-04-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0032_remove_filetype_id_alter_filetype_name'),
        ('catalog', '0038_rename_entity_agency'),
        ('classify_task', '0012_alter_taskfunction_model_name'),
        ('inai', '0069_rename_is_valid_sheetfile_valid_insert_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthEntity',
            new_name='MonthAgency',
        ),
        migrations.AlterModelOptions(
            name='petitionmonth',
            options={'get_latest_by': 'month_agency__year_month', 'verbose_name': 'Mes de peticion', 'verbose_name_plural': 'Meses de peticion'},
        ),
        migrations.RenameField(
            model_name='monthagency',
            old_name='entity',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='entity',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='petitionmonth',
            old_name='month_entity',
            new_name='month_agency',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='csv_file',
        ),
        migrations.AlterField(
            model_name='datafile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask', verbose_name='Status actual'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='status_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol'),
        ),
        migrations.AlterField(
            model_name='lapsheet',
            name='sheet_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='inai.sheetfile'),
        ),
        migrations.AlterField(
            model_name='replyfile',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.filetype'),
        ),
    ]
