# Generated by Django 4.1.6 on 2023-04-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0070_rename_monthentity_monthagency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapsheet',
            name='discarded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lapsheet',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
