# Generated by Django 4.1.6 on 2024-03-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_rename_entity_asynctask_provider_and_more'),
        ('formula', '0019_rename_entity_matdrugextended_provider_and_more'),
        ('respond', '0002_rename_entity_datafile_provider_and_more'),
        ('classify_task', '0018_alter_stage_stage_group_and_more'),
        ('geo', '0018_rename_entity_agency_provider_and_more'),
        ('mat', '0004_delete_motherdrugextended'),
        ('inai', '0070_rename_entity_entitymonth_provider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityMonth',
            new_name='MonthRecord',
        ),
        migrations.RenameModel(
            old_name='EntityWeek',
            new_name='WeekRecord',
        ),
    ]
