# Generated by Django 4.1.6 on 2024-03-26 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_rename_entity_agency_provider_and_more'),
        ('inai', '0071_rename_entitymonth_monthrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='entity_months',
            new_name='month_records',
        ),
        migrations.RenameField(
            model_name='petitionmonth',
            old_name='entity_month',
            new_name='month_record',
        ),
        migrations.RenameField(
            model_name='weekrecord',
            old_name='entity_month',
            new_name='month_record',
        ),
        migrations.AlterField(
            model_name='monthrecord',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_records', to='geo.provider', verbose_name='Proveedor de servicios de salud'),
        ),
        migrations.AlterModelTable(
            name='monthrecord',
            table='inai_entitymonth',
        ),
    ]
