# Generated by Django 4.1.6 on 2023-04-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0071_lapsheet_discarded_count_lapsheet_total_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['-id'], 'verbose_name': 'Archivo con datos', 'verbose_name_plural': '3. Archivos con datos'},
        ),
        migrations.AlterModelOptions(
            name='lapsheet',
            options={'ordering': ['id'], 'verbose_name': 'Lap de archivo csv', 'verbose_name_plural': '5. Laps de archivo csv'},
        ),
        migrations.AlterModelOptions(
            name='petition',
            options={'verbose_name': 'Solicitud - Petición', 'verbose_name_plural': '1. Solicitudes (Peticiones)'},
        ),
        migrations.AlterModelOptions(
            name='petitionfilecontrol',
            options={'verbose_name': 'Relacional: petición -- Grupo de Control', 'verbose_name_plural': '7. Relacional: Petición -- Grupos de Control'},
        ),
        migrations.AlterModelOptions(
            name='replyfile',
            options={'verbose_name': 'Archivo sin datos finales', 'verbose_name_plural': '2. Archivos sin datos finales'},
        ),
        migrations.AlterModelOptions(
            name='sheetfile',
            options={'ordering': ['id'], 'verbose_name': 'Archivo csv', 'verbose_name_plural': '4. Archivos csv'},
        ),
        migrations.AlterModelOptions(
            name='tablefile',
            options={'ordering': ['id'], 'verbose_name': 'Archivo para insertar', 'verbose_name_plural': '6. Archivos para insertar'},
        ),
    ]
