# Generated by Django 4.1.6 on 2023-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0072_alter_datafile_options_alter_lapsheet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapsheet',
            name='area_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lapsheet',
            name='diagnosis_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lapsheet',
            name='doctor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lapsheet',
            name='medical_unity_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lapsheet',
            name='medicament_count',
            field=models.IntegerField(default=0),
        ),
    ]
