# Generated by Django 4.1.6 on 2024-04-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0073_petition_template_text_alter_variable_variable_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='request_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='inai.requesttemplate'),
        ),
        migrations.AddField(
            model_name='petition',
            name='template_variables',
            field=models.JSONField(blank=True, null=True, verbose_name='Variables de la plantilla'),
        ),
    ]
