# Generated by Django 4.1.6 on 2023-04-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0073_lapsheet_area_count_lapsheet_diagnosis_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lapsheet',
            old_name='medical_unity_count',
            new_name='medical_unit_count',
        ),
    ]
