# Generated by Django 4.1.6 on 2023-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0074_rename_medical_unity_count_lapsheet_medical_unit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefile',
            name='inserted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lapsheet',
            name='inserted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
