# Generated by Django 4.1.6 on 2023-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0075_tablefile_inserted_alter_lapsheet_inserted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapsheet',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
