# Generated by Django 4.1.6 on 2024-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0075_alter_variable_variable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekrecord',
            name='big_denied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weekrecord',
            name='big_partial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_type',
            field=models.CharField(choices=[('string', 'String'), ('provider', 'By Provider'), ('date', 'Date')], default='string', max_length=15),
        ),
    ]
