# Generated by Django 4.1.6 on 2024-04-13 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0019_alter_taskfunction_group_queue_and_more'),
        ('inai', '0076_weekrecord_big_denied_weekrecord_big_partial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='months_verified',
            field=models.BooleanField(default=False, verbose_name='Meses verificados'),
        ),
        migrations.AlterField(
            model_name='monthrecord',
            name='stage',
            field=models.ForeignKey(default='init_month', on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa actual'),
        ),
    ]
