# Generated by Django 4.1.6 on 2023-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0076_lapsheet_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapsheet',
            name='processed_count',
            field=models.IntegerField(default=0),
        ),
    ]
