# Generated by Django 4.1.6 on 2024-04-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0019_alter_provider_options_provider_variables'),
        ('inai', '0077_petition_months_verified_alter_monthrecord_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttemplate',
            options={'ordering': ['-version'], 'verbose_name': 'Plantilla de solicitud', 'verbose_name_plural': 'CAT. Plantillas de solicitud'},
        ),
        migrations.AddField(
            model_name='requesttemplate',
            name='version_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requesttemplate',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_templates', to='geo.provider', verbose_name='Proveedor'),
        ),
    ]
