# Generated by Django 4.1.6 on 2023-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0077_lapsheet_processed_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetfile',
            name='valid_insert',
        ),
        migrations.AddField(
            model_name='lapsheet',
            name='valid_insert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lapsheet',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
