# Generated by Django 4.1.6 on 2024-05-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0078_alter_requesttemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesttemplate',
            options={'ordering': ['-id'], 'verbose_name': 'Plantilla de solicitud', 'verbose_name_plural': 'CAT. Plantillas de solicitud'},
        ),
    ]
