# Generated by Django 4.1.6 on 2023-04-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0078_remove_sheetfile_valid_insert_lapsheet_valid_insert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablefile',
            name='inserted',
        ),
    ]
