# Generated by Django 4.1.6 on 2024-05-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_datebreak_group_alter_filetype_group_and_more'),
        ('inai', '0079_alter_requesttemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='status_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions_priority', to='category.statuscontrol', verbose_name='Status de prioridad'),
        ),
    ]
