# Generated by Django 4.1.6 on 2023-04-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0012_alter_taskfunction_model_name'),
        ('inai', '0079_remove_tablefile_inserted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetfile',
            name='error_process',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='stage',
            field=models.ForeignKey(blank=True, default='initial', null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa actual'),
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask'),
        ),
        migrations.AddField(
            model_name='sheetfile',
            name='warnings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='stage',
            field=models.ForeignKey(blank=True, default='initial', null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa actual'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='status',
            field=models.ForeignKey(blank=True, default='finished', null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask', verbose_name='Status actual'),
        ),
    ]
