# Generated by Django 4.1.6 on 2023-04-22 23:44

from django.db import migrations, models
import django.db.models.deletion
import inai.models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0012_alter_taskfunction_model_name'),
        ('inai', '0080_sheetfile_error_process_sheetfile_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitionmonth',
            options={'get_latest_by': 'month_agency__year_month', 'verbose_name': 'Mes de solicitud', 'verbose_name_plural': 'Meses de solicitud'},
        ),
        migrations.AlterField(
            model_name='petition',
            name='info_queja_inai',
            field=models.JSONField(blank=True, help_text='Información de la queja en INAI Search', null=True, verbose_name='Datos de queja'),
        ),
        migrations.AlterField(
            model_name='replyfile',
            name='file',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=inai.models.set_upload_path, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='sheetfile',
            name='stage',
            field=models.ForeignKey(default='explore', on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa actual'),
        ),
        migrations.AlterField(
            model_name='sheetfile',
            name='status',
            field=models.ForeignKey(default='finished', on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask'),
        ),
    ]
