# Generated by Django 4.1.6 on 2024-05-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0080_petition_status_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='status_complain',
            new_name='old_status_complain',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='status_data',
            new_name='old_status_data',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='status_petition',
            new_name='old_status_petition',
        ),
    ]
