# Generated by Django 4.1.6 on 2024-05-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_statuscontrol'),
        ('inai', '0081_rename_status_complain_petition_old_status_complain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='new_status_complain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions_complain', to='category.statuscontrol', verbose_name='Status de la queja'),
        ),
        migrations.AddField(
            model_name='petition',
            name='new_status_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions_data', to='category.statuscontrol', verbose_name='Status de los datos entregados'),
        ),
        migrations.AddField(
            model_name='petition',
            name='new_status_petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions_petition', to='category.statuscontrol', verbose_name='Status de la petición'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions_priority', to='category.statuscontrol', verbose_name='Status de prioridad'),
        ),
    ]
