# Generated by Django 4.1.6 on 2024-05-04 19:16

from django.db import migrations, models


def copy_old_values(apps, schema_editor):
    OldStatusControl = apps.get_model("category", "OldStatusControl")
    Petition = apps.get_model("inai", "Petition")
    for old_status in OldStatusControl.objects.all():
        Petition.objects.filter(old_status_complain=old_status)\
                .update(new_status_complain=old_status.name)
        Petition.objects.filter(old_status_data=old_status)\
                .update(new_status_data=old_status.name)
        Petition.objects.filter(old_status_petition=old_status)\
                .update(new_status_petition=old_status.name)


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0082_petition_new_status_complain_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_old_values),
    ]
