# Generated by Django 4.1.6 on 2024-05-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0082_petition_new_status_complain_and_more'),
    ]

    operations = [
    ]
