# Generated by Django 4.1.6 on 2024-05-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0083_artificial_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='new_status_complain',
            new_name='status_complain',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='new_status_data',
            new_name='status_data',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='new_status_petition',
            new_name='status_petition',
        ),
    ]
