# Generated by Django 4.1.6 on 2024-05-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0084_rename_new_status_complain_petition_status_complain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='old_status_complain',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='old_status_data',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='old_status_petition',
        ),
    ]
