# Generated by Django 4.1.6 on 2024-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0085_remove_petition_old_status_complain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='reasons_verified',
            field=models.BooleanField(default=False, verbose_name='Razones verificadas'),
        ),
        migrations.AddField(
            model_name='petition',
            name='reply_files_verified',
            field=models.BooleanField(default=False, verbose_name='Archivos de respuesta verificados'),
        ),
        migrations.AddField(
            model_name='petition',
            name='response_limit',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de respuesta'),
        ),
    ]
