# Generated by Django 4.1.6 on 2024-05-17 19:42

from django.db import migrations, models
import django.db.models.deletion


def recover_complain_data(apps, schema_editor):
    Petition = apps.get_model("inai", "Petition")
    Complaint = apps.get_model("inai", "Complaint")
    for petition in Petition.objects.filter(info_queja_inai__isnull=False):
        json_data = petition.info_queja_inai
        folio_complaint = json_data.get("EXPEDIENTE")
        complaint = Complaint.objects.create(
            petition=petition,
            folio_complaint=folio_complaint,
            info_queja_inai=json_data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_alter_statuscontrol_options'),
        ('inai', '0086_petition_reasons_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='ask_extension',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='description_complain',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='folio_complain',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='status_complain',
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_extension', models.BooleanField(blank=True, null=True, verbose_name='Se solicitó extensión')),
                ('folio_complaint', models.CharField(blank=True, max_length=50, null=True, verbose_name='Expediente')),
                ('info_queja_inai', models.JSONField(blank=True, help_text='Información de la queja en INAI Search', null=True, verbose_name='Datos de queja')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Texto de la queja')),
                ('date_complaint', models.DateField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('relevant_data', models.JSONField(blank=True, help_text='Datos relevantes de la queja', null=True, verbose_name='Datos relevantes')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='inai.petition')),
                ('status_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='category.statuscontrol')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': '2. Quejas',
            },
        ),
        migrations.RunPython(recover_complain_data),
    ]
