# Generated by Django 4.1.6 on 2024-05-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0087_remove_petition_ask_extension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='ask_extension',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='info_queja_inai',
        ),
    ]
