# Generated by Django 4.1.6 on 2024-06-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0089_monthrecord_last_behavior_deliveredweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetitionMonth',
        ),
    ]
