# Generated by Django 4.1.6 on 2024-06-19 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0007_alter_operation_options'),
        ('inai', '0090_delete_petitionmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthrecord',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rds.cluster'),
        ),
    ]
