# Generated by Django 4.1.6 on 2024-07-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0091_monthrecord_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesttemplate',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
