# Generated by Django 4.1.6 on 2024-07-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_alter_statuscontrol_options'),
        ('data_param', '0023_delete_olddatagroup'),
        ('inai', '0092_requesttemplate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttemplate',
            name='data_groups',
            field=models.ManyToManyField(blank=True, to='data_param.datagroup', verbose_name='Grupos de datos'),
        ),
        migrations.CreateModel(
            name='PetitionDataGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='data_param.datagroup')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_groups', to='inai.petition')),
                ('status_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_data_groups_data', to='category.statuscontrol')),
            ],
            options={
                'verbose_name': 'Petición - Grupo de datos (m2m)',
                'verbose_name_plural': 'Peticiones - Grupos de datos (m2m)',
            },
        ),
    ]
