# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-03 19:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.BooleanField(verbose_name='Medicamento')),
                ('supply', models.BooleanField(verbose_name='Insumo')),
                ('medication_name', models.CharField(max_length=255, verbose_name='Nombre de medicamento / insumo faltante')),
                ('institution', models.CharField(choices=[('INSABI', 'INSABI'), ('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('PEMEX', 'PEMEX'), ('SEDENA', 'SEDENA'), ('SEMAR', 'SEMAR'), ('OTRA', 'OTRA')], max_length=20, verbose_name='Instituci\xf3n')),
                ('hospital_name', models.CharField(max_length=255, verbose_name='\xbfHospital o Cl\xednica?')),
                ('corruption', models.CharField(choices=[('si', 'SI'), ('no', 'NO')], max_length=2, verbose_name='\xbfConsideras que es un caso de corrupci\xf3n')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Correo de contacto (opcional)')),
                ('phone', models.CharField(max_length=255, verbose_name='N\xfamero de contacto (opcional)')),
                ('type', models.CharField(choices=[('paciente', 'Paciente'), ('profesional', 'Profesional')], max_length=20)),
                ('register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=2, verbose_name='Clave INEGI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Corto')),
                ('code_name', models.CharField(blank=True, max_length=6, null=True, verbose_name='Nombre Clave')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.State', verbose_name='Estado'),
        ),
    ]
