# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-03 19:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo de contacto (opcional)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N\xfamero de contacto (opcional)'),
        ),
    ]
