# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-03 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0002_auto_20200303_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='register',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='type',
            new_name='informer_type',
        ),
        migrations.AddField(
            model_name='report',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='origin_app',
            field=models.CharField(default='Yeeko', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='corruption',
            field=models.NullBooleanField(verbose_name='\xbfConsideras que es un caso de corrupci\xf3n'),
        ),
        migrations.AlterField(
            model_name='report',
            name='institution',
            field=models.CharField(max_length=20, verbose_name='Instituci\xf3n'),
        ),
    ]
