# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0003_auto_20200303_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='corruption',
            new_name='has_corruption',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='informer_name',
        ),
        migrations.AddField(
            model_name='report',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
