# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-10 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0004_auto_20200303_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='corruption_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
