# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-10 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0005_report_corruption_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
