# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-11 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0006_report_incident_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='report',
            name='supply',
        ),
        migrations.AddField(
            model_name='report',
            name='disease',
            field=models.TextField(blank=True, null=True, verbose_name='Padecimiento'),
        ),
        migrations.AddField(
            model_name='report',
            name='medicine_type',
            field=models.CharField(choices=[('medicamento', 'Medicamento'), ('vacuna', 'Vacuna'), ('material', 'Material de curaci\xf3n'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo de medicina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='informer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='report',
            name='medication_name',
            field=models.CharField(max_length=255, verbose_name='Nombre de medicamento / Insumo faltante'),
        ),
    ]
