# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-11 18:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0007_auto_20200311_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='corruption_description',
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo de contacto'),
        ),
        migrations.AlterField(
            model_name='report',
            name='has_corruption',
            field=models.BooleanField(verbose_name='\xbfIncluy\xf3 corrupci\xf3n?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hospital_name',
            field=models.CharField(max_length=255, verbose_name='Nombre de hospital o cl\xednica'),
        ),
        migrations.AlterField(
            model_name='report',
            name='informer_type',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('profesional', 'Profesional')], max_length=20, verbose_name='Tipo de Informante'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_other',
            field=models.BooleanField(default=False, verbose_name='Es otra instituci\xf3n'),
        ),
        migrations.AlterField(
            model_name='report',
            name='narration',
            field=models.TextField(blank=True, null=True, verbose_name='Relato de la corrupci\xf3n'),
        ),
        migrations.AlterField(
            model_name='report',
            name='origin_app',
            field=models.CharField(default='Yeeko', max_length=100, verbose_name='Aplicacion'),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='N\xfamero de contacto'),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.State', verbose_name='Entidad'),
        ),
    ]
