# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0008_auto_20200311_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='institution',
            field=models.CharField(max_length=255, verbose_name='Instituci\xf3n'),
        ),
    ]
