# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-08 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0009_auto_20200312_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLUES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='NOMBRE DE LA UNIDAD')),
                ('municipality', models.CharField(max_length=255, verbose_name='NOMBRE DEL MUNICIPIO')),
                ('municipality_inegi_code', models.CharField(max_length=3, verbose_name='CLAVE DEL MUNICIPIO')),
                ('tipology', models.CharField(max_length=255, verbose_name='NOMBRE DE TIPOLOGIA')),
                ('tipology_cve', models.CharField(max_length=5, verbose_name='CLAVE DE TIPOLOGIA')),
                ('id_clues', models.CharField(max_length=10, verbose_name='ID_CLUES')),
                ('clues', models.CharField(max_length=20, verbose_name='CLUES')),
                ('status_operation', models.CharField(max_length=80, verbose_name='ESTATUS DE OPERACION')),
                ('longitude', models.CharField(max_length=20, verbose_name='LONGITUD')),
                ('latitude', models.CharField(max_length=20, verbose_name='LATITUD')),
                ('locality', models.CharField(max_length=80, verbose_name='NOMBRE DE LA LOCALIDAD')),
                ('locality_inegi_code', models.CharField(max_length=5, verbose_name='CLAVE DE LA LOCALIDAD')),
                ('jurisdiction', models.CharField(max_length=80, verbose_name='NOMBRE DE LA JURISDICCION')),
                ('jurisdiction_clave', models.CharField(max_length=5, verbose_name='CLAVE DE LA JURISDICCION')),
                ('establishment_type', models.CharField(max_length=80, verbose_name='NOMBRE TIPO ESTABLECIMIENTO')),
                ('consultings_general', models.IntegerField(verbose_name='CONSULTORIOS DE MED GRAL')),
                ('consultings_other', models.IntegerField(verbose_name='CONSULTORIOS EN OTRAS AREAS')),
                ('beds_hopital', models.IntegerField(verbose_name='CAMAS EN AREA DE HOS')),
                ('beds_other', models.IntegerField(verbose_name='CAMAS EN OTRAS AREAS')),
                ('total_unities', models.IntegerField(verbose_name='UNIDADES TOTALES (SUMA)')),
                ('admin_institution', models.CharField(max_length=80, verbose_name='NOMBRE DE LA INS ADM')),
                ('atention_level', models.CharField(max_length=80, verbose_name='NIVEL ATENCION')),
                ('stratum', models.CharField(max_length=80, verbose_name='ESTRATO UNIDAD')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='NOMBRE DE LA INSTITUCION')),
                ('code', models.CharField(max_length=20, verbose_name='CLAVE DE LA INSTITUCION')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('position', models.CharField(max_length=255, verbose_name='Cargo o posici\xf3n')),
                ('emails', models.CharField(max_length=255, verbose_name='Correos electronicos')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Medicamento')),
                ('medicine_name_raw', models.CharField(max_length=255, verbose_name='Nombre reportado del medicamento')),
                ('medicine_real_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre real del medicamento')),
            ],
            options={
                'verbose_name': 'Suministro Medico',
                'verbose_name_plural': 'Suministros Medicos',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de hospital o cl\xednica'),
        ),
        migrations.AlterField(
            model_name='report',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituci\xf3n'),
        ),
        migrations.AlterField(
            model_name='report',
            name='medicine_type',
            field=models.CharField(max_length=30, verbose_name='Tipo de medicina'),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.State', verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='supply',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.Report'),
        ),
        migrations.AddField(
            model_name='clues',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.Institution'),
        ),
        migrations.AddField(
            model_name='clues',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.State'),
        ),
        migrations.AddField(
            model_name='report',
            name='clues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.CLUES'),
        ),
        migrations.AddField(
            model_name='report',
            name='institution_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.Institution', verbose_name='Instituci\xf3n'),
        ),
    ]
