# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-08 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0010_auto_20200407_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='hospital_name',
            new_name='hospital_name_raw',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='institution',
            new_name='institution_raw',
        ),
    ]
