# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-08 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0012_auto_20200407_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='medication_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de medicamento / Insumo faltante'),
        ),
        migrations.AlterField(
            model_name='report',
            name='medicine_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de medicina'),
        ),
    ]
