# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0013_auto_20200408_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='validated',
            field=models.BooleanField(default=True),
        ),
    ]
