# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-08 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0015_auto_20200408_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='public_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CLAVE PUBLICA DE LA INSTITUCION'),
        ),
        migrations.AddField(
            model_name='institution',
            name='public_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NOMBRE PUBLICO DE LA INSTITUCION'),
        ),
    ]
