# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0017_auto_20200420_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='is_searchable',
            field=models.BooleanField(default=False, verbose_name='Puede buscarse por el usuario'),
        ),
    ]
