# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-10 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0018_clues_is_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='relevance',
            field=models.IntegerField(default=2, verbose_name='Relevancia (Para filtros)'),
        ),
    ]
