# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0019_institution_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='alter_clasifs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='clasificaciones alternativas'),
        ),
        migrations.AddField(
            model_name='clues',
            name='clasif_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre completo tipo'),
        ),
        migrations.AddField(
            model_name='clues',
            name='number_unity',
            field=models.IntegerField(blank=True, null=True, verbose_name='N\xfamero de unidad'),
        ),
        migrations.AddField(
            model_name='clues',
            name='prev_clasif_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre corto tipo'),
        ),
        migrations.AddField(
            model_name='clues',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Limpiado'),
        ),
    ]
