# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-14 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0020_auto_20200511_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='number_unity',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='N\xfamero de unidad'),
        ),
    ]
