# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-15 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0021_auto_20200514_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='tipology_cve',
            field=models.CharField(max_length=12, verbose_name='CLAVE DE TIPOLOGIA'),
        ),
    ]
