# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-18 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0022_auto_20200515_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='trimester',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trimestre'),
        ),
    ]
