# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-18 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0023_report_trimester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='trimester',
        ),
    ]
