# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-06-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0024_remove_report_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='other_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
