# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-01-21 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desabasto', '0025_state_other_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres alternativos y comerciales')),
                ('presentation_count', models.IntegerField(default=1)),
                ('is_relevant', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('official_name', models.TextField()),
                ('official_attributes', models.TextField(blank=True, null=True)),
                ('short_attributes', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.Component')),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
            },
        ),
        migrations.CreateModel(
            name='TestimonyMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='cero_desabasto')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TestimonyMedia',
                'verbose_name_plural': 'TestimonyMedias',
            },
        ),
        migrations.AddField(
            model_name='clues',
            name='is_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='testimony',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='validated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='want_litigation',
            field=models.BooleanField(verbose_name='\xbfPermite contacto para litigio?'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='clues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.CLUES'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='responsible'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.State'),
        ),
        migrations.AddField(
            model_name='supply',
            name='presentation_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='validated',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='desabasto.Institution'),
        ),
        migrations.AddField(
            model_name='testimonymedia',
            name='repost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.Report'),
        ),
        migrations.AddField(
            model_name='supply',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.Component'),
        ),
        migrations.AddField(
            model_name='supply',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.Presentation'),
        ),
    ]
