# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-01-21 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0027_report_public_testimony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonymedia',
            old_name='repost',
            new_name='report',
        ),
    ]
