# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-01-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0028_auto_20210121_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sent_email',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='report',
            name='sent_responsible',
            field=models.BooleanField(),
        ),
    ]
