# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-01-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0029_auto_20210121_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key', models.CharField(max_length=20, verbose_name='Clave')),
                ('is_current', models.BooleanField(default=True)),
                ('short_name', models.TextField()),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='PresentationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_count', models.IntegerField(default=0)),
                ('agrupated_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.PresentationType')),
            ],
            options={
                'verbose_name': 'PresentationType',
                'verbose_name_plural': 'PresentationTypes',
            },
        ),
        migrations.RemoveField(
            model_name='component',
            name='is_relevant',
        ),
        migrations.AddField(
            model_name='component',
            name='presentations_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='desabasto.Component'),
        ),
        migrations.AlterField(
            model_name='testimonymedia',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies_media', to='desabasto.Report'),
        ),
        migrations.AddField(
            model_name='container',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.Presentation'),
        ),
        migrations.AddField(
            model_name='component',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.Group'),
        ),
    ]
