# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-01-26 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0030_auto_20210126_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationtype',
            name='agrupated_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.PresentationType'),
        ),
    ]
