# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-01-26 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0032_auto_20210126_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='session_ga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
