# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0033_report_session_ga'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='origen_cvmei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='origen_cvmei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='origen_cvmei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentationtype',
            name='origen_cvmei',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='clues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='desabasto.CLUES'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='desabasto.State'),
        ),
    ]
