# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0034_auto_20210224_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentationtype',
            options={'ordering': ['name'], 'verbose_name': 'PresentationType', 'verbose_name_plural': 'PresentationTypes'},
        ),
        migrations.AddField(
            model_name='presentation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.Group'),
        ),
    ]
