# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-02-27 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0035_auto_20210225_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_relevant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clues',
            name='is_searchable',
            field=models.BooleanField(default=False, help_text='Puede buscarse por el usuario', verbose_name='ACtivo'),
        ),
    ]
