# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0038_auto_20210309_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='container',
        ),
        migrations.AddField(
            model_name='component',
            name='is_vaccine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supply',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.Presentation'),
        ),
    ]
