# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-09 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0039_auto_20210309_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('page_url', models.CharField(blank=True, max_length=180, null=True)),
                ('logo', models.FileField(upload_to=b'')),
                ('level', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Alliances',
                'verbose_name_plural': 'Alliances',
            },
        ),
    ]
