# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0040_alliances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='validator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
