# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0041_auto_20210317_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'DocumentType',
                'verbose_name_plural': 'DocumentTypes',
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('clave_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medico', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Medic',
                'verbose_name_plural': 'Medics',
            },
        ),
        migrations.CreateModel(
            name='MedicalSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MedicalSpeciality',
                'verbose_name_plural': 'MedicalSpecialitys',
            },
        ),
        migrations.CreateModel(
            name='RecipeMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_ref', models.TextField(blank=True, null=True)),
                ('cantidad_prescrita', models.IntegerField()),
                ('cantidad_entregada', models.IntegerField()),
                ('precio_medicamento', models.FloatField()),
                ('rn', models.CharField(max_length=10)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.Container')),
            ],
            options={
                'verbose_name': 'RecipeItem',
                'verbose_name_plural': 'RecipeItems',
            },
        ),
        migrations.CreateModel(
            name='RecipeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.IntegerField()),
                ('lost_ref', models.TextField(blank=True, null=True)),
                ('folio_documento', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('delivered', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'RecipeReport',
                'verbose_name_plural': 'RecipeReports',
            },
        ),
        migrations.AddField(
            model_name='clues',
            name='name_in_issten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NOMBRE DE LA UNIDAD'),
        ),
        migrations.AddField(
            model_name='recipereport',
            name='clues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.CLUES'),
        ),
        migrations.AddField(
            model_name='recipereport',
            name='especialidad_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.MedicalSpeciality'),
        ),
        migrations.AddField(
            model_name='recipereport',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.Medic'),
        ),
        migrations.AddField(
            model_name='recipereport',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.DocumentType'),
        ),
        migrations.AddField(
            model_name='recipemedicine',
            name='recipereport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.RecipeReport'),
        ),
        migrations.AddField(
            model_name='medic',
            name='especialidad_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.MedicalSpeciality'),
        ),
    ]
