# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0042_auto_20210318_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemedicine',
            name='fecha_emision',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='recipemedicine',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='key',
            field=models.CharField(max_length=20, verbose_name='Clave sin puntos'),
        ),
        migrations.AlterField(
            model_name='recipereport',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
