# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0043_auto_20210318_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='key2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave sin puntos'),
        ),
        migrations.AlterField(
            model_name='container',
            name='key',
            field=models.CharField(max_length=20, verbose_name='Clave'),
        ),
    ]
