# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0045_auto_20210318_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipereport',
            name='especialidad_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.MedicalSpeciality'),
        ),
    ]
