# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0046_auto_20210318_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemedicine',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipereport',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
