# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-20 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0047_auto_20210319_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeReportRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegacion', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_presupuestal', models.CharField(blank=True, max_length=20, null=True)),
                ('unidad_medica', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_unidad_med', models.CharField(blank=True, max_length=10, null=True)),
                ('nivel_atencion', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('folio_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_medicamento', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_medicamento', models.TextField(blank=True, null=True)),
                ('cantidad_prescrita', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad_entregada', models.CharField(blank=True, max_length=10, null=True)),
                ('clave_medico', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_medico', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad_medico', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_medicamento', models.CharField(blank=True, max_length=50, null=True)),
                ('rn', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'RecipeReportRaw',
                'verbose_name_plural': 'RecipeReportRaws',
            },
        ),
    ]
