# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0048_recipereportraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
