# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-09-13 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0049_report_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(blank=True, max_length=30, null=True)),
                ('contrato', models.CharField(blank=True, max_length=30, null=True)),
                ('procedimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('partida_presupuestal', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc', models.CharField(blank=True, max_length=15, null=True)),
                ('preveedor', models.TextField(blank=True, null=True)),
                ('expedition_date', models.CharField(blank=True, max_length=10, null=True)),
                ('deliver_date', models.CharField(blank=True, max_length=10, null=True)),
                ('warehouse', models.TextField(blank=True, null=True)),
                ('adress_warehouse', models.TextField(blank=True, null=True)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('clave_insumo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('clues', models.TextField(blank=True, null=True)),
                ('entidad', models.CharField(blank=True, max_length=80, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Suministro',
                'verbose_name_plural': 'Ordenes de Suministro',
            },
        ),
    ]
