# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-09-13 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0050_purchaseraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseraw',
            name='raw_pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
