# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-09-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0051_purchaseraw_raw_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseraw',
            name='contrato',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
