# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-10-01 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0052_auto_20210915_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Padecimiento',
                'verbose_name_plural': 'Padecimientos',
            },
        ),
        migrations.RenameField(
            model_name='report',
            old_name='disease',
            new_name='disease_raw',
        ),
        migrations.AddField(
            model_name='supply',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desabasto.Disease', verbose_name='Padecimiento'),
        ),
    ]
