# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-22 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0053_auto_20210930_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemedicine',
            name='container',
        ),
        migrations.RemoveField(
            model_name='recipemedicine',
            name='recipereport',
        ),
        migrations.RemoveField(
            model_name='recipereport',
            name='clues',
        ),
        migrations.RemoveField(
            model_name='recipereport',
            name='especialidad_medico',
        ),
        migrations.RemoveField(
            model_name='recipereport',
            name='medic',
        ),
        migrations.RemoveField(
            model_name='recipereport',
            name='tipo_documento',
        ),
        migrations.DeleteModel(
            name='RecipeMedicine',
        ),
        migrations.DeleteModel(
            name='RecipeReport',
        ),
    ]
