# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2022-01-08 23:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0055_auto_20211019_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='alternative_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clues',
            name='is_searchable',
            field=models.BooleanField(default=False, help_text='Puede buscarse por el usuario', verbose_name='Activo'),
        ),
    ]
