# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2022-01-09 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0056_auto_20220108_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemedicine2',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='recipemedicine2',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='recipemedicine2',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipereport2',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipereport2',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='folio_documento',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='recipereport2',
            name='folio_ocamis',
            field=models.CharField(default='--', max_length=48, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipereport2',
            name='iso_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipereport2',
            name='iso_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipereport2',
            name='iso_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipemedicine2',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desabasto.RecipeReport2'),
        ),
    ]
