# Generated by Django 2.2.25 on 2022-03-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0057_auto_20220108_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliances',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='clues',
            name='institution',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clues',
            name='state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medic',
            name='especialidad_medico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='component',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='presentation_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentationtype',
            name='agrupated_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipemedicine2',
            name='recipe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='clues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='delegacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='medico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipereport2',
            name='tipo_documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='clues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='institution',
            field=models.IntegerField(blank=True, null=True, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.IntegerField(blank=True, null=True, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='clues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='institution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='component',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='disease',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='report',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testimonymedia',
            name='report',
            field=models.IntegerField(),
        ),
    ]
