# Generated by Django 2.2.25 on 2022-03-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0058_auto_20220308_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alliances',
        ),
        migrations.DeleteModel(
            name='CLUES',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
