# Generated by Django 2.2.25 on 2022-03-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0059_auto_20220308_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
        migrations.DeleteModel(
            name='PresentationType',
        ),
    ]
