# Generated by Django 2.2.25 on 2022-03-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0060_auto_20220308_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
        migrations.DeleteModel(
            name='TestimonyMedia',
        ),
    ]
