# Generated by Django 2.2.25 on 2022-03-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desabasto', '0061_auto_20220308_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='Medic',
        ),
        migrations.DeleteModel(
            name='MedicalSpeciality',
        ),
        migrations.DeleteModel(
            name='RecipeMedicine2',
        ),
        migrations.DeleteModel(
            name='RecipeReport2',
        ),
        migrations.DeleteModel(
            name='RecipeReportLog',
        ),
    ]
