
SELECT DISTINCT
    UM.CVE_DELEGACION AS CLAVE_OOAD,
    NDI.NOM_DELEGACION_IMSS AS DELEGACION,
    UM.REF_UNIDAD_MEDICA AS UNIDAD_MEDICA,
    UM.CVE_PRESUPUESTAL AS PRESUPUESTAL,
    CASE
        WHEN UM.CVE_NIVEL_ATENCION = 3 THEN 'Tercer Nivel'
        ELSE 'Segundo Nivel'
    END AS NIVEL_ATENCION,
    NUMC.DES_TIPOLOGIA_UNIDAD AS TIPO_UNIDAD,
    NC10.DES_CIE10,
    NTP.DES_TIPO_PRESCRIPCION AS TIPO_DOCUMENTO,
    NPM.CVE_FOLIO_RECETA AS FOLIO_DOCUMENTO,
    NANM.STP_FECHA_ATENCION AS FECHA_CONSULTA,
    NPM.FEC_RECETA AS FECHA_EMISION_MEDICAMENTO,
    NPM.CVE_MEDICAMENTO AS CLAVE_MEDICAMENTO,
    NM.DES_MEDICAMENTO AS DESCRIPCIÓN_MEDICAMENTO,
    NPM.CAN_CANTIDAD AS CANTIDAD_PRESCRITA
FROM NET_PRESCRIPCION_MEDICAMENTO NPM
JOIN NEC_MEDICAMENTO NM ON NM.CVE_MEDICAMENTO = NPM.CVE_MEDICAMENTO
JOIN NET_ATENCION_NOTA_MEDICA NANM ON NANM.CVE_IDEE_FECHA_ATENCION = NPM.CVE_IDEE_FECHA_ATENCION
JOIN NET_PACIENTE NP ON NP.CVE_IDEE = NANM.CVE_IDEE
JOIN NET_UNIDAD_MEDICA UM ON UM.CVE_PRESUPUESTAL = NANM.CVE_UNIDAD_MEDICA
JOIN NEC_DELEGACION_IMSS NDI ON NDI.CVE_DELEGACION_IMSS = UM.CVE_DELEGACION
JOIN NET_ASIGNACION NA ON NA.REF_CEDULA = NANM.REF_CEDULA
JOIN NET_DIAGNOSTICO ND ON ND.CVE_IDEE_FECHA_ATENCION = NPM.CVE_IDEE_FECHA_ATENCION
JOIN NEC_UNIDAD_MEDICA_CLUES NUMC ON NUMC.CVE_UNIDAD_CLUES = UM.CVE_PRESUPUESTAL
JOIN NEC_TIPO_PRESCRIPCION NTP ON NTP.CVE_TIPO_PRESCRIPCION = NPM.CVE_CODIGO_TIPO_RECETA
JOIN NET_DIAGNOSTICO_TIPODX NDT ON NDT.CVE_IDEE_FECHA_ATENCION = NPM.CVE_IDEE_FECHA_ATENCION
JOIN NEC_CIE10 NC10 ON NC10.CVE_CIE10 = NDT.CVE_CIE10
WHERE
    NPM.FEC_RECETA >= TO_DATE('11/11/2023 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
    AND NPM.FEC_RECETA <= TO_DATE('20/11/2023 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
    AND NA.FEC_BAJA IS NULL
    AND NDT.CVE_TIPO_DIAGNOSTICO = 1
    AND NPM.FEC_CANCELACION IS NULL;


SELECT DISTINCT
    NDI.NOM_DELEGACION_IMSS AS DELEGACION,
    NEUM.CVE_PRESUPUESTAL AS PRESUPUESTAL,
    NEUM.REF_UNIDAD_MEDICA AS UNIDAD,
    NEUM.CVE_NIVEL_ATENCION AS NIVEL_ATENCION,
    NEUM.CVE_NIVEL_ATENCION AS TIPO_UNIDAD,
    CASE
        WHEN NPM.CVE_FOLIO_RECETA_RESURTIBLE IS NULL THEN 'NORMAL'
        ELSE 'RESURTIBLE'
    END AS TIPO_DOCUMENTO,
    NPM.CVE_FOLIO_RECETA AS FOLIO_DOCUMENTO,
    NEP.STP_EVENTO AS FECHA_CONSULTA,
    CIE10P.CVE_CIE10 AS CVE_DIAGNOSTICO,
    CIE10P.DES_CIE10 AS MOTIVO,
    NPM.FEC_RECETA AS FECHA_EMISION,
    NULL AS FECHA_ENTREGA,
    NECM.CVE_MEDICAMENTO AS CVE_MEDICAMENTO,
    NECM.DES_MEDICAMENTO AS DES_MEDICAMENTO,
    NPM.CAN_SURTIR AS CANTIDAD_PRESCRITA,
    NULL AS CANTIDAD_ENTREGADA,
    NPO.CVE_MATRICULA AS MATRICULA,
    NPO.REF_APELLIDO_PATERNO AS AP_PATERNO_MEDICO,
    NPO.REF_APELLIDO_MATERNO AS AP_MATERNO_MEDICO,
    NPO.REF_NOMBRE AS NOMBRE_MEDICO,
    NES.CVE_ESPECIALIDAD AS CVE_ESPECIALIDAD,
    NES.DES_ESPECIALIDAD AS DES_ESPECIALIDAD
FROM
    NET_PRESCRIPCION_MEDICAMENTO NPM
INNER JOIN NET_EVENTO_PRESCRIPCION NEP ON NPM.CVE_IDEE_FECHA_ATENCION = NEP.CVE_IDEE_FECHA_ATENCION
INNER JOIN NET_DIAGNOSTICO NDX ON NDX.CVE_IDEE_FECHA_ATENCION = NEP.CVE_IDEE_FECHA_ATENCION
INNER JOIN NEC_CIE10 CIE10P ON CIE10P.CVE_CIE10 = NDX.CVE_CIE10
INNER JOIN NET_DIAGNOSTICO_TIPODX NDXTP ON
    (NDXTP.CVE_IDEE_FECHA_ATENCION = NDX.CVE_IDEE_FECHA_ATENCION
         AND NDXTP.CVE_CIE10 = NDX.CVE_CIE10
         AND NDXTP.CVE_TIPO_DIAGNOSTICO = 1)
INNER JOIN NEC_MEDICAMENTO NECM ON NECM.CVE_MEDICAMENTO = NPM.CVE_MEDICAMENTO
INNER JOIN NET_ASIGNACION NA ON NA.CVE_ASIGNACION = NEP.CVE_ASIGNACION
INNER JOIN NET_UNIDAD_MEDICA NEUM ON NEUM.CVE_PRESUPUESTAL = NA.CVE_UNIDAD_MEDICA
INNER JOIN NET_PERSONAL_OPERATIVO NPO ON NPO.CVE_MATRICULA = NA.CVE_MATRICULA
INNER JOIN NEC_ESPECIALIDAD NES ON NES.CVE_ESPECIALIDAD = NA.CVE_ESPECIALIDAD
INNER JOIN NEC_DELEGACION_IMSS NDI ON NDI.CVE_DELEGACION_IMSS = NEUM.CVE_DELEGACION
WHERE
    NEP.STP_EVENTO >= TO_DATE('01/09/2022 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
    AND NEP.STP_EVENTO <= TO_DATE('01/09/2022 12:59:59', 'DD/MM/YYYY HH24:MI:SS')
    AND NPM.FEC_CANCELACION IS NULL
ORDER BY
    1, 2;


WITH UMMX AS (
    SELECT
        NET_UNIDAD_MEDICA.CVE_DELEGACION AS CLAVE_OOAD,
        NEC_DELEGACION_IMSS.NOM_DELEGACION_IMSS AS DELEGACION,
        NET_UNIDAD_MEDICA.REF_UNIDAD_MEDICA AS UNIDAD_MEDICA,
        NET_UNIDAD_MEDICA.CVE_PRESUPUESTAL AS PRESUPUESTAL,
        CASE
            WHEN NET_UNIDAD_MEDICA.CVE_NIVEL_ATENCION = 3 THEN 'Tercer Nivel'
            ELSE 'Segundo Nivel'
        END AS NIVEL_ATENCION,
        NEC_UNIDAD_MEDICA_CLUES.DES_TIPOLOGIA_UNIDAD AS TIPO_UNIDAD
    FROM NET_UNIDAD_MEDICA
    JOIN NEC_DELEGACION_IMSS ON NET_UNIDAD_MEDICA.CVE_DELEGACION = NEC_DELEGACION_IMSS.CVE_DELEGACION_IMSS
    LEFT JOIN
        NEC_UNIDAD_MEDICA_CLUES ON NET_UNIDAD_MEDICA.CVE_UNIDAD_CLUES = NEC_UNIDAD_MEDICA_CLUES.CVE_UNIDAD_CLUES
        AND NET_UNIDAD_MEDICA.CVE_CLUES = NEC_UNIDAD_MEDICA_CLUES.CVE_CLUES
),
RECETASMX AS (
    SELECT
        NET_ATENCION_NOTA_MEDICA.CVE_UNIDAD_MEDICA,
        NET_PRESCRIPCION_MEDICAMENTO.CVE_FOLIO_RECETA AS FOLIO_DOCUMENTO,
        NET_ATENCION_NOTA_MEDICA.STP_FECHA_ATENCION AS FECHA_CONSULTA,
        NET_PRESCRIPCION_MEDICAMENTO.FEC_RECETA AS FECHA_EMISION_MEDICAMENTO,
        EXTRACT(YEAR FROM NET_PRESCRIPCION_MEDICAMENTO.FEC_RECETA) || LPAD(EXTRACT(MONTH FROM NET_PRESCRIPCION_MEDICAMENTO.FEC_RECETA), 2, '0') AS EMEDYYMM,
        NET_PRESCRIPCION_MEDICAMENTO.CVE_MEDICAMENTO AS CLAVE_MEDICAMENTO,
        NEC_MEDICAMENTO.DES_MEDICAMENTO AS DESCRIPCION_MEDICAMENTO,
        NET_PRESCRIPCION_MEDICAMENTO.CAN_CANTIDAD AS CANTIDAD_PRESCRITA,
        NEC_TIPO_PRESCRIPCION.DES_TIPO_PRESCRIPCION AS TIPO_DOCUMENTO,
        NEC_CIE10.DES_CIE10
    FROM
        NET_PRESCRIPCION_MEDICAMENTO
    JOIN
        NET_ATENCION_NOTA_MEDICA ON NET_PRESCRIPCION_MEDICAMENTO.CVE_IDEE_FECHA_ATENCION = NET_ATENCION_NOTA_MEDICA.CVE_IDEE_FECHA_ATENCION
    JOIN
        NEC_MEDICAMENTO ON NET_PRESCRIPCION_MEDICAMENTO.CVE_MEDICAMENTO = NEC_MEDICAMENTO.CVE_MEDICAMENTO
    JOIN
        NEC_TIPO_PRESCRIPCION ON NET_PRESCRIPCION_MEDICAMENTO.CVE_CODIGO_TIPO_RECETA = NEC_TIPO_PRESCRIPCION.CVE_TIPO_PRESCRIPCION
    JOIN
        NET_DIAGNOSTICO_TIPODX ON NET_PRESCRIPCION_MEDICAMENTO.CVE_IDEE_FECHA_ATENCION = NET_DIAGNOSTICO_TIPODX.CVE_IDEE_FECHA_ATENCION
    JOIN
        NEC_CIE10 ON NET_DIAGNOSTICO_TIPODX.CVE_CIE10 = NEC_CIE10.CVE_CIE10
    WHERE
        NET_PRESCRIPCION_MEDICAMENTO.FEC_RECETA >= TO_DATE('11/10/2021 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
        AND NET_PRESCRIPCION_MEDICAMENTO.FEC_RECETA <= TO_DATE('20/10/2021 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
        AND NET_PRESCRIPCION_MEDICAMENTO.FEC_CANCELACION IS NULL
        AND NET_DIAGNOSTICO_TIPODX.CVE_TIPO_DIAGNOSTICO = 1
)
SELECT
    UMMX.*,
    RECETASMX.DES_CIE10,
    RECETASMX.TIPO_DOCUMENTO,
    RECETASMX.FOLIO_DOCUMENTO,
    RECETASMX.FECHA_CONSULTA,
    RECETASMX.FECHA_EMISION_MEDICAMENTO,
    RECETASMX.CLAVE_MEDICAMENTO,
    RECETASMX.DESCRIPCION_MEDICAMENTO,
    RECETASMX.CANTIDAD_PRESCRITA
FROM
    RECETASMX
JOIN
    UMMX ON RECETASMX.CVE_UNIDAD_MEDICA = UMMX.PRESUPUESTAL;