# Generated by Django 4.1.13 on 2024-07-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Fuente')),
                ('instituciones', models.TextField(blank=True, null=True, verbose_name='Instituciones participante')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Otras notas')),
            ],
            options={
                'verbose_name': 'Fuente de clasificación',
                'verbose_name_plural': 'Fuentes de clasificación',
            },
        ),
        migrations.CreateModel(
            name='GroupAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='medicine.group')),
            ],
            options={
                'verbose_name': 'Grupo de respuestas',
                'verbose_name_plural': 'Grupos de respuestas',
            },
        ),
        migrations.CreateModel(
            name='InternatinalTerapeticGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sin equivalente')),
            ],
            options={
                'verbose_name': 'Grupo Terapeútico Internacional',
                'verbose_name_plural': 'Grupos Terapeúticos Internacionales',
            },
        ),
        migrations.CreateModel(
            name='InternationalMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre original (inglés)')),
                ('without_equal', models.BooleanField(default=False, verbose_name='Sin equivalente')),
                ('component', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.component', verbose_name='Componente asociado')),
            ],
            options={
                'verbose_name': 'Medicamento Internacional',
                'verbose_name_plural': 'Medicamentos Internacionales',
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('recognition', models.BooleanField(blank=True, help_text='Permite mostrar el nombre del encuestado', null=True, verbose_name='Mostrar nombre')),
            ],
            options={
                'verbose_name': 'Encuestado',
                'verbose_name_plural': 'Encuestados',
            },
        ),
        migrations.CreateModel(
            name='PriorizedMedSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasification_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intl_medicine.clasificationsource')),
                ('international_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intl_medicine.internationalmedicine')),
            ],
            options={
                'verbose_name': 'Priorización según fuentes internacionales',
                'verbose_name_plural': 'Priorizaciones según fuentes internacionales',
            },
        ),
        migrations.CreateModel(
            name='PrioritizedComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prioritized', models.BooleanField(blank=True, null=True)),
                ('is_low_priority', models.BooleanField(blank=True, null=True)),
                ('was_changed', models.BooleanField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.component')),
                ('group_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioritized', to='intl_medicine.groupanswer')),
            ],
            options={
                'verbose_name': 'Priorización de componente',
                'verbose_name_plural': 'Priorizaciones de componentes',
            },
        ),
        migrations.AddField(
            model_name='groupanswer',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intl_medicine.respondent'),
        ),
    ]
