# Generated by Django 4.1.6 on 2023-04-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Fuente')),
                ('instituciones', models.TextField(blank=True, null=True, verbose_name='Instituciones participante')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Otras notas')),
            ],
            options={
                'verbose_name': 'Fuente de clasificación',
                'verbose_name_plural': 'Fuentes de clasificación',
            },
        ),
        migrations.CreateModel(
            name='InternatinalTerapeticGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sin equivalente')),
            ],
            options={
                'verbose_name': 'Grupo Terapeútico Internacional',
                'verbose_name_plural': 'Grupos Terapeúticos Internacionales',
            },
        ),
        migrations.CreateModel(
            name='InternationalMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre original (inglés)')),
                ('without_equal', models.BooleanField(default=False, verbose_name='Sin equivalente')),
                ('component', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.component', verbose_name='Componente asociado')),
            ],
            options={
                'verbose_name': 'Medicamento Internacional',
                'verbose_name_plural': 'Medicamentos Internacionales',
            },
        ),
        migrations.CreateModel(
            name='PriorizedMedSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasification_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intl_medicine.clasificationsource')),
                ('international_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intl_medicine.internationalmedicine')),
            ],
            options={
                'verbose_name': 'Priorización según fuentes internacionales',
                'verbose_name_plural': 'Priorizaciones según fuentes internacionales',
            },
        ),
    ]
