# Generated by Django 4.1.6 on 2024-01-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_component_description'),
        ('intl_medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('institution', models.CharField(max_length=255, verbose_name='Institución')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('completed_groups', models.ManyToManyField(blank=True, to='medicine.group', verbose_name='Grupos completados')),
            ],
            options={
                'verbose_name': 'Encuestado',
                'verbose_name_plural': 'Encuestados',
            },
        ),
        migrations.CreateModel(
            name='PrioritizedComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prioritized', models.BooleanField(blank=True, null=True)),
                ('is_low_priority', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.component')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prioritized', to='medicine.group')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intl_medicine.respondent')),
            ],
            options={
                'verbose_name': 'Priorización de componente',
                'verbose_name_plural': 'Priorizaciones de componentes',
            },
        ),
    ]
