# Generated by Django 4.1.6 on 2024-01-10 17:38

from django.db import migrations, models
import django.db.models.deletion


def delete_prioritized_component(apps, schema_editor):
    PrioritizedComponent = apps.get_model("intl_medicine", "PrioritizedComponent")
    PrioritizedComponent.objects.all().delete()


def create_group_answer(apps, schema_editor):
    GroupAnswer = apps.get_model("intl_medicine", "GroupAnswer")
    Group = apps.get_model("medicine", "Group")
    for group in Group.objects.all():
        new_group_answer = GroupAnswer()
        new_group_answer.group = group
        new_group_answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_component_description'),
        ('intl_medicine', '0002_respondent_prioritizedcomponent'),
    ]

    operations = [
        migrations.RunPython(delete_prioritized_component),
        migrations.RenameField(
            model_name='respondent',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='prioritizedcomponent',
            name='group',
        ),
        migrations.RemoveField(
            model_name='prioritizedcomponent',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='completed_groups',
        ),
        migrations.AddField(
            model_name='respondent',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='recognition',
            field=models.BooleanField(blank=True, help_text='Permite mostrar el nombre del encuestado', null=True, verbose_name='Mostrar nombre'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución'),
        ),
        migrations.CreateModel(
            name='GroupAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='medicine.group')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intl_medicine.respondent')),
            ],
            options={
                'verbose_name': 'Respuesta de grupo',
                'verbose_name_plural': 'Respuestas de grupos',
            },
        ),
        migrations.AddField(
            model_name='prioritizedcomponent',
            name='group_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prioritized', to='intl_medicine.groupanswer'),
            preserve_default=False,
        ),
        migrations.RunPython(create_group_answer),
    ]
