# Generated by Django 4.1.6 on 2024-01-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intl_medicine', '0003_rename_name_respondent_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupanswer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
