# Generated by Django 4.1.6 on 2024-01-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intl_medicine', '0005_remove_prioritizedcomponent_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupanswer',
            options={'verbose_name': 'Grupo de respuestas', 'verbose_name_plural': 'Grupos de respuestas'},
        ),
    ]
