# Generated by Django 4.1.13 on 2024-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intl_medicine', '0006_alter_groupanswer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupanswer',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
