# Generated by Django 4.1.6 on 2024-04-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intl_medicine', '0007_groupanswer_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupanswer',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prioritizedcomponent',
            name='was_changed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
