# Generated by Django 4.1.6 on 2023-02-17 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inai', '0045_delete_asynctask'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTask',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=5)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Status de tarea',
                'verbose_name_plural': 'Status de tareas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskFunction',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, choices=[('petition', 'Petición'), ('file_control', 'Control de archivo'), ('data_file', 'Archivo de datos'), ('process_file', 'Archivo de procesamiento')], max_length=100, null=True)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('addl_params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Función (tarea)',
                'verbose_name_plural': 'Funciones (tareas)',
            },
        ),
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('function_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la función')),
                ('function_after', models.CharField(blank=True, max_length=100, null=True, verbose_name='Función a ejecutar después')),
                ('original_request', models.JSONField(blank=True, null=True, verbose_name='Request original')),
                ('params_after', models.JSONField(blank=True, null=True, verbose_name='Parámetros de la función after')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.datafile')),
                ('file_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.filecontrol')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='task.asynctask')),
                ('petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.petition')),
                ('process_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.processfile')),
                ('status_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.statustask', verbose_name='Estado de la tarea')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea asincrónica',
                'verbose_name_plural': 'Tareas asincrónicas',
                'ordering': ['-date_start'],
            },
        ),
    ]
