# Generated by Django 4.1.6 on 2023-04-23 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inai', '0001_initial'),
        ('data_param', '0001_initial'),
        ('classify_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('has_constrains', models.BooleanField(default=True)),
                ('create_constraints', models.JSONField(blank=True, null=True)),
                ('delete_constraints', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('function_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la función')),
                ('is_massive', models.BooleanField(default=False)),
                ('subgroup', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtipo de la función')),
                ('function_after', models.CharField(blank=True, max_length=100, null=True, verbose_name='Función a ejecutar después')),
                ('original_request', models.JSONField(blank=True, null=True, verbose_name='Request original')),
                ('params_after', models.JSONField(blank=True, null=True, verbose_name='Parámetros de la función after')),
                ('result', models.JSONField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True, verbose_name='last')),
                ('traceback', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_arrive', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.datafile')),
                ('file_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='data_param.filecontrol')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='task.asynctask')),
                ('petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.petition')),
                ('reply_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.replyfile')),
                ('sheet_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.sheetfile')),
                ('status_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask', verbose_name='Estado de la tarea')),
                ('task_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='classify_task.taskfunction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea solicitada',
                'verbose_name_plural': '1. Tareas solicitadas',
                'ordering': ['-date_start'],
            },
        ),
    ]
