# Generated by Django 4.1.6 on 2024-07-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilePath',
        ),
    ]
