# Generated by Django 4.1.6 on 2023-02-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asynctask',
            options={'ordering': ['-date_start'], 'verbose_name': 'Tarea asincrónica', 'verbose_name_plural': '1. Tareas solicitadas'},
        ),
        migrations.AlterModelOptions(
            name='statustask',
            options={'ordering': ['order'], 'verbose_name': 'Status de tarea', 'verbose_name_plural': '3. Status de tareas'},
        ),
        migrations.AlterModelOptions(
            name='taskfunction',
            options={'verbose_name': 'Función (tarea)', 'verbose_name_plural': '2. Funciones (tareas)'},
        ),
        migrations.AddField(
            model_name='asynctask',
            name='date_arrive',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asynctask',
            name='date_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asynctask',
            name='sub_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtipo de la función'),
        ),
        migrations.AddField(
            model_name='asynctask',
            name='task_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.taskfunction'),
        ),
        migrations.AlterField(
            model_name='taskfunction',
            name='model_name',
            field=models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('process_file', 'ProcessFile (.zip)')], max_length=100, null=True),
        ),
    ]
