# Generated by Django 4.1.13 on 2024-07-16 08:21

from django.db import migrations

def copy_old_values_opera(apps, schema_editor):
    OldStatusControl = apps.get_model("category", "OldStatusControl")
    Step = apps.get_model("task", "Step")
    for old_status in OldStatusControl.objects.all():
        Step.objects.filter(old_status_opera=old_status)\
                .update(status_operative=old_status.name)

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_old_values_opera),
    ]
