# Generated by Django 4.1.6 on 2023-02-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_asynctask_options_alter_statustask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='task_function_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions_after', to='task.taskfunction'),
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='task_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='task.taskfunction'),
        ),
    ]
