# Generated by Django 4.1.13 on 2024-07-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_run_python'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilePath',
        ),
    ]
