# Generated by Django 4.1.6 on 2024-08-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0002_cluster_icon'),
        ('task', '0002_delete_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='rds.cluster'),
        ),
        migrations.AddField(
            model_name='asynctask',
            name='mat_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='rds.matview'),
        ),
        migrations.AddField(
            model_name='asynctask',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='rds.operation'),
        ),
    ]
