# Generated by Django 4.1.6 on 2023-02-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_asynctask_task_function_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asynctask',
            name='date_send',
        ),
        migrations.RemoveField(
            model_name='asynctask',
            name='task_function_after',
        ),
    ]
