# Generated by Django 4.1.6 on 2023-05-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
        ('task', '0004_asynctask_entity_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='geo.entity'),
        ),
    ]
