# Generated by Django 4.1.6 on 2023-05-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_asynctask_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='finished_function',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Función a ejecutar si es exitosa'),
        ),
    ]
