# Generated by Django 4.1.6 on 2023-02-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_sub_group_asynctask_subgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asynctask',
            name='error',
        ),
        migrations.AddField(
            model_name='asynctask',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
