# Generated by Django 4.1.6 on 2023-05-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_asynctask_finished_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='is_massive',
            field=models.BooleanField(default=False, verbose_name='many'),
        ),
    ]
