# Generated by Django 4.1.6 on 2023-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_asynctask_error_asynctask_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='last'),
        ),
    ]
