# Generated by Django 4.1.6 on 2023-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_asynctask_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='file_control',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
