# Generated by Django 4.1.6 on 2023-07-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_asynctask_is_massive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['-version'], 'verbose_name': 'Plataforma', 'verbose_name_plural': 'Plataformas'},
        ),
    ]
