# Generated by Django 4.1.6 on 2023-03-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0026_alter_filecontrol_table_alter_namecolumn_table_and_more'),
        ('task', '0008_alter_asynctask_file_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='data_param.filecontrol'),
        ),
    ]
