# Generated by Django 4.1.6 on 2023-08-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_platform_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asynctask',
            name='function_name',
        ),
    ]
