# Generated by Django 4.1.6 on 2023-10-27 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_alter_entity_options'),
        ('category', '0002_alter_statuscontrol_icon'),
        ('classify_task', '0011_stage_stage_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0009_remove_asynctask_function_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Última modificación')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.entity', verbose_name='Entidad')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa')),
                ('status_opera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Último usuario en modificar')),
            ],
            options={
                'verbose_name': 'Paso',
                'verbose_name_plural': 'Pasos',
            },
        ),
    ]
