# Generated by Django 4.1.6 on 2023-03-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0054_replyfile_remove_processfile_file_type_and_more'),
        ('task', '0009_alter_asynctask_file_control'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asynctask',
            options={'ordering': ['-date_start'], 'verbose_name': 'Tarea solicitada', 'verbose_name_plural': '1. Tareas solicitadas'},
        ),
        migrations.RemoveField(
            model_name='asynctask',
            name='process_file',
        ),
        migrations.AddField(
            model_name='asynctask',
            name='reply_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.replyfile'),
        ),
        migrations.AlterField(
            model_name='taskfunction',
            name='model_name',
            field=models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('process_file', 'ReplyFile (.zip)')], max_length=100, null=True),
        ),
    ]
