# Generated by Django 4.1.6 on 2023-10-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_alter_entity_options'),
        ('inai', '0060_delete_step'),
        ('task', '0010_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='entity',
        ),
        migrations.CreateModel(
            name='CutOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.entity', verbose_name='Entidad')),
                ('last_entity_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.entitymonth', verbose_name='Mes de corte')),
            ],
            options={
                'verbose_name': 'Corte',
                'verbose_name_plural': 'Cortes',
            },
        ),
        migrations.AddField(
            model_name='step',
            name='cut_off',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.cutoff', verbose_name='Corte'),
            preserve_default=False,
        ),
    ]
