# Generated by Django 4.1.6 on 2023-03-05 18:42

from django.db import migrations, models


def move_process_to_reply(apps, schema_editor):
    TaskFunction = apps.get_model('task', 'TaskFunction')
    TaskFunction.objects.filter(model_name='process_file')\
        .update(model_name='reply_file')


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_asynctask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfunction',
            name='model_name',
            field=models.CharField(blank=True, choices=[('petition', 'Solicitud (Petición)'), ('file_control', 'Grupo de Control'), ('data_file', 'DataFile (archivo de datos)'), ('process_file', 'ReplyFile (.zip)'), ('reply_file', 'ReplyFile (.zip)')], max_length=100, null=True),
        ),
        migrations.RunPython(move_process_to_reply),
    ]
