# Generated by Django 4.1.6 on 2023-10-31 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_alter_entity_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0011_remove_step_entity_cutoff_step_cut_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoff',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_offs', to='geo.entity', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='step',
            name='cut_off',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='task.cutoff', verbose_name='Corte'),
        ),
        migrations.AlterField(
            model_name='step',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Último usuario en modificar'),
        ),
    ]
