# Generated by Django 4.1.11 on 2023-11-16 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0060_delete_step'),
        ('task', '0012_alter_cutoff_entity_alter_step_cut_off_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['-stage__order'], 'verbose_name': 'Paso', 'verbose_name_plural': 'Pasos'},
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_file', models.CharField(max_length=400, verbose_name='Ruta al archivo deseable')),
                ('path_in_bucket', models.CharField(max_length=400, verbose_name='Ruta al archivo actual')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('is_correct_path', models.BooleanField(blank=True, null=True)),
                ('data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.datafile')),
                ('reply_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_paths', to='inai.replyfile')),
                ('sheet_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.sheetfile')),
                ('table_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.tablefile')),
            ],
        ),
    ]
