# Generated by Django 4.1.6 on 2023-03-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_taskfunction_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='status_task',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de la tarea'),
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='task_function',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la función'),
        ),
    ]
