# Generated by Django 4.1.6 on 2023-03-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_asynctask_status_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusTask',
        ),
        migrations.DeleteModel(
            name='TaskFunction',
        ),
    ]
