# Generated by Django 4.1.6 on 2023-11-23 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0061_alter_datafile_options_remove_datafile_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_param', '0008_alter_filecontrol_table_alter_namecolumn_table_and_more'),
        ('task', '0013_alter_step_options_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('entity_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.entitymonth', verbose_name='Mes')),
                ('file_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.filecontrol', verbose_name='Control de archivos')),
                ('petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.petition', verbose_name='Petición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_histories', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de clicks',
                'verbose_name_plural': 'Historial de clicks',
                'ordering': ['-date'],
            },
        ),
    ]
