# Generated by Django 4.1.6 on 2024-01-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_clickhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickhistory',
            options={'ordering': ['-date'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
    ]
