# Generated by Django 4.1.6 on 2023-03-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0002_stage'),
        ('task', '0014_delete_statustask_delete_taskfunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='status_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask', verbose_name='Estado de la tarea'),
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='task_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='classify_task.taskfunction'),
        ),
    ]
