# Generated by Django 4.1.6 on 2024-02-10 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0015_alter_clickhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clickhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='OfflineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Inicio')),
                ('date_end', models.DateTimeField(verbose_name='Fin')),
                ('activity_type', models.CharField(choices=[('weekly_meeting', 'Reunión semanal'), ('meeting', 'Reunión'), ('training', 'Capacitación'), ('pnt', 'PNT'), ('other', 'Otro')], max_length=100, verbose_name='Tipo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Actividad')),
                ('user_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offline_tasks_added', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='offline_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea offline',
                'verbose_name_plural': 'Tareas offline',
                'ordering': ['-date_start'],
            },
        ),
    ]
