# Generated by Django 4.1.6 on 2023-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_asynctask_table_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='is_massive',
            field=models.BooleanField(default=False),
        ),
    ]
