# Generated by Django 4.1.6 on 2023-03-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0066_sheetfile_alter_tablefile_unique_together_and_more'),
        ('task', '0017_asynctask_is_massive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asynctask',
            name='table_file',
        ),
        migrations.AddField(
            model_name='asynctask',
            name='sheet_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='inai.sheetfile'),
        ),
    ]
