# Generated by Django 4.1.6 on 2023-04-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='create_constrains',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='delete_constrains',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
