# Generated by Django 4.1.6 on 2024-03-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_rename_entity_asynctask_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asynctask',
            old_name='entity_month',
            new_name='month_record',
        ),
        migrations.RenameField(
            model_name='asynctask',
            old_name='entity_week',
            new_name='week_record',
        ),
        migrations.RenameField(
            model_name='clickhistory',
            old_name='entity_month',
            new_name='month_record',
        ),
        migrations.RenameField(
            model_name='cutoff',
            old_name='last_entity_month',
            new_name='last_month_record',
        ),
    ]
