# Generated by Django 4.1.6 on 2023-04-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_platform_create_constrains_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='create_constrains',
            new_name='create_constraints',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='delete_constrains',
            new_name='delete_constraints',
        ),
    ]
