# Generated by Django 4.1.6 on 2024-05-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_rename_entity_month_asynctask_month_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='status_opera',
            new_name='old_status_opera',
        ),
    ]
