# Generated by Django 4.1.6 on 2024-05-04 19:16

from django.db import migrations, models
import django.db.models.deletion


def copy_old_values_opera(apps, schema_editor):
    OldStatusControl = apps.get_model("category", "OldStatusControl")
    Step = apps.get_model("task", "Step")
    for old_status in OldStatusControl.objects.all():
        Step.objects.filter(old_status_opera=old_status)\
                .update(status_operative=old_status.name)


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_statuscontrol'),
        ('task', '0021_rename_status_opera_step_old_status_opera'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='status_operative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol', verbose_name='Status'),
        ),
        migrations.RunPython(copy_old_values_opera),
    ]
