# Generated by Django 4.1.6 on 2023-04-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_rename_create_constrains_platform_create_constraints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
