# Generated by Django 4.1.6 on 2024-05-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_step_new_status_operative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='old_status_opera',
        ),
    ]
