# Generated by Django 4.1.6 on 2024-05-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_remove_step_old_status_opera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutoff',
            options={'verbose_name': 'Corte de pasos', 'verbose_name_plural': 'Cortes de pasos'},
        ),
    ]
