# Generated by Django 4.1.6 on 2024-06-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_alter_filepath_options_alter_platform_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
