# Generated by Django 4.1.6 on 2024-07-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0023_alter_taskfunction_group_queue_and_more'),
        ('task', '0026_delete_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='status_task',
            field=models.ForeignKey(default='created', on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask', verbose_name='Estado de la tarea'),
        ),
    ]
