# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-18 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('event_data', models.TextField()),
                ('email_record', models.IntegerField()),
            ],
            options={
                'db_table': 'perfil_emaileventhistory',
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email', models.BooleanField(default=False)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('template_base', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('x_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('sg_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(default=b'unknown', max_length=20)),
                ('status_date', models.DateTimeField(blank=True, null=True)),
                ('type_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'perfil_emailrecord',
                'verbose_name': 'Envio de Email',
                'verbose_name_plural': 'Envios de Emails',
            },
        ),
        migrations.CreateModel(
            name='MassMailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_base', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filter_kwargs', models.TextField(blank=True, null=True)),
                ('exclude_kwargs', models.TextField(blank=True, null=True)),
                ('order_by_args', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil_massmailing',
            },
        ),
        migrations.CreateModel(
            name='TemplateBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('from_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'perfil_templatebase',
                'verbose_name': 'Plantilla Base',
                'verbose_name_plural': 'Plantillas Base',
            },
        ),
    ]
