# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-18 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_sendgrid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaileventhistory',
            name='email_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_sendgrid.EmailRecord'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='template_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_sendgrid.TemplateBase'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='massmailing',
            name='template_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_sendgrid.TemplateBase'),
        ),
    ]
