# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-19 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_sendgrid', '0002_auto_20200518_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendGridProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sendgrid_api_key', models.CharField(max_length=255)),
                ('webhook_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Perfil de correo por SendGrid',
                'verbose_name_plural': 'Perfiles de correo por SendGrid',
            },
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='sendgrid_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_sendgrid.SendGridProfile'),
        ),
    ]
