# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sendgrid', '0003_auto_20200519_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendgridprofile',
            name='test_emails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sendgridprofile',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
