# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-05-28 18:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sendgrid', '0004_auto_20200522_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebase',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
