# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_sendgrid', '0005_auto_20200528_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatebase',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='templatebase',
            name='sendgrid_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_sendgrid.SendGridProfile'),
        ),
        migrations.AddField(
            model_name='templatebase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatebase',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
