# Generated by Django 2.2.25 on 2021-12-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sendgrid', '0006_auto_20210302_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
