# Generated by Django 4.1.6 on 2023-03-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transparencylevel',
            table='transparency_transparencylevel',
        ),
    ]
