# Generated by Django 4.1.6 on 2023-03-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0002_alter_transparencylevel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anomaly',
            table='transparency_anomaly',
        ),
        migrations.AlterModelTable(
            name='transparencyindex',
            table='transparency_transparencyindex',
        ),
    ]
