# Generated by Django 4.1.6 on 2023-03-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0003_alter_anomaly_table_alter_transparencyindex_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencylevel',
            options={'ordering': ['transparency_index__order_viz', '-order_viz'], 'verbose_name': 'Transparencia: Nivel', 'verbose_name_plural': 'Transparencia: Niveles'},
        ),
        migrations.AlterField(
            model_name='transparencylevel',
            name='transparency_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='transparency.transparencyindex', verbose_name='Indicador de Transparencia'),
        ),
    ]
