# Generated by Django 2.2.25 on 2022-03-09 00:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('page_url', models.CharField(blank=True, max_length=180, null=True)),
                ('logo', models.FileField(upload_to='')),
                ('level', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Alianza',
                'verbose_name_plural': 'Alianzas',
                'db_table': 'desabasto_alliances',
            },
        ),
        migrations.CreateModel(
            name='CLUES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('institution', models.IntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='NOMBRE DE LA UNIDAD')),
                ('is_searchable', models.BooleanField(default=False, help_text='Puede buscarse por el usuario', verbose_name='Activo')),
                ('municipality', models.CharField(max_length=255, verbose_name='NOMBRE DEL MUNICIPIO')),
                ('municipality_inegi_code', models.CharField(max_length=3, verbose_name='CLAVE DEL MUNICIPIO')),
                ('tipology', models.CharField(max_length=255, verbose_name='NOMBRE DE TIPOLOGIA')),
                ('tipology_cve', models.CharField(max_length=12, verbose_name='CLAVE DE TIPOLOGIA')),
                ('id_clues', models.CharField(max_length=10, verbose_name='ID_CLUES')),
                ('clues', models.CharField(max_length=20, verbose_name='CLUES')),
                ('status_operation', models.CharField(max_length=80, verbose_name='ESTATUS DE OPERACION')),
                ('longitude', models.CharField(max_length=20, verbose_name='LONGITUD')),
                ('latitude', models.CharField(max_length=20, verbose_name='LATITUD')),
                ('locality', models.CharField(max_length=80, verbose_name='NOMBRE DE LA LOCALIDAD')),
                ('locality_inegi_code', models.CharField(max_length=5, verbose_name='CLAVE DE LA LOCALIDAD')),
                ('jurisdiction', models.CharField(max_length=80, verbose_name='NOMBRE DE LA JURISDICCION')),
                ('jurisdiction_clave', models.CharField(max_length=5, verbose_name='CLAVE DE LA JURISDICCION')),
                ('establishment_type', models.CharField(max_length=80, verbose_name='NOMBRE TIPO ESTABLECIMIENTO')),
                ('consultings_general', models.IntegerField(verbose_name='CONSULTORIOS DE MED GRAL')),
                ('consultings_other', models.IntegerField(verbose_name='CONSULTORIOS EN OTRAS AREAS')),
                ('beds_hopital', models.IntegerField(verbose_name='CAMAS EN AREA DE HOS')),
                ('beds_other', models.IntegerField(verbose_name='CAMAS EN OTRAS AREAS')),
                ('total_unities', models.IntegerField(verbose_name='UNIDADES TOTALES (SUMA)')),
                ('admin_institution', models.CharField(max_length=80, verbose_name='NOMBRE DE LA INS ADM')),
                ('atention_level', models.CharField(max_length=80, verbose_name='NIVEL ATENCION')),
                ('stratum', models.CharField(max_length=80, verbose_name='ESTRATO UNIDAD')),
                ('real_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Limpiado')),
                ('alter_clasifs', models.CharField(blank=True, max_length=255, null=True, verbose_name='clasificaciones alternativas')),
                ('clasif_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre completo tipo')),
                ('prev_clasif_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre corto tipo')),
                ('number_unity', models.CharField(blank=True, max_length=6, null=True, verbose_name='Número de unidad')),
                ('is_national', models.BooleanField(default=False)),
                ('name_in_issten', models.CharField(blank=True, max_length=255, null=True, verbose_name='NOMBRE DE LA UNIDAD')),
                ('rr_data', models.TextField(blank=True, null=True)),
                ('alternative_names', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo ClUES',
                'verbose_name_plural': 'Catálogo ClUESs',
                'db_table': 'desabasto_clues',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='NOMBRE DE LA INSTITUCION')),
                ('code', models.CharField(max_length=20, verbose_name='CLAVE DE LA INSTITUCION')),
                ('public_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='NOMBRE PUBLICO DE LA INSTITUCION')),
                ('public_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='CLAVE PUBLICA DE LA INSTITUCION')),
                ('relevance', models.IntegerField(default=2, verbose_name='Relevancia (Para filtros)')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'desabasto_institution',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=2, verbose_name='Clave INEGI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre Corto')),
                ('code_name', models.CharField(blank=True, max_length=6, null=True, verbose_name='Nombre Clave')),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'desabasto_state',
            },
        ),
    ]
