# Generated by Django 2.2.25 on 2022-03-10 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='catalog.State', verbose_name='Entidad'),
        ),
    ]
