# Generated by Django 2.2.25 on 2022-03-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220309_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Padecimiento',
                'verbose_name_plural': '7. Padecimientos',
                'db_table': 'desabasto_disease',
            },
        ),
        migrations.AlterModelOptions(
            name='clues',
            options={'verbose_name': 'Hospital o clínica CLUES', 'verbose_name_plural': 'Catálogo CLUES'},
        ),
    ]
