# Generated by Django 2.2.25 on 2022-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220323_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliances',
            name='diseases_litigation',
            field=models.ManyToManyField(blank=True, related_name='litigations', to='catalog.Disease', verbose_name='Padecimientos asociados (asesoría legal)'),
        ),
        migrations.AddField(
            model_name='alliances',
            name='diseases_management',
            field=models.ManyToManyField(blank=True, related_name='managements', to='catalog.Disease', verbose_name='Padecimientos asociados (acompañamiento)'),
        ),
        migrations.AddField(
            model_name='alliances',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email para asistencia'),
        ),
        migrations.AddField(
            model_name='alliances',
            name='page_help',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Página web de asistencia'),
        ),
        migrations.AddField(
            model_name='alliances',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='alliances',
            name='page_url',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Página web'),
        ),
    ]
