# Generated by Django 2.2.25 on 2022-07-20 00:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave oficial')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre oficial')),
                ('public_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre corto (modificado)')),
                ('alternative_names', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipología',
                'verbose_name_plural': 'Tipologías',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, help_text='Solo cuando sea distinta al nombre de la institución/CLUES', max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('other_names', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('clues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.CLUES')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Institution', verbose_name='Institución')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.State', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
            },
        ),
        migrations.AddField(
            model_name='clues',
            name='tipology_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Tipology', verbose_name='Tipología (Catálogo)'),
        ),
    ]
