# Generated by Django 2.2.25 on 2022-07-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220719_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='last_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FECHA ULTIMO MOVIMIENTO'),
        ),
        migrations.AddField(
            model_name='clues',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='CODIGO POSTAL'),
        ),
        migrations.AddField(
            model_name='clues',
            name='rfc',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='clues',
            name='streat_number',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='NÚMERO CALLE'),
        ),
        migrations.AddField(
            model_name='clues',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VIALIDAD'),
        ),
        migrations.AddField(
            model_name='clues',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SUBURBIO'),
        ),
        migrations.AddField(
            model_name='clues',
            name='type_street',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='TIPO DE VIALIDAD'),
        ),
    ]
