# Generated by Django 2.2.25 on 2022-07-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20220727_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='municipality_inegi_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Municipality'),
        ),
    ]
