# Generated by Django 2.2.25 on 2022-07-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220727_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['state__name'], 'verbose_name': 'Sujeto Obligado', 'verbose_name_plural': 'Sujetos Obligados'},
        ),
    ]
