# Generated by Django 2.2.25 on 2022-07-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20220729_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Siglas del Sujeto Obligado'),
        ),
    ]
