# Generated by Django 2.2.25 on 2022-08-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_entity_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='idSujetoObligado',
            field=models.IntegerField(blank=True, null=True, verbose_name='idSujetoObligado (inai)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='nombreSujetoObligado',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='nombreSujetoObligado (inai)'),
        ),
    ]
