# Generated by Django 2.2.25 on 2022-08-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220801_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='compentent',
            field=models.BooleanField(default=True, help_text='Es compentente porque tiene pacientes y debe tener la información', verbose_name='compentente'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='idSujetoObligado',
            field=models.IntegerField(blank=True, help_text='idSujetoObligado del INAI', null=True, verbose_name='idSujetoObligado'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='nombreSujetoObligado',
            field=models.CharField(blank=True, help_text='nombreSujetoObligado del INAI', max_length=160, null=True, verbose_name='nombreSujetoObligado)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='vigencia',
            field=models.BooleanField(default=True, help_text='Actualmente se le sigue preguntando'),
        ),
    ]
