# Generated by Django 2.2.25 on 2022-08-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20220808_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
