# Generated by Django 2.2.25 on 2022-08-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_entity_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_pilot',
            field=models.BooleanField(default=False),
        ),
    ]
