# Generated by Django 2.2.25 on 2022-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20220831_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Derechohabientes'),
        ),
    ]
