# Generated by Django 4.1.5 on 2023-01-22 07:41

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_entity_nameforinai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='alternative_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='other_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addl_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='alternative_names',
            field=models.JSONField(help_text='Ocupar para OCAMIS', verbose_name='Lista nombres alternativos'),
        ),
        migrations.AlterField(
            model_name='tipology',
            name='alternative_names',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
