# Generated by Django 4.1.6 on 2023-02-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_clues_key_issste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='clues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_clues', to='catalog.clues'),
        ),
    ]
