# Generated by Django 4.1.6 on 2023-02-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_delegation_clues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='clues',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_delegation', to='catalog.clues'),
        ),
    ]
