# Generated by Django 4.1.6 on 2023-03-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_delegation_clues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='key_issste',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Clave única de ISSSTE'),
        ),
        migrations.AlterField(
            model_name='clues',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='clues',
            name='total_unities',
            field=models.IntegerField(verbose_name='suma de unidades'),
        ),
    ]
