# Generated by Django 4.1.6 on 2023-03-14 17:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_clues_typology_cve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='id',
        ),
        migrations.AddField(
            model_name='area',
            name='delegation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.delegation', verbose_name='Delegación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
