# Generated by Django 4.1.6 on 2023-04-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_rename_entity_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='hex_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
