# Generated by Django 2.2.25 on 2022-03-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres alternativos y comerciales')),
                ('presentation_count', models.IntegerField(default=1)),
                ('frequency', models.IntegerField(blank=True, default=0, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('presentations_raw', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('is_relevant', models.BooleanField(default=True)),
                ('is_vaccine', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'desabasto_component',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('key', models.CharField(max_length=20, verbose_name='Clave')),
                ('key2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave sin puntos')),
                ('is_current', models.BooleanField(default=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Recipiente (Contenedor)',
                'verbose_name_plural': 'Recipientes (Contenedores)',
                'db_table': 'desabasto_container',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Terapeútico',
                'verbose_name_plural': 'Grupos Terapeúticos',
                'db_table': 'desabasto_group',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.IntegerField()),
                ('presentation_type', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('presentation_type_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.TextField(blank=True, null=True)),
                ('official_attributes', models.TextField(blank=True, null=True)),
                ('short_attributes', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Presentación del componente',
                'verbose_name_plural': 'Presentaciones del componente',
                'db_table': 'desabasto_presentation',
            },
        ),
        migrations.CreateModel(
            name='PresentationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_count', models.IntegerField(default=0)),
                ('agrupated_in', models.IntegerField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de presentación',
                'verbose_name_plural': 'Tipos de presentación',
                'db_table': 'desabasto_presentationtype',
                'ordering': ['name'],
            },
        ),
    ]
