# Generated by Django 4.1.13 on 2024-07-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_type', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres alternativos y comerciales')),
                ('alternative_names', models.JSONField(blank=True, default=list, null=True, verbose_name='Otros nombres')),
                ('presentation_count', models.IntegerField(default=1)),
                ('frequency', models.IntegerField(blank=True, default=0, null=True)),
                ('presentations_raw', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('is_relevant', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('generalities', models.TextField(blank=True, null=True, verbose_name='Generalidades')),
                ('pregnancy_risks', models.TextField(blank=True, null=True, verbose_name='Riesgos en el embarazo')),
                ('adverse_effects', models.TextField(blank=True, null=True, verbose_name='Efectos adversos')),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='Contraindicaciones y precauciones')),
                ('interactions', models.TextField(blank=True, null=True, verbose_name='Interacciones')),
                ('groups_count', models.IntegerField(default=0, verbose_name='Gpos')),
                ('groups_pc_count', models.IntegerField(default=0, verbose_name='Gpos. priori')),
                ('presentations_count', models.IntegerField(default=0, verbose_name='Pres.')),
                ('containers_count', models.IntegerField(default=0, verbose_name='Cont.')),
                ('is_vaccine', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': '2. Componentes',
                'db_table': 'medicine_component',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('need_survey', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo Terapeútico',
                'verbose_name_plural': '1. Grupos Terapeúticos',
                'db_table': 'medicine_group',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Fuente de catálogo',
                'verbose_name_plural': 'Fuentes de catálogo',
            },
        ),
        migrations.CreateModel(
            name='PresentationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_count', models.IntegerField(default=0)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('agrupated_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.presentationtype')),
            ],
            options={
                'verbose_name': 'Tipo de presentación',
                'verbose_name_plural': '0. Tipos de presentación',
                'db_table': 'medicine_presentationtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('presentation_type_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('indications', models.TextField(blank=True, null=True, verbose_name='Indicaciones')),
                ('way', models.TextField(blank=True, null=True, verbose_name='Vía de administración')),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.TextField(blank=True, null=True)),
                ('official_attributes', models.TextField(blank=True, null=True)),
                ('short_attributes', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='medicine.component')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_presentations', to='medicine.group')),
                ('groups', models.ManyToManyField(blank=True, related_name='presentations', to='medicine.group')),
                ('presentation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.presentationtype')),
            ],
            options={
                'verbose_name': 'Presentación del componente',
                'verbose_name_plural': '3. Presentaciones del componente',
                'db_table': 'medicine_presentation',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('key', models.CharField(max_length=20, verbose_name='Clave')),
                ('key2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave sin puntos')),
                ('is_current', models.BooleanField(default=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='medicine.presentation')),
                ('sources', models.ManyToManyField(blank=True, to='medicine.source')),
            ],
            options={
                'verbose_name': 'Recipiente (Contenedor)',
                'verbose_name_plural': '4. Recipientes (Contenedores)',
                'db_table': 'medicine_container',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.group'),
        ),
        migrations.AddField(
            model_name='component',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='components', to='medicine.group'),
        ),
    ]
