# Generated by Django 4.1.6 on 2023-04-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine_type', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres alternativos y comerciales')),
                ('presentation_count', models.IntegerField(default=1)),
                ('frequency', models.IntegerField(blank=True, default=0, null=True)),
                ('presentations_raw', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('is_relevant', models.BooleanField(default=True)),
                ('is_vaccine', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': '2. Componentes',
                'db_table': 'desabasto_component',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Terapeútico',
                'verbose_name_plural': '1. Grupos Terapeúticos',
                'db_table': 'desabasto_group',
            },
        ),
        migrations.CreateModel(
            name='PresentationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_count', models.IntegerField(default=0)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('agrupated_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.presentationtype')),
            ],
            options={
                'verbose_name': 'Tipo de presentación',
                'verbose_name_plural': '0. Tipos de presentación',
                'db_table': 'desabasto_presentationtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('presentation_type_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('official_name', models.TextField(blank=True, null=True)),
                ('official_attributes', models.TextField(blank=True, null=True)),
                ('short_attributes', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='medicine.component')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.group')),
                ('presentation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.presentationtype')),
            ],
            options={
                'verbose_name': 'Presentación del componente',
                'verbose_name_plural': '3. Presentaciones del componente',
                'db_table': 'desabasto_presentation',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key', models.CharField(max_length=20, verbose_name='Clave')),
                ('key2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave sin puntos')),
                ('is_current', models.BooleanField(default=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('origen_cvmei', models.BooleanField(default=False)),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='medicine.presentation')),
            ],
            options={
                'verbose_name': 'Recipiente (Contenedor)',
                'verbose_name_plural': '4. Recipientes (Contenedores)',
                'db_table': 'desabasto_container',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.group'),
        ),
    ]
