# Generated by Django 4.1.13 on 2024-07-16 08:17

from django.db import migrations


def add_groups(apps, schema_editor):
    PrioritizedComponent = apps.get_model(
        'intl_medicine', 'PrioritizedComponent')
    alone_prior_components = PrioritizedComponent.objects.filter(
        group_answer__respondent__isnull=True).distinct()
    for prior_component in alone_prior_components:
        new_group = prior_component.group_answer.group
        if new_group in prior_component.component.groups.all():
            continue
        prior_component.component.groups.add(new_group)
        prior_component.component.save()


def assign_priority(apps, schema_editor):
    PrioritizedComponent = apps.get_model(
        'intl_medicine', 'PrioritizedComponent')
    prior_components = PrioritizedComponent.objects.filter(
        group_answer__respondent__isnull=True,
        is_prioritized=True).distinct()
    for prior_component in prior_components:
        if prior_component.component.priority < 10:
            continue
        prior_component.component.priority = 5
        prior_component.component.save()


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups),
        migrations.RunPython(assign_priority),
    ]
