# Generated by Django 4.1.6 on 2023-08-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='groups',
            field=models.ManyToManyField(related_name='presentations', to='medicine.group'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_presentations', to='medicine.group'),
        ),
    ]
