# Generated by Django 4.1.6 on 2024-11-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_viewmedicine_remove_container_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
