# Generated by Django 4.1.6 on 2023-04-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20220308_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Componente', 'verbose_name_plural': '2. Componentes'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Recipiente (Contenedor)', 'verbose_name_plural': '4. Recipientes (Contenedores)'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupo Terapeútico', 'verbose_name_plural': '1. Grupos Terapeúticos'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Presentación del componente', 'verbose_name_plural': '3. Presentaciones del componente'},
        ),
        migrations.AlterModelOptions(
            name='presentationtype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de presentación', 'verbose_name_plural': '0. Tipos de presentación'},
        ),
        migrations.AddField(
            model_name='component',
            name='medicine_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
