# Generated by Django 4.1.6 on 2023-08-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_presentation_groups_alter_presentation_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Componente', 'verbose_name_plural': '2. Componentes'},
        ),
        migrations.AddField(
            model_name='component',
            name='priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterModelTable(
            name='component',
            table='medicine_component',
        ),
        migrations.AlterModelTable(
            name='container',
            table='medicine_container',
        ),
        migrations.AlterModelTable(
            name='group',
            table='medicine_group',
        ),
        migrations.AlterModelTable(
            name='presentation',
            table='medicine_presentation',
        ),
        migrations.AlterModelTable(
            name='presentationtype',
            table='medicine_presentationtype',
        ),
    ]
