# Generated by Django 4.1.13 on 2024-11-06 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_datebreak_group_alter_filetype_group_and_more'),
        ('medicine', '0003_component_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='unidecode_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='status_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers_review', to='category.statuscontrol'),
        ),
    ]
