# Generated by Django 4.1.6 on 2023-08-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_component_options_component_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='presentations', to='medicine.group'),
        ),
    ]
