# Generated by Django 4.1.6 on 2024-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_component_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Fuente de catálogo',
                'verbose_name_plural': 'Fuentes de catálogo',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='sources',
            field=models.ManyToManyField(blank=True, to='medicine.source'),
        ),
    ]
