# Generated by Django 4.1.6 on 2024-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_source_container_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='adverse_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Efectos adversos'),
        ),
        migrations.AddField(
            model_name='component',
            name='alternative_names',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Otros nombres'),
        ),
        migrations.AddField(
            model_name='component',
            name='contraindications',
            field=models.TextField(blank=True, null=True, verbose_name='Contraindicaciones y precauciones'),
        ),
        migrations.AddField(
            model_name='component',
            name='generalities',
            field=models.TextField(blank=True, null=True, verbose_name='Generalidades'),
        ),
        migrations.AddField(
            model_name='component',
            name='interactions',
            field=models.TextField(blank=True, null=True, verbose_name='Interacciones'),
        ),
        migrations.AddField(
            model_name='component',
            name='pregnancy_risks',
            field=models.TextField(blank=True, null=True, verbose_name='Riesgos en el embarazo'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='content_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='indications',
            field=models.TextField(blank=True, null=True, verbose_name='Indicaciones'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='way',
            field=models.TextField(blank=True, null=True, verbose_name='Vía de administración'),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
