# Generated by Django 4.1.6 on 2024-01-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_component_adverse_effects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['number'], 'verbose_name': 'Grupo Terapeútico', 'verbose_name_plural': '1. Grupos Terapeúticos'},
        ),
        migrations.AddField(
            model_name='component',
            name='containers_count',
            field=models.IntegerField(default=0, verbose_name='Cont.'),
        ),
        migrations.AddField(
            model_name='component',
            name='groups_count',
            field=models.IntegerField(default=0, verbose_name='Gpos'),
        ),
        migrations.AddField(
            model_name='component',
            name='groups_pc_count',
            field=models.IntegerField(default=0, verbose_name='Gpos. priori'),
        ),
        migrations.AddField(
            model_name='component',
            name='presentations_count',
            field=models.IntegerField(default=0, verbose_name='Pres.'),
        ),
        migrations.AddField(
            model_name='group',
            name='need_survey',
            field=models.BooleanField(default=True),
        ),
    ]
