# Generated by Django 4.1.6 on 2024-04-25 01:24

from django.db import migrations, models


def add_groups(apps, schema_editor):
    PrioritizedComponent = apps.get_model('intl_medicine', 'PrioritizedComponent')
    alone_prior_components = PrioritizedComponent.objects.filter(
        group_answer__respondent__isnull=True).distinct()
    for prior_component in alone_prior_components:
        new_group = prior_component.group_answer.group
        if new_group in prior_component.component.groups.all():
            continue
        prior_component.component.groups.add(new_group)
        prior_component.component.save()


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_group_options_component_containers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='components', to='medicine.group'),
        ),
        migrations.RunPython(add_groups),
    ]
