# Generated by Django 4.1.6 on 2024-04-25 01:24

from django.db import migrations, models


def assign_priority(apps, schema_editor):
    PrioritizedComponent = apps.get_model('intl_medicine', 'PrioritizedComponent')
    prior_components = PrioritizedComponent.objects.filter(
        group_answer__respondent__isnull=True,
        is_prioritized=True).distinct()
    for prior_component in prior_components:
        if prior_component.component.priority < 10:
            continue
        prior_component.component.priority = 5
        prior_component.component.save()


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_component_groups'),
    ]

    operations = [
        migrations.RunPython(assign_priority),
    ]
