# Generated by Django 4.1.6 on 2023-04-23 05:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('data_param', '0001_initial'),
        ('med_cat', '0001_initial'),
        ('inai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('prescribed_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delivered_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('delivered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
                ('lap_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.lapsheet')),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.medicament')),
            ],
            options={
                'verbose_name': 'Insumos',
                'verbose_name_plural': 'Insumos (medicamentos)',
            },
        ),
        migrations.CreateModel(
            name='MedicalSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Especialidad de Médico',
                'verbose_name_plural': 'Especialidades de Médicos',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('uuid_folio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio_ocamis', models.CharField(max_length=60)),
                ('folio_document', models.CharField(max_length=46)),
                ('iso_year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('iso_week', models.PositiveSmallIntegerField()),
                ('iso_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_release', models.DateTimeField(blank=True, null=True)),
                ('date_delivery', models.DateTimeField(blank=True, null=True)),
                ('date_visit', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.area')),
                ('delivered_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.diagnosis')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.doctor')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.entity')),
                ('medical_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.medicalunit')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='MissingRow',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_data', models.JSONField(blank=True, null=True)),
                ('inserted', models.BooleanField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.drug')),
                ('sheet_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_rows', to='inai.sheetfile')),
            ],
            options={
                'verbose_name': 'Renglón faltante',
                'verbose_name_plural': 'Renglones faltantes',
            },
        ),
        migrations.CreateModel(
            name='MissingField',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('final_value', models.TextField(blank=True, null=True)),
                ('other_values', models.JSONField(blank=True, null=True)),
                ('last_revised', models.DateTimeField()),
                ('inserted', models.BooleanField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('missing_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula.missingrow')),
                ('name_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_param.namecolumn')),
            ],
            options={
                'verbose_name': 'Documento Faltante',
                'verbose_name_plural': 'Documentos Faltantes',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='formula.prescription'),
        ),
        migrations.AddField(
            model_name='drug',
            name='sheet_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.sheetfile'),
        ),
    ]
