# Generated by Django 2.2.25 on 2022-07-26 19:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0008_auto_20220719_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('short_name', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Clasificación de entrega',
                'verbose_name_plural': 'Clasificaciones de Entrega',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('clave_doctor', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_medico', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'DocumentType',
                'verbose_name_plural': 'DocumentTypes',
            },
        ),
        migrations.CreateModel(
            name='Droug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prescrita', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cantidad_entregada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('precio_medicamento', models.FloatField(blank=True, null=True)),
                ('row_seq', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Insumos',
                'verbose_name_plural': 'Insumos (medicamentos)',
            },
        ),
        migrations.CreateModel(
            name='MedicalSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MedicalSpeciality',
                'verbose_name_plural': 'MedicalSpecialitys',
            },
        ),
        migrations.CreateModel(
            name='MissingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_value', models.TextField(blank=True, null=True)),
                ('final_value', models.TextField(blank=True, null=True)),
                ('other_values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento Faltante',
                'verbose_name_plural': 'Documentos Faltantes',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('folio_ocamis', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('iso_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('iso_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('folio_documento', models.CharField(max_length=40)),
                ('iso_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('clave_presupuestal', models.CharField(blank=True, max_length=20, null=True)),
                ('clues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.CLUES')),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Delegation')),
                ('delivered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.Delivered')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.Doctor')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.DocumentType')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='MissingRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('row_seq', models.IntegerField(default=1)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('droug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.Droug')),
            ],
            options={
                'verbose_name': 'Renglón faltante',
                'verbose_name_plural': 'Renglones faltantes',
            },
        ),
    ]
