# Generated by Django 2.2.25 on 2022-07-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formula', '0001_initial'),
        ('inai', '0001_initial'),
        ('medicine', '0002_auto_20220308_1847'),
        ('geo', '0008_auto_20220719_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingrow',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.DataFile'),
        ),
        migrations.AddField(
            model_name='missingrow',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.Prescription'),
        ),
        migrations.AddField(
            model_name='missingfield',
            name='missing_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula.MissingRow'),
        ),
        migrations.AddField(
            model_name='missingfield',
            name='name_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.NameColumn'),
        ),
        migrations.AddField(
            model_name='droug',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Container'),
        ),
        migrations.AddField(
            model_name='droug',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.DataFile'),
        ),
        migrations.AddField(
            model_name='droug',
            name='delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.Delivered'),
        ),
        migrations.AddField(
            model_name='droug',
            name='recipe_prescr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula.Prescription'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.MedicalSpeciality'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Institution'),
        ),
    ]
