# Generated by Django 4.1.6 on 2023-05-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
        ('med_cat', '0001_initial'),
        ('formula', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prescription',
            new_name='Rx',
        ),
    ]
