# Generated by Django 4.1.6 on 2024-08-13 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_delegation_clues_alter_clues_provider'),
        ('inai', '0003_alter_monthrecord_cluster'),
        ('rds', '0003_rename_comment_operation_notes_and_more'),
        ('med_cat', '0001_initial'),
        ('formula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatDrugTotals2',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescribed_total', models.IntegerField()),
                ('delivered_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cluster', models.ForeignKey(blank=True, default='first', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rds.cluster')),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation')),
                ('delivered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
                ('week_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.weekrecord')),
            ],
            options={
                'db_table': 'mat_drug_totals2',
            },
        ),
    ]
