# Generated by Django 2.2.25 on 2022-08-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_auto_20220726_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AlterModelOptions(
            name='medicalspeciality',
            options={'verbose_name': 'Especialidad de Médico', 'verbose_name_plural': 'Especialidades de Médicos'},
        ),
    ]
