# Generated by Django 4.1.6 on 2023-05-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_rename_prescription_rx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='prescription',
            new_name='rx',
        ),
    ]
