# Generated by Django 4.1.5 on 2023-01-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0003_auto_20220817_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingfield',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingfield',
            name='other_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingrow',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingrow',
            name='original_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
