# Generated by Django 4.1.6 on 2023-05-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0003_rename_prescription_drug_rx'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rx',
            table='formula_rx',
        ),
    ]
