# Generated by Django 4.1.6 on 2023-05-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0004_alter_rx_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rx',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
