# Generated by Django 4.1.6 on 2023-05-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0005_rx_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rx',
            name='iso_delegation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rx',
            name='folio_ocamis',
            field=models.CharField(max_length=64),
        ),
    ]
