# Generated by Django 4.1.6 on 2023-02-24 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0023_area_rename_tipology_typology_and_more'),
        ('medicine', '0002_auto_20220308_1847'),
        ('inai', '0047_filecontrol_all_results'),
        ('formula', '0005_remove_doctor_especialidad_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('short_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clasificación de entrega',
                'verbose_name_plural': 'Clasificaciones de Entrega',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cie10', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('motive', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave_doctor', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_medico', models.CharField(max_length=255)),
                ('professional_license', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescribed_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delivered_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('not_delivered_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('row_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('rn', models.CharField(blank=True, max_length=80, null=True)),
                ('for_training', models.CharField(blank=True, choices=[('medicine', 'Medicamentos'), ('clues', 'CLUES'), ('jurisdiction', 'Jurisdicción'), ('delivered', 'Clasificación Entrega'), ('diagnosis', 'Diagnóstico')], max_length=20, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.container')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.datafile')),
                ('delivered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.delivered')),
            ],
            options={
                'verbose_name': 'Insumos',
                'verbose_name_plural': 'Insumos (medicamentos)',
            },
        ),
        migrations.CreateModel(
            name='MedicalSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Especialidad de Médico',
                'verbose_name_plural': 'Especialidades de Médicos',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio_ocamis', models.CharField(max_length=48)),
                ('folio_document', models.CharField(max_length=40)),
                ('iso_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('iso_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('iso_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_release', models.DateTimeField(blank=True, null=True)),
                ('date_delivery', models.DateTimeField(blank=True, null=True)),
                ('date_visit', models.DateTimeField(blank=True, null=True)),
                ('budget_key', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.area')),
                ('clues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.clues')),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.delegation')),
                ('delivered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.delivered')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.doctor')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.documenttype')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='MissingRow',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_data', models.JSONField(blank=True, null=True)),
                ('row_seq', models.IntegerField(default=1)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.drug')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.datafile')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.prescription')),
            ],
            options={
                'verbose_name': 'Renglón faltante',
                'verbose_name_plural': 'Renglones faltantes',
            },
        ),
        migrations.CreateModel(
            name='MissingField',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('final_value', models.TextField(blank=True, null=True)),
                ('other_values', models.JSONField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('missing_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula.missingrow')),
                ('name_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.namecolumn')),
            ],
            options={
                'verbose_name': 'Documento Faltante',
                'verbose_name_plural': 'Documentos Faltantes',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula.prescription'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.medicalspeciality'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.institution'),
        ),
    ]
