# Generated by Django 4.1.6 on 2023-02-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_clues_key_issste'),
        ('formula', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.delegation'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='folio_ocamis',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='iso_week',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='iso_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
