# Generated by Django 4.1.6 on 2023-05-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0006_rx_iso_delegation_alter_rx_folio_ocamis'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
