# Generated by Django 4.1.6 on 2023-02-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0007_prescription_month_alter_prescription_delegation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingrow',
            old_name='file',
            new_name='data_file',
        ),
        migrations.RemoveField(
            model_name='missingfield',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='errors',
        ),
        migrations.AddField(
            model_name='missingfield',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingrow',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='formula.prescription'),
        ),
        migrations.AlterField(
            model_name='missingrow',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_rows', to='formula.prescription'),
        ),
    ]
