# Generated by Django 4.1.6 on 2023-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0007_drug_date_closed_drug_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='sheet_file',
            field=models.IntegerField(),
        ),
    ]
