# Generated by Django 4.1.6 on 2023-07-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0008_alter_drug_sheet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='entity_week_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='lap_sheet',
            field=models.IntegerField(),
        ),
    ]
