# Generated by Django 4.1.6 on 2023-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0008_rename_file_missingrow_data_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='delivered',
            new_name='delivered_final',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='uuid',
            new_name='uuid_folio',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='not_delivered_amount',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='type_document',
        ),
        migrations.AddField(
            model_name='prescription',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
