# Generated by Django 4.1.6 on 2023-03-02 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0049_filecontrol_decode_alter_namecolumn_final_field'),
        ('formula', '0009_rename_delivered_prescription_delivered_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='data_file',
        ),
        migrations.AddField(
            model_name='prescription',
            name='data_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inai.datafile'),
            preserve_default=False,
        ),
    ]
