# Generated by Django 4.1.6 on 2023-07-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0009_drug_entity_week_id_alter_drug_lap_sheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='lap_sheet',
            new_name='lap_sheet_id',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='sheet_file',
            new_name='sheet_file_id',
        ),
    ]
