# Generated by Django 4.1.6 on 2023-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0010_remove_drug_data_file_prescription_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingfield',
            name='name_column',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
