# Generated by Django 4.1.6 on 2023-08-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0011_alter_rx_table_complementrx_complementdrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementrx',
            name='area',
        ),
        migrations.RemoveField(
            model_name='complementrx',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='complementrx',
            name='rx',
        ),
        migrations.DeleteModel(
            name='ComplementDrug',
        ),
        migrations.DeleteModel(
            name='ComplementRx',
        ),
    ]
