# Generated by Django 4.1.6 on 2023-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0012_remove_complementrx_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDrugLosartan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total')),
            ],
            options={
                'verbose_name': 'Dato Losartan',
                'verbose_name_plural': 'Datos Losartan',
                'db_table': 'mother_drug_losartan',
                'managed': False,
            },
        ),
    ]
