# Generated by Django 4.1.6 on 2023-09-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_component_description'),
        ('med_cat', '0002_delivered_is_cancelled'),
        ('geo', '0011_alter_entity_options'),
        ('inai', '0059_entitymonth_last_validate'),
        ('formula', '0012_remove_complementrx_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatDrugTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_total', models.IntegerField()),
                ('delivered_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('clues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.clues')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.delegation')),
                ('delivered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
                ('entity_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.entityweek')),
            ],
            options={
                'db_table': 'mat_drug_totals',
            },
        ),
        migrations.CreateModel(
            name='MatDrugPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('prescribed_total', models.IntegerField()),
                ('delivered_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('clues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.clues')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.container')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.delegation')),
                ('delivered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
                ('entity_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.entityweek')),
            ],
            options={
                'db_table': 'mat_drug_priority',
            },
        ),
        migrations.CreateModel(
            name='MatDrugExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.PositiveSmallIntegerField()),
                ('iso_week', models.PositiveSmallIntegerField()),
                ('prescribed_total', models.IntegerField()),
                ('delivered_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.component')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.container')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.delegation')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.entity')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.presentation')),
            ],
            options={
                'db_table': 'mat_drug_extended',
            },
        ),
        migrations.CreateModel(
            name='MatDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('prescribed_total', models.IntegerField()),
                ('delivered_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('clues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.clues')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.container')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.delegation')),
                ('delivered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
                ('entity_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inai.entityweek')),
            ],
            options={
                'db_table': 'mat_drug',
            },
        ),
    ]
