# Generated by Django 4.1.6 on 2023-03-10 01:50

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0012_alter_missingfield_name_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='budget_key',
        ),
        migrations.AddField(
            model_name='missingfield',
            name='inserted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingfield',
            name='last_revised',
            field=models.DateTimeField(default=datetime(2023, 3, 10, 1, 50, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingrow',
            name='inserted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingrow',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
