# Generated by Django 4.1.6 on 2023-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0013_motherdruglosartan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDrugPriority',
            fields=[
                ('key', models.CharField(db_column='key', max_length=255, primary_key=True, serialize=False)),
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total')),
            ],
            options={
                'verbose_name': 'Dato Prioridad',
                'verbose_name_plural': 'Datos Prioridad',
                'db_table': 'mother_drug_priority',
                'managed': False,
            },
        ),
    ]
