# Generated by Django 4.1.6 on 2023-09-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_alter_entity_options'),
        ('formula', '0013_matdrugtotals_matdrugpriority_matdrugextended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matdrugtotals',
            name='clues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.clues'),
        ),
        migrations.AlterField(
            model_name='matdrugtotals',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation'),
        ),
    ]
