# Generated by Django 4.1.6 on 2023-03-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0057_remove_datafile_sheets_to_insert_datafile_csv_file_and_more'),
        ('formula', '0013_remove_prescription_budget_key_missingfield_inserted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='for_training',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='sheet_name',
        ),
        migrations.AddField(
            model_name='drug',
            name='data_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inai.datafile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
