# Generated by Django 4.1.6 on 2023-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0014_motherdrugpriority'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherDrugTotals',
            fields=[
                ('prescribed_total', models.IntegerField(db_column='prescribed')),
                ('delivered_total', models.IntegerField(db_column='delivered')),
                ('total', models.IntegerField(db_column='total', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Dato Total',
                'verbose_name_plural': 'Datos Totales',
                'db_table': 'mother_drug_totals',
                'managed': False,
            },
        ),
    ]
