# Generated by Django 4.1.6 on 2023-03-22 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0058_remove_datafile_sheets_info_datafile_filtered_sheets_and_more'),
        ('formula', '0014_remove_drug_for_training_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingrow',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='row_seq',
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='sheet_name',
        ),
        migrations.AddField(
            model_name='missingrow',
            name='table_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='missing_rows', to='inai.tablefile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.diagnosis'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad_medico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
