# Generated by Django 4.1.6 on 2023-03-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0015_remove_missingrow_data_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='rn',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='aggregate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.diagnosis'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='is_aggregate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='aggregate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_aggregate',
            field=models.BooleanField(default=False),
        ),
    ]
