# Generated by Django 4.1.6 on 2023-03-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_remove_area_delegation_area_institution_area_state'),
        ('formula', '0016_remove_drug_rn_remove_prescription_is_valid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='clave_doctor',
            new_name='clave',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='nombre_medico',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='especialidad_medico',
            new_name='medical_speciality',
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.state'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.institution'),
        ),
    ]
