# Generated by Django 4.1.6 on 2023-10-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0016_complementrx_complementdrug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complementdrug',
            old_name='uuid',
            new_name='uuid_comp_drug',
        ),
        migrations.RenameField(
            model_name='complementrx',
            old_name='uuid',
            new_name='uuid_comp_rx',
        ),
    ]
