# Generated by Django 4.1.6 on 2024-03-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0001_initial'),
        ('formula', '0017_rename_uuid_complementdrug_uuid_comp_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingrow',
            name='sheet_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_rows', to='respond.sheetfile'),
        ),
    ]
