# Generated by Django 4.1.6 on 2024-03-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0018_alter_missingrow_sheet_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matdrugextended',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='rx',
            old_name='entity',
            new_name='provider',
        ),
    ]
