# Generated by Django 4.1.6 on 2023-03-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0018_remove_diagnosis_id_diagnosis_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingrow',
            name='table_file',
        ),
    ]
