# Generated by Django 4.1.6 on 2023-03-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0066_sheetfile_alter_tablefile_unique_together_and_more'),
        ('formula', '0019_remove_missingrow_table_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingrow',
            name='sheet_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='missing_rows', to='inai.sheetfile'),
            preserve_default=False,
        ),
    ]
