# Generated by Django 4.1.6 on 2024-03-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0019_rename_entity_matdrugextended_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='entity_week_id',
            new_name='week_record_id',
        ),
        migrations.RenameField(
            model_name='matdrug',
            old_name='entity_week',
            new_name='week_record',
        ),
        migrations.RenameField(
            model_name='matdrugpriority',
            old_name='entity_week',
            new_name='week_record',
        ),
        migrations.RenameField(
            model_name='matdrugtotals',
            old_name='entity_week',
            new_name='week_record',
        ),
    ]
