# Generated by Django 4.1.6 on 2024-04-21 01:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0006_rename_entity_area_provider_and_more'),
        ('formula', '0020_rename_entity_week_id_drug_week_record_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementrx',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='rx',
            name='area',
        ),
        migrations.RemoveField(
            model_name='rx',
            name='diagnosis',
        ),
        migrations.CreateModel(
            name='DiagnosisRx',
            fields=[
                ('uuid_diag_rx', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_cat.diagnosis')),
                ('rx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='formula.rx')),
            ],
            options={
                'verbose_name': 'Diagnóstico por Receta',
                'verbose_name_plural': 'Diagnósticos por Receta',
            },
        ),
    ]
