# Generated by Django 4.1.6 on 2023-04-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_remove_area_state_area_delegation'),
        ('formula', '0020_missingrow_sheet_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='state',
        ),
        migrations.AddField(
            model_name='doctor',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.delegation'),
        ),
    ]
