# Generated by Django 4.1.6 on 2023-04-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0021_remove_doctor_state_doctor_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='hex_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hex_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
