# Generated by Django 4.1.6 on 2024-04-25 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0006_rename_entity_area_provider_and_more'),
        ('geo', '0019_alter_provider_options_provider_variables'),
        ('formula', '0021_remove_complementrx_diagnosis_remove_rx_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatDrugEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_year', models.PositiveSmallIntegerField()),
                ('iso_week', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('prescribed_total', models.IntegerField()),
                ('delivered_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('delivered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.provider')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_cat.medicament')),
            ],
            options={
                'db_table': 'mat_drug_entity',
            },
        ),
    ]
