# Generated by Django 4.1.6 on 2023-04-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0022_diagnosis_hex_hash_doctor_hex_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='aggregate_to',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='aggregate_to',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='delegation',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='institution',
        ),
    ]
