# Generated by Django 4.1.6 on 2024-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0022_matdrugentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='price',
        ),
        migrations.AddField(
            model_name='complementdrug',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
