# Generated by Django 4.1.6 on 2024-06-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0023_remove_drug_price_complementdrug_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='date_closed',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='date_created',
        ),
        migrations.AddField(
            model_name='rx',
            name='days_between',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
