# Generated by Django 4.1.6 on 2023-04-10 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0043_remove_clues_jurisdiction_obj_clues_delegation_and_more'),
        ('med_cat', '0002_remove_area_delegation_remove_area_hex_hash_and_more'),
        ('formula', '0024_alter_prescription_area_alter_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='clues',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='delegation',
        ),
        migrations.AddField(
            model_name='prescription',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_unity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='med_cat.medicalunity'),
            preserve_default=False,
        ),
    ]
