# Generated by Django 4.1.6 on 2023-04-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0003_rename_hash_area_hex_hash_and_more'),
        ('formula', '0025_remove_prescription_clues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='container',
        ),
        migrations.AddField(
            model_name='drug',
            name='medicament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.medicament'),
        ),
    ]
