# Generated by Django 4.1.6 on 2023-04-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0026_remove_drug_container_drug_medicament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medical_unity',
            new_name='medical_unit',
        ),
    ]
