# Generated by Django 4.1.6 on 2023-04-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inai', '0075_tablefile_inserted_alter_lapsheet_inserted'),
        ('formula', '0027_rename_medical_unity_prescription_medical_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='sheet_name',
        ),
        migrations.AddField(
            model_name='drug',
            name='sheet_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inai.sheetfile'),
        ),
    ]
