# Generated by Django 4.1.6 on 2023-04-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0028_remove_drug_data_file_remove_drug_sheet_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='area',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='delivered_final',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medical_unit',
        ),
        migrations.DeleteModel(
            name='Delivered',
        ),
    ]
