# Generated by Django 4.1.6 on 2023-04-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0008_delivered'),
        ('formula', '0029_remove_drug_delivered_remove_drug_medicament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='delivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered'),
        ),
        migrations.AddField(
            model_name='drug',
            name='medicament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.medicament'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.area'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='delivered_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.delivered'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.diagnosis'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='med_cat.medicalunit'),
            preserve_default=False,
        ),
    ]
