# Generated by Django 4.1.6 on 2023-04-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_cat', '0008_delivered'),
        ('formula', '0030_drug_delivered_drug_medicament_prescription_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medical_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med_cat.medicalunit'),
        ),
    ]
