# Generated by Django 4.1.6 on 2023-04-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0032_drug_lap_sheet_alter_drug_sheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='folio_document',
            field=models.CharField(max_length=46),
        ),
    ]
