# Generated by Django 2.2.25 on 2022-03-09 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Institution'),
        ),
        migrations.AlterField(
            model_name='clues',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.State'),
        ),
    ]
