# Generated by Django 4.1.6 on 2024-08-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='clues',
        ),
        migrations.AlterField(
            model_name='clues',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prov_clues', to='geo.provider'),
        ),
    ]
