# Generated by Django 2.2.25 on 2022-03-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20220308_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inegi_code', models.CharField(max_length=6, verbose_name='Clave INEGI')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.State', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
