# Generated by Django 4.1.6 on 2023-05-21 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_clues_table_alter_delegation_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='split_by_delegation',
            field=models.BooleanField(default=False, verbose_name='Dividir por delegación'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='geo.entity', verbose_name='Entidad'),
        ),
    ]
