# Generated by Django 4.1.13 on 2024-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_delegation_clues_alter_clues_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='alternative_codes',
            field=models.CharField(blank=True, help_text='Separadas por coma', max_length=255, null=True, verbose_name='CLAVES ALTERNATIVAS'),
        ),
    ]
