# Generated by Django 4.1.6 on 2023-06-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_entity_split_by_delegation_alter_agency_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='geo.state', verbose_name='Entidad'),
        ),
    ]
