# Generated by Django 4.1.6 on 2023-06-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_entity_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='geo.entity', verbose_name='Entidad'),
        ),
    ]
