# Generated by Django 4.1.6 on 2023-06-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_alter_entity_options_alter_entity_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_pilot',
            field=models.BooleanField(default=False, verbose_name='Es piloto'),
        ),
    ]
