# Generated by Django 4.1.6 on 2023-07-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_entity_assigned_to_entity_notes_entity_status_opera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['state__name'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
