# Generated by Django 4.1.6 on 2023-08-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_alter_entity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['inegi_code'], 'verbose_name': 'Entidad Federativa', 'verbose_name_plural': 'Entidades Federativas'},
        ),
        migrations.AlterModelTable(
            name='agency',
            table='geo_agency',
        ),
        migrations.AlterModelTable(
            name='state',
            table='geo_state',
        ),
    ]
