# Generated by Django 4.1.6 on 2023-08-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_alter_state_options_alter_agency_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['state__name'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores (Entities)'},
        ),
    ]
