# Generated by Django 4.1.6 on 2024-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_alter_entity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre corto'),
        ),
    ]
