# Generated by Django 4.1.6 on 2024-03-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_entity_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['state__name'], 'verbose_name': 'Sujeto Obligado (Agency)', 'verbose_name_plural': 'Sujetos Obligados (Agencies)'},
        ),
    ]
