# Generated by Django 4.1.6 on 2024-03-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0013_alter_agency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='has_indirect',
            field=models.BooleanField(default=False, verbose_name='Tiene indirectos'),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_indirect',
            field=models.BooleanField(default=False, verbose_name='Es indirecto (entidad Real)'),
        ),
    ]
