# Generated by Django 4.1.6 on 2024-03-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_covidreport_municipality_and_more'),
        ('geo', '0014_entity_has_indirect_entity_is_indirect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_pilot',
        ),
        migrations.DeleteModel(
            name='Alliances',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
