# Generated by Django 4.1.6 on 2024-03-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_pilot',
        ),
        migrations.DeleteModel(
            name='Alliances',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
