# Generated by Django 2.2.25 on 2022-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0015_auto_20220801_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='compentent',
        ),
        migrations.AddField(
            model_name='entity',
            name='competent',
            field=models.BooleanField(default=True, help_text='Es Competente porque tiene pacientes y debe tener la información', verbose_name='Competente'),
        ),
    ]
