# Generated by Django 4.1.6 on 2024-03-26 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_alter_asynctask_data_file_alter_asynctask_reply_file_and_more'),
        ('category', '0003_alter_fileformat_options'),
        ('respond', '0001_initial'),
        ('inai', '0068_alter_requesttemplate_options'),
        ('data_param', '0011_remove_filecontrol_format_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('med_cat', '0003_delivered_alternative_names'),
        ('formula', '0018_alter_missingrow_sheet_file'),
        ('geo', '0015_remove_entity_is_pilot_delete_alliances_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entity',
            new_name='Provider',
        ),
        migrations.AlterModelTable(
            name='provider',
            table='geo_entity',
        ),
    ]
