# Generated by Django 4.1.6 on 2024-03-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_rename_entity_provider_alter_provider_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='geo.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='geo.state', verbose_name='Estado'),
        ),
    ]
