# Generated by Django 4.1.6 on 2024-03-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0017_alter_provider_institution_alter_provider_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='entity',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='delegation',
            old_name='entity',
            new_name='provider',
        ),
    ]
