# Generated by Django 2.2.25 on 2022-08-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_entity_is_pilot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['inegi_code'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
