# Generated by Django 4.1.6 on 2024-05-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0019_alter_provider_options_provider_variables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='status_opera',
            new_name='old_status_opera',
        ),
    ]
