# Generated by Django 2.2.25 on 2023-01-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0020_entity_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='nameForInai',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre según INAI'),
        ),
    ]
