# Generated by Django 4.1.6 on 2024-05-02 20:52

from django.db import migrations, models
import django.db.models.deletion


def copy_old_values(apps, schema_editor):
    OldStatusControl = apps.get_model("category", "OldStatusControl")
    Provider = apps.get_model("geo", "Provider")
    for old_status in OldStatusControl.objects.all():
        Provider.objects.filter(old_status_opera=old_status)\
                .update(status_operative=old_status.name)


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_statuscontrol'),
        ('geo', '0020_rename_status_opera_provider_old_status_opera'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='status_operative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol', verbose_name='Status de los registro de variables'),
        ),
        migrations.RunPython(copy_old_values),
    ]
