# Generated by Django 4.1.6 on 2024-05-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0021_provider_status_opera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='old_status_opera',
        ),
    ]
