# Generated by Django 4.1.6 on 2023-02-24 09:35

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0022_alter_clues_alternative_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave del área')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Nombre del área')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.RenameModel(
            old_name='Tipology',
            new_name='Typology',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='tipology',
            new_name='typology',
        ),
        migrations.RenameField(
            model_name='clues',
            old_name='tipology_obj',
            new_name='typology_obj',
        ),
        migrations.RemoveField(
            model_name='clues',
            name='tipology_cve',
        ),
        migrations.AddField(
            model_name='clues',
            name='typology_cve',
            field=models.CharField(default='UNKNOWN', max_length=12, verbose_name='CLAVE DE TIPOLOGÍA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clues',
            name='atention_level',
            field=models.CharField(max_length=80, verbose_name='NIVEL ATENCIÓN'),
        ),
        migrations.AlterField(
            model_name='clues',
            name='jurisdiction',
            field=models.CharField(max_length=80, verbose_name='NOMBRE DE LA JURISDICCIÓN'),
        ),
        migrations.AlterField(
            model_name='clues',
            name='jurisdiction_clave',
            field=models.CharField(max_length=5, verbose_name='CLAVE DE LA JURISDICCIÓN'),
        ),
        migrations.AlterField(
            model_name='clues',
            name='status_operation',
            field=models.CharField(max_length=80, verbose_name='ESTATUS DE OPERACIÓN'),
        ),
        migrations.AlterField(
            model_name='state',
            name='alternative_names',
            field=models.JSONField(default=catalog.models.default_alternative_names, help_text='Ocupar para OCAMIS', verbose_name='Lista nombres alternativos'),
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('key', models.CharField(max_length=50, verbose_name='Clave')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.institution', verbose_name='Institución')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.state', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Jurisdicción',
                'verbose_name_plural': 'Jurisdicciones',
            },
        ),
        migrations.AddField(
            model_name='clues',
            name='jurisdiction_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jurisdictions', to='geo.jurisdiction', verbose_name='Jurisdicción Sanitaria'),
        ),
    ]
