# Generated by Django 4.1.6 on 2023-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0023_area_rename_tipology_typology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='key_issste',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CLAVE ISSSTE'),
        ),
    ]
