# Generated by Django 4.1.6 on 2023-03-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0028_alter_clues_key_issste_alter_clues_rfc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clues',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='clues',
            name='municipality_inegi_code',
        ),
    ]
