# Generated by Django 4.1.6 on 2023-03-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0029_remove_clues_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clues',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.municipality'),
        ),
        migrations.AddField(
            model_name='clues',
            name='municipality_inegi_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='clues',
            name='municipality_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NOMBRE DEL MUNICIPIO'),
        ),
    ]
