# Generated by Django 4.1.6 on 2023-03-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0030_clues_municipality_clues_municipality_inegi_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='rfc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RFC'),
        ),
    ]
