# Generated by Django 4.1.6 on 2023-03-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0031_alter_clues_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='typology_cve',
            field=models.CharField(max_length=13, verbose_name='CLAVE DE TIPOLOGÍA'),
        ),
    ]
