# Generated by Django 4.1.6 on 2023-03-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0032_alter_clues_typology_cve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='typology_cve',
            field=models.CharField(max_length=18, verbose_name='CLAVE DE TIPOLOGÍA'),
        ),
    ]
