# Generated by Django 4.1.6 on 2023-03-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0034_remove_area_id_area_delegation_area_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='aggregate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.area'),
        ),
        migrations.AddField(
            model_name='area',
            name='is_aggregate',
            field=models.BooleanField(default=False),
        ),
    ]
