# Generated by Django 4.1.6 on 2023-04-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0036_remove_area_delegation_area_institution_area_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='state',
        ),
        migrations.AddField(
            model_name='area',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.delegation'),
        ),
    ]
