# Generated by Django 4.1.6 on 2023-04-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0038_rename_entity_filecontrol_agency'),
        ('inai', '0069_rename_is_valid_sheetfile_valid_insert_and_more'),
        ('geo', '0037_remove_area_state_area_delegation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entity',
            new_name='Agency',
        ),
    ]
