# Generated by Django 4.1.6 on 2023-04-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0040_alter_agency_table_alter_area_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='aggregate_to',
        ),
        migrations.RemoveField(
            model_name='area',
            name='delegation',
        ),
        migrations.RemoveField(
            model_name='area',
            name='institution',
        ),
    ]
