# Generated by Django 4.1.6 on 2023-04-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0041_remove_area_aggregate_to_remove_area_delegation_and_more'),
        ('formula', '0024_alter_prescription_area_alter_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
