# Generated by Django 4.1.6 on 2023-04-10 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0042_delete_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clues',
            name='jurisdiction_obj',
        ),
        migrations.AddField(
            model_name='clues',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_clues', to='geo.delegation'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='is_clues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delegation',
            name='is_jurisdiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delegation',
            name='jurisdiction_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave de la Jurisdicción'),
        ),
        migrations.AddField(
            model_name='typology',
            name='aggregate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.typology'),
        ),
        migrations.AddField(
            model_name='typology',
            name='is_aggregate',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la entidad')),
                ('acronym', models.CharField(max_length=20, verbose_name='Clave de la entidad')),
                ('is_clues', models.BooleanField(default=False, verbose_name='Es solo un CLUES')),
                ('population', models.IntegerField(default=0, verbose_name='Población')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='geo.institution', verbose_name='Institución')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='geo.state', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.AddField(
            model_name='clues',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.entity'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.entity', verbose_name='Entidad'),
        ),
    ]
