# Generated by Django 4.1.6 on 2023-04-10 02:13

from django.db import migrations, models
import django.db.models.deletion
import geo.models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0043_remove_clues_jurisdiction_obj_clues_delegation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='geo.state', verbose_name=geo.models.State),
        ),
    ]
