# Generated by Django 4.1.6 on 2023-04-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0044_alter_municipality_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipality',
            table='catalog_municipality',
        ),
    ]
