# Generated by Django 4.1.6 on 2023-04-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0045_alter_municipality_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.entity', verbose_name='Entidad'),
        ),
    ]
