# Generated by Django 4.1.6 on 2023-04-11 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0046_agency_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clues',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ent_clues', to='geo.entity'),
        ),
    ]
