# Generated by Django 4.1.6 on 2023-04-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0047_alter_clues_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typology',
            name='is_aggregate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
