# Generated by Django 2.2.25 on 2022-07-11 15:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('model_name', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Coleccion',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='FinalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('verbose_name', models.TextField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.Collection')),
            ],
            options={
                'verbose_name': 'Documento final',
                'verbose_name_plural': 'Documentos finales',
            },
        ),
        migrations.CreateModel(
            name='GroupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Grupo de datos',
                'verbose_name_plural': 'Grupos de datos',
            },
        ),
        migrations.CreateModel(
            name='GroupParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.GroupData')),
            ],
            options={
                'verbose_name': 'Grupo Parametro',
                'verbose_name_plural': 'Grupo Parametros',
            },
        ),
        migrations.CreateModel(
            name='TypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('addl_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_common', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tipo de dato',
                'verbose_name_plural': 'Tipos de datos',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_name', models.CharField(max_length=255)),
                ('variations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('almost_requiered', models.BooleanField(default=False)),
                ('is_common', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('addl_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('final_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.FinalField')),
                ('group_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.GroupParameter')),
            ],
            options={
                'verbose_name': 'Parametro',
                'verbose_name_plural': 'Parametros',
            },
        ),
        migrations.AddField(
            model_name='finalfield',
            name='type_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.TypeData'),
        ),
    ]
