# Generated by Django 2.2.25 on 2022-07-20 00:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import parameter.models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pririty', models.SmallIntegerField(default=5, verbose_name='Nivel de prioridad (5 niveles)')),
                ('for_all_data', models.BooleanField(default=False, verbose_name='Es una tranformación para toda la info')),
            ],
            options={
                'verbose_name': 'Función de Transformación',
                'verbose_name_plural': 'Funciones de transformación',
            },
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Modelo (Tabla)', 'verbose_name_plural': 'Modelos o Tablas'},
        ),
        migrations.AlterModelOptions(
            name='groupparameter',
            options={'verbose_name': 'Grupo de Parametros', 'verbose_name_plural': 'Grupos de Parametros'},
        ),
        migrations.AddField(
            model_name='finalfield',
            name='addl_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Otras configuraciones'),
        ),
        migrations.AddField(
            model_name='groupdata',
            name='can_has_percent',
            field=models.BooleanField(default=False, verbose_name='Puede tener porcentajes'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='model_name',
            field=models.CharField(max_length=225, verbose_name='Nombre en el código'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='addl_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Otras configuraciones'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='almost_requiered',
            field=models.BooleanField(default=False, verbose_name='Es casi indispensable'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Es un parámetro común'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='variations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Variaciones comunes del nombre'),
        ),
        migrations.AlterField(
            model_name='typedata',
            name='addl_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=parameter.models.TypeData.default_params_type_data, verbose_name='Otras configuraciones'),
        ),
        migrations.AlterField(
            model_name='typedata',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
