# Generated by Django 2.2.25 on 2022-07-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0002_remove_column_tranformations'),
        ('parameter', '0002_auto_20220719_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transformation',
        ),
    ]
