# Generated by Django 2.2.25 on 2022-07-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_delete_transformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pririty', models.SmallIntegerField(default=5, verbose_name='Nivel de prioridad (5 niveles)')),
                ('for_all_data', models.BooleanField(default=False, verbose_name='Es una tranformación para toda la info')),
                ('restricted_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.FinalField', verbose_name='Campo final al cual solo puede aplicarse')),
            ],
            options={
                'verbose_name': 'Función de Transformación',
                'verbose_name_plural': 'Funciones de transformación',
            },
        ),
    ]
