# Generated by Django 2.2.25 on 2022-07-25 19:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0008_remove_namecolumn_parameter'),
        ('parameter', '0004_cleanfunction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='final_field',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='group_parameter',
        ),
        migrations.AddField(
            model_name='cleanfunction',
            name='addl_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Otras configuraciones'),
        ),
        migrations.DeleteModel(
            name='GroupParameter',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
