# Generated by Django 2.2.25 on 2022-07-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0005_auto_20220725_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanfunction',
            old_name='pririty',
            new_name='priority',
        ),
    ]
