# Generated by Django 2.2.25 on 2022-07-26 18:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import parameter.models


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0011_auto_20220726_1321'),
        ('parameter', '0006_auto_20220725_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('addl_params', django.contrib.postgres.fields.jsonb.JSONField(default=parameter.models.DataType.default_params_data_type, verbose_name='Otras configuraciones')),
                ('is_common', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Tipo de dato',
                'verbose_name_plural': 'Tipos de datos',
            },
        ),
        migrations.RenameModel(
            old_name='GroupData',
            new_name='DataGroup',
        ),
        migrations.AlterModelOptions(
            name='cleanfunction',
            options={'verbose_name': 'Función de limpieza y tranformación', 'verbose_name_plural': 'Funciones de limpieza y tranformación'},
        ),
        migrations.RemoveField(
            model_name='finalfield',
            name='type_data',
        ),
        migrations.AddField(
            model_name='collection',
            name='data_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parameter.DataGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalfield',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Es una variable muy común'),
        ),
        migrations.AddField(
            model_name='finalfield',
            name='requiered',
            field=models.BooleanField(default=False, verbose_name='Es indispensable para registrar fila'),
        ),
        migrations.AddField(
            model_name='finalfield',
            name='variatrions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Otros posibles nombres'),
        ),
        migrations.AddField(
            model_name='finalfield',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verificado (solo devs)'),
        ),
        migrations.AlterField(
            model_name='finalfield',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='TypeData',
        ),
        migrations.AddField(
            model_name='finalfield',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.DataType'),
        ),
    ]
