# Generated by Django 2.2.25 on 2022-07-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0013_auto_20220726_1347'),
        ('parameter', '0007_auto_20220726_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='data_group',
        ),
        migrations.RemoveField(
            model_name='finalfield',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='finalfield',
            name='data_type',
        ),
        migrations.DeleteModel(
            name='CleanFunction',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='DataGroup',
        ),
        migrations.DeleteModel(
            name='DataType',
        ),
        migrations.DeleteModel(
            name='FinalField',
        ),
    ]
