# Generated by Django 2.2.25 on 2022-07-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('public_name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Columna',
                'verbose_name_plural': 'Tipos de columnas',
            },
        ),
        migrations.CreateModel(
            name='FormatFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('has_data', models.NullBooleanField(verbose_name='Tiene datos procesables')),
                ('icon', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Formato de documento',
                'verbose_name_plural': 'Formato de documentos',
            },
        ),
        migrations.CreateModel(
            name='StatusProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('public_name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado del proceso',
                'verbose_name_plural': 'Estados de procesos',
            },
        ),
        migrations.CreateModel(
            name='TypeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('has_data', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('default_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_categories.FormatFile')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
    ]
