# Generated by Django 2.2.25 on 2022-07-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0003_auto_20220721_1831'),
        ('files_categories', '0002_negativereason_statuscontrol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusProcessing',
        ),
        migrations.RemoveField(
            model_name='typefile',
            name='default_format',
        ),
        migrations.AlterField(
            model_name='typefile',
            name='order',
            field=models.IntegerField(default=15),
        ),
        migrations.DeleteModel(
            name='FormatFile',
        ),
    ]
