# Generated by Django 2.2.25 on 2022-07-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0011_auto_20220726_1321'),
        ('files_categories', '0003_auto_20220721_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeFile',
            new_name='FileType',
        ),
    ]
