# Generated by Django 2.2.25 on 2022-07-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0013_auto_20220726_1347'),
        ('files_categories', '0004_auto_20220726_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColumnType',
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.DeleteModel(
            name='NegativeReason',
        ),
        migrations.DeleteModel(
            name='StatusControl',
        ),
    ]
