# Generated by Django 4.1.13 on 2024-07-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_param', '0001_initial'),
        ('classify_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatView',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre público')),
                ('description', models.TextField(blank=True, null=True)),
                ('script', models.TextField()),
                ('script_drop', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stage', models.ForeignKey(default='init_mat_view', on_delete=django.db.models.deletion.CASCADE, related_name='mvs', to='classify_task.stage', verbose_name='Etapa actual')),
                ('stage_belongs', models.ForeignKey(default='init_mat_view', on_delete=django.db.models.deletion.CASCADE, related_name='mat_views', to='classify_task.stage', verbose_name='Etapa de creación')),
                ('status', models.ForeignKey(default='finished', on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask')),
            ],
            options={
                'verbose_name': 'Materialized View',
                'verbose_name_plural': 'Materialized Views',
            },
        ),
        migrations.CreateModel(
            name='OperationGroup',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('low_priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Operaciones',
                'verbose_name_plural': 'Grupos de Operaciones',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('has_constrains', models.BooleanField(default=True)),
                ('create_constraints', models.JSONField(blank=True, null=True)),
                ('delete_constraints', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'db_table': 'rds_platform',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('clean', 'Limpiar de constrains'), ('constraint', 'constraint'), ('index', 'index'), ('materialized', 'materialized view'), ('union', 'union'), ('index_union', 'index of consolidated materialized view')], max_length=20)),
                ('order', models.IntegerField(default=40)),
                ('low_priority', models.BooleanField(default=False, verbose_name='low')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('script', models.TextField()),
                ('script_drop', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.collection')),
                ('mat_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rds.matview')),
                ('operation_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rds.operationgroup')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-is_active', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre público')),
                ('stage', models.ForeignKey(default='init_cluster', on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa actual')),
                ('status', models.ForeignKey(default='finished', on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
            },
        ),
    ]
