# Generated by Django 4.1.6 on 2024-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('has_constrains', models.BooleanField(default=True)),
                ('create_constraints', models.JSONField(blank=True, null=True)),
                ('delete_constraints', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'db_table': 'rds_platform',
            },
        ),
    ]
