# Generated by Django 4.1.6 on 2024-08-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='icon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
