# Generated by Django 4.1.6 on 2024-06-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0020_alter_taskfunction_group_queue_and_more'),
        ('geo', '0023_rename_status_operative_provider_status_priority'),
        ('data_param', '0022_rename_new_data_group_collection_data_group_and_more'),
        ('rds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre público')),
                ('providers', models.ManyToManyField(blank=True, related_name='clusters', to='geo.provider')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
            },
        ),
        migrations.CreateModel(
            name='MatView',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre público')),
                ('description', models.TextField(blank=True, null=True)),
                ('script', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('stage', models.ForeignKey(default='init_mat_view', on_delete=django.db.models.deletion.CASCADE, related_name='mvs', to='classify_task.stage', verbose_name='Etapa actual')),
                ('stage_belongs', models.ForeignKey(default='init_mat_view', on_delete=django.db.models.deletion.CASCADE, related_name='mat_views', to='classify_task.stage', verbose_name='Etapa de creación')),
                ('status', models.ForeignKey(default='finished', on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask')),
            ],
            options={
                'verbose_name': 'Materialized View',
                'verbose_name_plural': 'Materialized Views',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('clean', 'Limpiar de constrains'), ('constraint', 'constraint'), ('index', 'index'), ('materialized', 'materialized view'), ('union', 'union'), ('index_union', 'index of consolidated materialized view')], max_length=20)),
                ('order', models.IntegerField(default=40)),
                ('low_priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('script', models.TextField()),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_param.collection')),
                ('mat_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rds.matview')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.CreateModel(
            name='ClusterYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rds.cluster')),
                ('stage', models.ForeignKey(default='init_cluster', on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa actual')),
                ('status', models.ForeignKey(default='finished', on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask')),
            ],
            options={
                'verbose_name': 'Cluster por año',
                'verbose_name_plural': 'Clusters por año',
            },
        ),
    ]
