# Generated by Django 4.1.13 on 2024-07-16 08:18

from django.db import migrations


def create_stage(apps, schema_editor):
    Stage = apps.get_model("classify_task", "Stage")
    Stage.objects.create(
        name='init_cluster', public_name='Inicial Cluster',
        stage_group='cluster', order=20)


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_stage),
    ]
