# Generated by Django 4.1.6 on 2024-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0002_cluster_matview_operation_clusteryear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['is_active', 'order'], 'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AddField(
            model_name='operation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
