# Generated by Django 4.1.6 on 2024-08-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_param', '0002_delete_dictionaryfile'),
        ('rds', '0002_cluster_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='comment',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='operation',
            name='collection_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_related', to='data_param.collection'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='data_param.collection'),
        ),
    ]
