# Generated by Django 4.1.6 on 2024-06-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0003_alter_operation_options_operation_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationGroup',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('low_priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Operaciones',
                'verbose_name_plural': 'Grupos de Operaciones',
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rds.operationgroup'),
        ),
    ]
