# Generated by Django 4.1.6 on 2024-06-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0004_operationgroup_operation_operation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='matview',
            name='script_drop',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='low_priority',
            field=models.BooleanField(default=False, verbose_name='low'),
        ),
    ]
