# Generated by Django 4.1.6 on 2024-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0005_matview_script_drop_alter_operation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='script_drop',
            field=models.TextField(blank=True, null=True),
        ),
    ]
