# Generated by Django 4.1.6 on 2024-06-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0006_operation_script_drop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-is_active', 'order'], 'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
    ]
