# Generated by Django 4.1.6 on 2024-06-19 01:13

from django.db import migrations, models
import django.db.models.deletion


def create_stage(apps, schema_editor):
    Stage = apps.get_model("classify_task", "Stage")
    Stage.objects.create(
        name='init_cluster', public_name='Inicial Cluster',
        stage_group='cluster', order=20)


class Migration(migrations.Migration):

    dependencies = [
        ('classify_task', '0020_alter_taskfunction_group_queue_and_more'),
        ('rds', '0007_alter_operation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='providers',
        ),
        migrations.RunPython(create_stage),
        migrations.AddField(
            model_name='cluster',
            name='stage',
            field=models.ForeignKey(default='init_cluster', on_delete=django.db.models.deletion.CASCADE, to='classify_task.stage', verbose_name='Etapa actual'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='status',
            field=models.ForeignKey(default='finished', on_delete=django.db.models.deletion.CASCADE, to='classify_task.statustask'),
        ),
    ]
