# Generated by Django 4.1.6 on 2024-06-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0008_remove_cluster_providers_cluster_stage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusterYear',
        ),
    ]
