# Generated by Django 2.2.25 on 2022-07-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='tranformations',
        ),
    ]
