# Generated by Django 2.2.25 on 2022-07-21 23:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_categories', '0002_negativereason_statuscontrol'),
        ('parameter', '0004_cleanfunction'),
        ('files_rows', '0002_remove_column_tranformations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addl_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('clean_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.CleanFunction', verbose_name='Función de limpieza o tranformación')),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_rows.Column', verbose_name='Columna')),
            ],
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='file',
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='recipe_medicine',
        ),
        migrations.RemoveField(
            model_name='missingrow',
            name='recipe_report',
        ),
        migrations.AddField(
            model_name='groupfile',
            name='other_format',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='groupfile',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_categories.StatusControl', verbose_name='Status de los registro de variables'),
        ),
        migrations.AddField(
            model_name='petition',
            name='ask_extension',
            field=models.NullBooleanField(verbose_name='Se solicitó extensión'),
        ),
        migrations.AddField(
            model_name='petition',
            name='limit_complain',
            field=models.DateTimeField(blank=True, null=True, verbose_name='límite para presentar queja'),
        ),
        migrations.AddField(
            model_name='petition',
            name='limit_pickup',
            field=models.DateTimeField(blank=True, null=True, verbose_name='límite para recoger datos'),
        ),
        migrations.AddField(
            model_name='petition',
            name='limit_response',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='negative_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_categories.NegativeReason', verbose_name='Razón de la negativa'),
        ),
        migrations.AddField(
            model_name='petition',
            name='status_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions_data', to='files_categories.StatusControl', verbose_name='Status de los datos entregados'),
        ),
        migrations.AddField(
            model_name='petition',
            name='status_petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitions_petition', to='files_categories.StatusControl', verbose_name='Status de la petición'),
        ),
        migrations.AlterField(
            model_name='file',
            name='status_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_categories.StatusControl'),
        ),
        migrations.AlterField(
            model_name='groupfile',
            name='format_file',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('word', 'Word'), ('xls', 'Excel'), ('txt', 'Texto'), ('csv', 'CSV'), ('email', 'Correo electrónico'), ('other', 'Otro')], max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='MissingField',
        ),
        migrations.DeleteModel(
            name='MissingRow',
        ),
        migrations.AddField(
            model_name='transformation',
            name='group_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_rows.GroupFile', verbose_name='Grupo de archivos'),
        ),
    ]
