# Generated by Django 2.2.25 on 2022-07-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0003_auto_20220721_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='petition_month',
        ),
        migrations.AddField(
            model_name='file',
            name='month_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_rows.MonthEntity'),
        ),
    ]
