# Generated by Django 2.2.25 on 2022-07-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_categories', '0003_auto_20220721_1831'),
        ('recipe', '0007_auto_20220722_1217'),
        ('parameter', '0004_cleanfunction'),
        ('files_rows', '0004_auto_20220722_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Column',
            new_name='NameColumn',
        ),
        migrations.AlterModelOptions(
            name='namecolumn',
            options={'verbose_name': 'Nombre de Columna', 'verbose_name_plural': 'Nombres de Columnas'},
        ),
    ]
