# Generated by Django 2.2.25 on 2022-07-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20220722_1451'),
        ('files_categories', '0003_auto_20220721_1831'),
        ('files_rows', '0005_auto_20220722_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='DataFile',
        ),
        migrations.CreateModel(
            name='ProcessFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ori_file', models.FileField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_rows.Petition')),
                ('type_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_categories.TypeFile')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
