# Generated by Django 2.2.25 on 2022-07-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0006_auto_20220725_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'verbose_name': 'Archivo con datos', 'verbose_name_plural': 'Archivos con datos'},
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='group_file',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='is_final',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='petition',
        ),
        migrations.AlterField(
            model_name='datafile',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='origin_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_files', to='files_rows.DataFile'),
        ),
    ]
