# Generated by Django 2.2.25 on 2022-07-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0007_auto_20220725_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namecolumn',
            name='parameter',
        ),
    ]
