# Generated by Django 2.2.25 on 2022-07-25 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0008_remove_namecolumn_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petitionmonth',
            old_name='monthentity',
            new_name='month_entity',
        ),
        migrations.AddField(
            model_name='datafile',
            name='petition_group_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='files_rows.PetitionGroupFile'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='catalog.Entity'),
        ),
        migrations.AlterField(
            model_name='petitiongroupfile',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_groups', to='files_rows.Petition'),
        ),
        migrations.AlterField(
            model_name='petitionmonth',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_months', to='files_rows.Petition'),
        ),
        migrations.AlterField(
            model_name='processfile',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_files', to='files_rows.Petition'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_tranformations', to='files_rows.NameColumn', verbose_name='Columna'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='group_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_tranformations', to='files_rows.GroupFile', verbose_name='Grupo de archivos'),
        ),
    ]
