# Generated by Django 2.2.25 on 2022-07-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0009_auto_20220725_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthentity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='catalog.Entity'),
        ),
        migrations.AlterField(
            model_name='namecolumn',
            name='group_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='files_rows.GroupFile'),
        ),
    ]
