# Generated by Django 2.2.25 on 2022-07-26 18:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import files_rows.models


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0010_auto_20220726_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='grupo único', max_length=120)),
                ('format_file', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('word', 'Word'), ('xls', 'Excel'), ('txt', 'Texto'), ('csv', 'CSV'), ('email', 'Correo electrónico'), ('other', 'Otro')], max_length=5, null=True)),
                ('other_format', models.CharField(blank=True, max_length=80, null=True)),
                ('final_data', models.BooleanField(verbose_name='Es información final')),
                ('notes', models.TextField(blank=True, null=True)),
                ('row_start_data', models.IntegerField(default=1, verbose_name='# de fila donde inician los datos')),
                ('row_headers', models.IntegerField(blank=True, null=True, verbose_name='# de fila donde se encuentran los encabezados')),
                ('in_percent', models.BooleanField(default=False)),
                ('addl_params', django.contrib.postgres.fields.jsonb.JSONField(default=files_rows.models.FileControl.default_addl_params)),
                ('delimiter', models.CharField(blank=True, max_length=3, null=True, verbose_name='Delimitador de columnas')),
            ],
            options={
                'verbose_name': 'Grupo de archivos',
                'verbose_name_plural': 'Grupos de archivos',
            },
        ),
        migrations.CreateModel(
            name='PetitionFileControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relacional: petición -- file_control',
                'verbose_name_plural': 'Relacional: petición -- file_control',
            },
        ),
        migrations.CreateModel(
            name='PetitionNegativeReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Es la razón principal')),
            ],
            options={
                'verbose_name': 'Petición - razón negativa (m2m)',
                'verbose_name_plural': 'Peticiones - razones negativas (m2m)',
            },
        ),
        migrations.RemoveField(
            model_name='groupfile',
            name='status_register',
        ),
        migrations.RemoveField(
            model_name='groupfile',
            name='type_file',
        ),
        migrations.RemoveField(
            model_name='petitiongroupfile',
            name='group_file',
        ),
        migrations.RemoveField(
            model_name='petitiongroupfile',
            name='petition',
        ),
        migrations.RenameField(
            model_name='transformation',
            old_name='column',
            new_name='name_column',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='petition_group_file',
        ),
        migrations.RemoveField(
            model_name='namecolumn',
            name='group_file',
        ),
        migrations.RemoveField(
            model_name='namecolumn',
            name='type_data',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='negative_reason',
        ),
        migrations.RemoveField(
            model_name='processfile',
            name='type_file',
        ),
        migrations.RemoveField(
            model_name='transformation',
            name='group_file',
        ),
    ]
