# Generated by Django 2.2.25 on 2022-07-26 18:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_rows', '0011_auto_20220726_1321'),
        ('parameter', '0007_auto_20220726_1321'),
        ('files_categories', '0004_auto_20220726_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='namecolumn',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.DataType'),
        ),
        migrations.AddField(
            model_name='petition',
            name='folio_petition',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folio de la solicitud'),
        ),
        migrations.AddField(
            model_name='petition',
            name='folio_queja',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folio de la queja'),
        ),
        migrations.AddField(
            model_name='processfile',
            name='addl_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Otras configuraciones'),
        ),
        migrations.AddField(
            model_name='processfile',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_categories.FileType'),
        ),
        migrations.AddField(
            model_name='processfile',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto (en caso de no haber archivo)'),
        ),
        migrations.AlterField(
            model_name='processfile',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.DeleteModel(
            name='GroupFile',
        ),
        migrations.DeleteModel(
            name='PetitionGroupFile',
        ),
        migrations.AddField(
            model_name='petitionnegativereason',
            name='negative_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_categories.NegativeReason'),
        ),
        migrations.AddField(
            model_name='petitionnegativereason',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_rows.Petition'),
        ),
        migrations.AddField(
            model_name='petitionfilecontrol',
            name='file_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_rows.FileControl'),
        ),
        migrations.AddField(
            model_name='petitionfilecontrol',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_controls', to='files_rows.Petition'),
        ),
        migrations.AddField(
            model_name='filecontrol',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_categories.FileType'),
        ),
        migrations.AddField(
            model_name='filecontrol',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_categories.StatusControl', verbose_name='Status de los registro de variables'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='petition_file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='files_rows.PetitionFileControl'),
        ),
        migrations.AddField(
            model_name='namecolumn',
            name='file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='files_rows.FileControl'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='file_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_tranformations', to='files_rows.FileControl', verbose_name='Grupo de archivos'),
        ),
    ]
